#config_version=4
mode:
  start_events: ball_starting
  stop_events: end_skill_shot, collect_managers_choice, sw_end_skill_shot
  priority: 200

timers:
    skill_shot_timer:
        start_value: 5
        direction: down
        control_events:
          - event: balldevice_bd_plunger_ball_left
            action: start

event_player:
  mode_skill_shot_started:
    - light_managers_choice
  timer_skill_shot_timer_complete:
    - end_managers_choice
    - end_skill_shot

slides:
  skill_shot_stage:
    widgets:
      - type: video
        video: ss_skill_shot
        end_behavior: loop
#      - type: text
#        text: SKILL SHOT INSTRUCTIONS
#        style: stage
  player_start:
    widgets:
      - type: text
        text: PLAYER (number) UP
        style: dmd_huge
        color: ff4400
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 150ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 150ms
            repeat: true
            easing: in_quint
  skill_shot_dmd:
      - type: text
        text: TIME LEFT (skill_shot_skill_shot_timer_tick)
        style: dmd_big

slide_player:
  mode_skill_shot_starting:
    skill_shot_stage:
      target: stage
    player_start:
      target: dmd

  balldevice_bd_plunger_ball_left:
    skill_shot_dmd:
      target: dmd