#config_version=4
mode:
  start_events: ball_starting
  stop_events: end_skill_shot, collect_managers_choice, sw_end_skill_shot
  priority: 200

timers:
    skill_shot_timer:
        start_value: 5
        direction: down
        control_events:
          - event: balldevice_playfield_ball_enter
            action: start

event_player:
  mode_skill_shot_started:
    - light_managers_choice
  timer_skill_shot_timer_complete:
    - end_managers_choice
    - end_skill_shot

slides:
  skill_shot:
    widgets:
      - type: text
        text: SKILL SHOT INSTRUCTIONS
        style: stage
      - type: text
        text: TIME LEFT (skill_shot_skill_shot_timer_tick)
        y: 20%
        style: stage

slide_player:
  mode_skill_shot_started:
    skill_shot:
      target: stage