#config_version=5

mode:
  start_events: ball_starting
  stop_events: end_skill_shot, collect_managers_choice, sw_skill_shot_fail
  priority: 700

#           88                                                         
#    ,d     ""                                                         
#    88                                                                
#  MM88MMM  88  88,dPYba,,adPYba,    ,adPPYba,  8b,dPPYba,  ,adPPYba,  
#    88     88  88P'   "88"    "8a  a8P_____88  88P'   "Y8  I8[    ""  
#    88     88  88      88      88  8PP"""""""  88           `"Y8ba,   
#    88,    88  88      88      88  "8b,   ,aa  88          aa    ]8I  
#    "Y888  88  88      88      88   `"Ybbd8"'  88          `"YbbdP"' 


timers:
  skill_shot_timer:
    start_value: 5
    direction: down
    control_events:
      - event: succesful_eject
        action: start            

#                                                      ,d            
#                                                      88            
#   ,adPPYba,  8b       d8   ,adPPYba,  8b,dPPYba,   MM88MMM         
#  a8P_____88  `8b     d8'  a8P_____88  88P'   `"8a    88            
#  8PP"""""""   `8b   d8'   8PP"""""""  88       88    88            
#  "8b,   ,aa    `8b,d8'    "8b,   ,aa  88       88    88,           
#   `"Ybbd8"'   88 "8"       `"Ybbd8"'  88       88    "Y888         
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

event_player:
  mode_skill_shot_started:
    - light_managers_choice
  timer_skill_shot_timer_complete:
    - end_managers_choice
    - end_skill_shot
  s_topkicker_active:
    - end_skill_shot|3s
  balldevice_bd_plunger_ball_eject_success:
    - succesful_eject #workaround for MC crashing in 0.56

#                                                             88     
#                                                             88     
#                                                             88     
#  ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,    ,adPPYb,88     
#  I8[    ""  a8"     "8a  88       88  88P'   `"8a  a8"    `Y88     
#   `"Y8ba,   8b       d8  88       88  88       88  8b       88     
#  aa    ]8I  "8a,   ,a8"  "8a,   ,a88  88       88  "8a,   ,d88     
#  `"YbbdP"'   `"YbbdP"'    `"YbbdP'Y8  88       88   `"8bbdP"Y8     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

sound_player:
  s_topkicker_active:
    skill_shot_made:
      action: play

#             88  88           88                         
#             88  ""           88                         
#             88               88                         
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,  ,adPPYba,  
#  I8[    ""  88  88  a8"    `Y88  a8P_____88  I8[    ""  
#   `"Y8ba,   88  88  8b       88  8PP"""""""   `"Y8ba,   
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa  aa    ]8I  
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'  `"YbbdP"'

slides:
  skill_shot_stage:
    widgets:
      - type: video
        video: ss_skill_shot
        end_behavior: loop
    target: stage
  player_start:
    widgets:
      - type: text
        text: PLAYER (number) UP
        style: huge 
        color: ff4400
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 150ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 150ms
            repeat: true
            easing: in_quint
      - type: text
        text: SEE STAGE FOR SKILLSHOT!
        style: small 
        anchor_y: top
        y: top
        color: red
      - type: text
        text: BALL (ball)
        style: small 
        anchor_y: bottom
        y: bottom+1
        anchor_x: left
        x: left
      - type: text
        text: (score)
        style: small 
        min_digits: 2
        number_grouping: true
        anchor_y: bottom
        y: bottom+1
        anchor_x: right
        x: right
    target: dmd
  skill_shot_made:
    widgets:
      - type: text
        text: SKILL
        style: big #dmd_big
        color: yellow
        anchor_y: top
        y: top-4
        anchor_x: left
        x: left
      - type: text
        text: SHOT
        style: big #dmd_big
        color: yellow
        anchor_y: top
        y: top-4
        anchor_x: left
        x: 34
      - type: text
        text: COLLECTED
        style: big #dmd_big
        color: yellow
        anchor_y: top
        y: top-4
        anchor_x: right
        x: right
      - type: text
        text: 500000
        number_grouping: true
        style: big #dmd_big
        anchor_y: bottom
        y: bottom+4
        animations:
          show_slide:
            - property: opacity
              value: .3
              duration: 150ms
            - property: opacity
              value: 1
              duration: 150ms
              repeat: true

#             88  88           88                                    
#             88  ""           88                                    
#             88               88                                    
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,                        
#  I8[    ""  88  88  a8"    `Y88  a8P_____88                        
#   `"Y8ba,   88  88  8b       88  8PP"""""""                        
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa                        
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

slide_player:
  mode_skill_shot_started:
    skill_shot_stage:
      target: stage
    player_start:
      target: dmd
  s_topkicker_active:
    skill_shot_made:
      target: dmd
      expire: 3s
  succesful_eject:
    player_start:
      action: remove
      target: dmd
  end_skill_shot:
    skill_shot_stage:
      action: remove
      target: stage
  skill_shot_fail:
    skill_shot_stage:
      action: remove
      target: stage
      force: true

#                                       88              88           88              
#                                       ""              88           88              
#                                                       88           88              
#  8b       d8  ,adPPYYba,  8b,dPPYba,  88  ,adPPYYba,  88,dPPYba,   88   ,adPPYba,  
#  `8b     d8'  ""     `Y8  88P'   "Y8  88  ""     `Y8  88P'    "8a  88  a8P_____88  
#   `8b   d8'   ,adPPPPP88  88          88  ,adPPPPP88  88       d8  88  8PP"""""""  
#    `8b,d8'    88,    ,88  88          88  88,    ,88  88b,   ,a8"  88  "8b,   ,aa  
#      "8"      `"8bbdP"Y8  88          88  `"8bbdP"Y8  8Y"Ybbd8"'   88   `"Ybbd8"'
#               88                                                                   
#               88                                                                   
#               88                                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,                  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8                  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88                          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88                          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88                          
#  88                               d8'                                              
#  88                              d8' 

#scoring: #leaving for reference
variable_player:
  s_topkicker_active:
    score: 500000
