#config_version=4
mode:
  start_events: ball_starting
  stop_events: end_skill_shot, collect_managers_choice, sw_end_skill_shot
  priority: 200

timers:
    skill_shot_timer:
        start_value: 5
        direction: down
        control_events:
          - event: balldevice_bd_plunger_ball_eject_success
            action: start

event_player:
  mode_skill_shot_started:
    - light_managers_choice
  timer_skill_shot_timer_complete:
    - end_managers_choice
    - end_skill_shot

slides:
  skill_shot_stage:
    widgets:
      - type: video
        video: ss_skill_shot
        end_behavior: loop
  player_start:
    widgets:
      - type: text
        text: PLAYER (number) UP
        style: dmd_huge
        color: ff4400
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 150ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 150ms
            repeat: true
            easing: in_quint
      - type: text
        text: SEE STAGE FOR SKILLSHOT!
        style: dmd_small
        anchor_y: top
        y: top
        color: red
      - type: text
        text: BALL (ball)
        style: dmd_small
        anchor_y: bottom
        y: 0
        anchor_x: left
        x: left
      - type: text
        text: (score)
        style: dmd_small
        min_digits: 2
        number_grouping: true
        anchor_y: bottom
        y: 0
        anchor_x: right
        x: right

slide_player:
  mode_skill_shot_starting:
    skill_shot_stage:
      target: stage
    player_start:
      target: dmd

  balldevice_bd_plunger_ball_eject_success:
    player_start:
      action: remove