#config_version=5
#config_version=4 # Left for reference. Did NOT double check
mode:
  start_events: ball_starting
  stop_events: end_skill_shot, collect_managers_choice
  priority: 700

timers:
    skill_shot_timer:
        start_value: 5
        direction: down
        control_events:
          - event: succesful_eject
            action: start

event_player:
  mode_skill_shot_started:
    - light_managers_choice
  timer_skill_shot_timer_complete:
    - end_managers_choice
    - end_skill_shot
  s_topkicker_active:
    - end_skill_shot|3s
  balldevice_bd_plunger_ball_eject_success:
    - succesful_eject #workaround for MC crashing in 0.56

sound_player:
  s_topkicker_active:
    skill_shot_made:
      action: play

slides:
  skill_shot_stage:
    widgets:
      - type: video
        video: ss_skill_shot
        end_behavior: loop
    target: stage
  player_start:
    widgets:
      - type: text
        text: PLAYER (number) UP
        style: huge #dmd_huge
        color: ff4400
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 150ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 150ms
            repeat: true
            easing: in_quint
      - type: text
        text: SEE STAGE FOR SKILLSHOT!
        style: small #dmd_small
        anchor_y: top
        y: top
        color: red
      - type: text
        text: BALL (ball)
        style: small #dmd_small
        anchor_y: bottom
        y: 0
        anchor_x: left
        x: left
      - type: text
        text: (score)
        style: small #dmd_small
        min_digits: 2
        number_grouping: true
        anchor_y: bottom
        y: 0
        anchor_x: right
        x: right
    target: dmd
  skill_shot_made:
    widgets:
      - type: text
        text: SKILL
        style: big #dmd_big
        color: yellow
        anchor_y: top
        y: top-4
        anchor_x: left
        x: left
      - type: text
        text: SHOT
        style: big #dmd_big
        color: yellow
        anchor_y: top
        y: top-4
        anchor_x: left
        x: 34
      - type: text
        text: COLLECTED
        style: big #dmd_big
        color: yellow
        anchor_y: top
        y: top-4
        anchor_x: right
        x: right
      - type: text
        text: 500000
        number_grouping: true
        style: big #dmd_big
        anchor_y: bottom
        y: bottom+4
        animations:
          show_slide:
            - property: opacity
              value: .3
              duration: 150ms
            - property: opacity
              value: 1
              duration: 150ms
              repeat: true

slide_player:
  mode_skill_shot_started:
    skill_shot_stage:
      target: stage
    player_start:
      target: dmd
  s_topkicker_active:
    skill_shot_made:
      target: dmd
      expire: 3s
  succesful_eject:
    player_start:
      action: remove
      target: dmd

#scoring: #leaving for reference
variable_player:
  s_topkicker_active:
    score: 500000
