#config_version=4
mode:
  start_events: ball_starting
  stop_events: end_skill_shot, collect_managers_choice, sw_end_skill_shot
  priority: 200

timers:
    skill_shot_timer:
        start_value: 5
        direction: down
        control_events:
          - event: balldevice_bd_plunger_ball_left
            action: start

event_player:
  mode_skill_shot_started:
    - light_managers_choice
  timer_skill_shot_timer_complete:
    - end_managers_choice
    - end_skill_shot

slides:
  skill_shot_stage:
    widgets:
      - type: video
        video: ss_skill_shot
        end_behavior: loop
#      - type: text
#        text: SKILL SHOT INSTRUCTIONS
#        style: stage
  skill_shot_dmd:
    widgets:
      - type: text
        text: TIME LEFT (skill_shot_skill_shot_timer_tick)
        y: 20%

slide_player:
  mode_skill_shot_started:
    skill_shot_stage:
      target: stage
    skill_shot_dmd:
      target: dmd
