#config_version=5

mode:
  priority: 160
  start_events: mode_base_started


#                                                       ,d                                        
#                                                       88                                        
#   ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,   MM88MMM   ,adPPYba,  8b,dPPYba,  ,adPPYba,  
#  a8"     ""  a8"     "8a  88       88  88P'   `"8a    88     a8P_____88  88P'   "Y8  I8[    ""  
#  8b          8b       d8  88       88  88       88    88     8PP"""""""  88           `"Y8ba,   
#  "8a,   ,aa  "8a,   ,a8"  "8a,   ,a88  88       88    88,    "8b,   ,aa  88          aa    ]8I  
#   `"Ybbd8"'   `"YbbdP"'    `"YbbdP'Y8  88       88    "Y888   `"Ybbd8"'  88          `"YbbdP"' 


#logic_blocks:
counters:
  albums:
    count_events: drop_target_bank_drop_targets_down
    events_when_hit: num_albums
    persist_state: false
    count_complete_value: 20
    starting_count: current_player.temp_num_albums
    
#                                                      ,d            
#                                                      88            
#   ,adPPYba,  8b       d8   ,adPPYba,  8b,dPPYba,   MM88MMM         
#  a8P_____88  `8b     d8'  a8P_____88  88P'   `"8a    88            
#  8PP"""""""   `8b   d8'   8PP"""""""  88       88    88            
#  "8b,   ,aa    `8b,d8'    "8b,   ,aa  88       88    88,           
#   `"Ybbd8"'   88 "8"       `"Ybbd8"'  88       88    "Y888         
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'


# event_player:
#   player_num_albums: show_album_slide|.1s

#                                       88              88           88              
#                                       ""              88           88              
#                                                       88           88              
#  8b       d8  ,adPPYYba,  8b,dPPYba,  88  ,adPPYYba,  88,dPPYba,   88   ,adPPYba,  
#  `8b     d8'  ""     `Y8  88P'   "Y8  88  ""     `Y8  88P'    "8a  88  a8P_____88  
#   `8b   d8'   ,adPPPPP88  88          88  ,adPPPPP88  88       d8  88  8PP"""""""  
#    `8b,d8'    88,    ,88  88          88  88,    ,88  88b,   ,a8"  88  "8b,   ,aa  
#      "8"      `"8bbdP"Y8  88          88  `"8bbdP"Y8  8Y"Ybbd8"'   88   `"Ybbd8"'
#               88                                                                   
#               88                                                                   
#               88                                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,                  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8                  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88                          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88                          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88                          
#  88                               d8'                                              
#  88                              d8' 


variable_player:
 
  num_albums{count==1}:
    album_value:
      int: 25000
      action: set
    album_name:
      string: SILVER
      action: set
    score: 25000
    multiplier:
      int: 2
      action: set
    temp_num_albums: # Used to help preserve album status when multiplier is held. See base mode code.
      int: 1
      action: set
    temp_next_album_name:
      string: GOLD
      action: set
    temp_next_album_num_albums_count:
      int: 2
      action: set
  
  

  num_albums{count==2}:
    album_value:
      int: 50000
      action: set
    album_name:
      string: GOLD
      action: set
    score: 50000
    multiplier:
      int: 3
      action: set
    temp_num_albums:
      int: 2
      action: set
    temp_next_album_name:
      string: PLATINUM
      action: set
    temp_next_album_num_albums_count:
      int: 4
      action: set


  num_albums{count==4}:
    album_value:
      int: 100000
      action: set
    album_name:
      string: PLATINUM
      action: set
    score: 100000
    multiplier:
      int: 4
      action: set
    temp_num_albums:
      int: 4
      action: set
    temp_next_album_name:
      string: DOUBLE PLATINUM
      action: set
    temp_next_album_num_albums_count:
      int: 7
      action: set

  num_albums{count==7}:
    album_value:
      int: 200000
      action: set
    album_name:
      string: DOUBLE PLATINUM
      action: set
    score: 200000
    multiplier:
      int: 5
      action: set
    temp_num_albums:
      int: 7
      action: set
    temp_next_album_name:
      string: QUINTUPLE PLATINUM
      action: set
    temp_next_album_num_albums_count:
      int: 12
      action: set

  num_albums{count==12}:
    album_value:
      int: 500000
      action: set
    album_name:
      string: QUINTUPLE PLATINUM
      action: set
    score: 500000
    multiplier:
      int: 6
      action: set
    temp_num_albums:
      int: 12
      action: set
    temp_next_album_name:
      string: OFF THE CHARTS
      action: set
    temp_next_album_num_albums_count:
      int: 20
      action: set


  num_albums{count==20}:  # beyond 20 we don't increase anymore
    album_value:
      int: 2500000
      action: set
    album_name:
      string: OFF THE CHARTS
      action: set
    score: 2500000
    album_int:
      int: 6
    multiplier:
      int: 9
      action: set
    temp_num_albums:
      int: 20
      action: set

  # To get current_num_albums_difference, need to know temp_next_album_num_albums_count and the value of the albums counter.

  num_albums{count>=1}:
    current_num_albums_count:
      int: count
      action: set
    
    current_num_albums_difference:
      int: current_player.temp_next_album_num_albums_count - current_player.current_num_albums_count
      action: set


#             88  88           88                                    
#             88  ""           88                                    
#             88               88                                    
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,                        
#  I8[    ""  88  88  a8"    `Y88  a8P_____88                        
#   `"Y8ba,   88  88  8b       88  8PP"""""""                        
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa                        
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

slide_player:
  num_albums{count == 1}:
    album_silver:
      expire: 2s
      priority: 160
  num_albums{count == 2}:
      album_gold:
        expire: 2s
        priority: 160
  num_albums{count == 4}:
      album_platinum:
        expire: 2s
        priority: 160
  num_albums{count == 7}:
      album_platinum:
        expire: 2s
        priority: 160
  num_albums{count == 12}:
      album_platinum:
        expire: 2s
        priority: 160
  num_albums{count >= 20}:
      album_off_the_charts:
        expire: 2s
        priority: 160
  num_albums{count == 3}:
    knockdowns_to_go:
      expire: 2s
      priority: 160
  num_albums{current_player.current_num_albums_difference >= 2}:
    knockdowns_to_go:
      expire: 2s
      priority: 158
  num_albums{current_player.current_num_albums_difference == 1}:
    one_knockdown_to_go:
      expire: 2s
      priority: 159


#             88  88           88                         
#             88  ""           88                         
#             88               88                         
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,  ,adPPYba,  
#  I8[    ""  88  88  a8"    `Y88  a8P_____88  I8[    ""  
#   `"Y8ba,   88  88  8b       88  8PP"""""""   `"Y8ba,   
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa  aa    ]8I  
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'  `"YbbdP"'

slides:
  one_knockdown_to_go:
    widgets:
      - type: text
        text: (player|current_num_albums_difference)
        #text: 17
        anchor_y: top
        anchor_x: left
        y: top-1
        x: left+18
        style: big
        color: white
      - type: text
        text: "ALBUM UNTIL"
        color: white
        style: big
        anchor_y: top
        anchor_x: left
        y: top-1
        x: left+33
      - type: text
        text: (player|temp_next_album_name)
        style: huge 
        anchor_y: bottom
        y: bottom-3
        color: white
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 250ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 250ms
            repeat: true
            easing: in_quint
      - type: rectangle
        width: 128
        height: 32
        color: 444444  
  knockdowns_to_go:
    widgets:
      - type: text
        text: (player|current_num_albums_difference)
        #text: 17
        anchor_y: top
        anchor_x: left
        y: top-1
        x: left+18
        style: big
        color: white
      - type: text
        text: "ALBUMS UNTIL"
        color: white
        style: big
        anchor_y: top
        anchor_x: left
        y: top-1
        x: left+33
      - type: text
        text: (player|temp_next_album_name)
        style: huge 
        anchor_y: bottom
        y: bottom-3
        color: white
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 250ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 250ms
            repeat: true
            easing: in_quint
      - type: rectangle
        width: 128
        height: 32
        color: 444444

  album_silver:
    widgets:
      - type: text
        text: (player|album_name)
        style: huge 
        y: 22
        color: aaaaaa
      - type: text
        text: (player|album_value)
        style: big #dmd_big
        y: 7
        color: aaaaaa
        number_grouping: true
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 50ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 50ms
            repeat: true
            easing: in_quint
  album_gold:
    widgets:
      - type: text
        text: (player|album_name)
        style: huge 
        y: 22
        color: gold
      - type: text
        text: (player|album_value)
        style: big #dmd_big
        y: 7
        color: gold
        number_grouping: true
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 50ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 50ms
            repeat: true
            easing: in_quint
  album_platinum:  # used for all three platinum awards
    widgets:
      - type: text
        text: (player|album_name)
        style: huge 
        y: 22
        color: black
      - type: text
        text: (player|album_value)
        style: big #dmd_big
        y: 7
        color: black
        number_grouping: true
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 50ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 50ms
            repeat: true
            easing: in_quint
      - type: rectangle
        width: 128
        height: 32
  album_off_the_charts:
    widgets:
      - type: text
        text: (player|album_name)
        style: huge 
        y: 22
        color: black
      - type: text
        text: (player|album_value)
        style: big #dmd_big
        y: 7
        color: black
        number_grouping: true
      - type: rectangle
        width: 128
        height: 32
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 50ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 50ms
            repeat: true
            easing: in_quint

#                                                             88     
#                                                             88     
#                                                             88     
#  ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,    ,adPPYb,88     
#  I8[    ""  a8"     "8a  88       88  88P'   `"8a  a8"    `Y88     
#   `"Y8ba,   8b       d8  88       88  88       88  8b       88     
#  aa    ]8I  "8a,   ,a8"  "8a,   ,a88  88       88  "8a,   ,d88     
#  `"YbbdP"'   `"YbbdP"'    `"YbbdP'Y8  88       88   `"8bbdP"Y8     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

sound_player:
  num_albums{count == 1}:
    ma_silver:
      action: play
      loops: 0
  num_albums{count == 2}:
    ma_gold:
      action: play
      loops: 0
  num_albums{count == 4}:
    ma_platinum:
      action: play
      loops: 0
  num_albums{count == 7}:
    ma_double_platinum:
      action: play
      loops: 0
  num_albums{count == 12}:
    ma_quintuple_platinum:
      action: play
      loops: 0
  num_albums{count >= 20}:
    ma_off_the_charts:
      action: play
      loops: 0