#config_version=5

mode:
  priority: 600
  start_events: start_managers_choice
  stop_events: release_top_kicker_ball, stop_managers_choice



#             88                                                     
#             88                                                     
#             88                                                     
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   8b      db      d8           
#  I8[    ""  88P'    "8a  a8"     "8a  `8b    d88b    d8'           
#   `"Y8ba,   8888     88  8b       d8   `8b  d8'`8b  d8'            
#  aa    ]8I  8888     88  "8a,   ,a8"    `8bd8'  `8bd8'             
#  `"YbbdP"'  8888     88   `"YbbdP"'       YP      YP               
#
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

show_player:
  mode_managers_choice_started:
    mc_intro_show:
      loops: 0

#             88  88           88                         
#             88  ""           88                         
#             88               88                         
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,  ,adPPYba,  
#  I8[    ""  88  88  a8"    `Y88  a8P_____88  I8[    ""  
#   `"Y8ba,   88  88  8b       88  8PP"""""""   `"Y8ba,   
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa  aa    ]8I  
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'  `"YbbdP"'

slides:
  mcsl_title:
    widgets:
      - type: line # part of an apostrophe
        points: 65, 22, 65, 20
        color: red
      - type: line # part of an apostrophe
        points: 66, 22, 66, 18
        color: red
      - type: points # part of an apostrophe
        points: 65, 18
        color: red
        pointsize: .5
      - type: text
        text: S
        style: big #dmd_big
        anchor_y: center
        y: center
        anchor_x: left
        x: 67
        color: red
      - type: text
        text: MANAGER
        style: big #dmd_big
        anchor_y: center
        y: center
        anchor_x: right
        x: 64
        color: red
      - type: text
        text: CHOICE
        style: big #dmd_big
        anchor_y: center
        y: center
        anchor_x: left
        x: 79
        color: white
  mcsl_start_mission:
    widgets:
      - type: text
        text: STARTING ROUND...
        color: red
        style: big #dmd_big
  mcsl_world_tour:
    widgets:
      - type: text
        text: WORLD TOUR
        color: red
        style: big #dmd_big
  mcsl_money_bags:
    widgets:
      - type: text
        text: MONEY BAGS
        color: red
        style: big #dmd_big
  mcsl_music_awards:
    widgets:
      - type: text
        text: MUSIC AWARDS
        color: red
        style: big #dmd_big
  mcsl_jukebox:
    widgets:
      - type: text
        text: JUKEBOX
        color: red
        style: big #dmd_big
  mcsl_play_poker:
    widgets:
      - type: text
        text: PLAY POKER
        color: red
        style: big #dmd_big
  mcsl_last_slide:
      widgets:
        - type: rectangle
          width: 128
          height: 32
          color: white
          opacity: 0
          animations:
            show_slide:
              - property: opacity
                value: 0
                duration: .8s
              - property: opacity
                value: 1
                duration: .3s
        - type: text
          text: WORLD TOUR
          color: red
          style: small 
          x: center-33
          y: bottom+5
        - type: text
          text: PLAY POKER
          color: red
          style: small 
          x: center-33
          y: bottom+16
        - type: text
          text: MUSIC AWARDS
          color: red
          style: small 
          x: center+30
          y: bottom+16
        - type: text
          text: MONEY BAGS
          color: red
          style: small 
          x: center+30
          y: bottom+5
        - type: text
          text: JUKEBOX
          color: red
          style: small 
          x: center
          y: top-5

#                      88           88                                               
#                      ""           88                             ,d                
#                                   88                             88                
#  8b      db      d8  88   ,adPPYb,88   ,adPPYb,d8   ,adPPYba,  MM88MMM  ,adPPYba,  
#  `8b    d88b    d8'  88  a8"    `Y88  a8"    `Y88  a8P_____88    88     I8[    ""  
#   `8b  d8'`8b  d8'   88  8b       88  8b       88  8PP"""""""    88      `"Y8ba,   
#    `8bd8'  `8bd8'    88  "8a,   ,d88  "8a,   ,d88  "8b,   ,aa    88,    aa    ]8I  
#      YP      YP      88   `"8bbdP"Y8   `"YbbdP"Y8   `"Ybbd8"'    "Y888  `"YbbdP"'  
#                                        aa,    ,88                                  
#                                         "Y8bbdP"  

widgets:
  mcw_white_box:
    - type: rectangle
      width: 128
      height: 32
      color: white
      opacity: 0
      animations:
        add_to_slide:
          - property: opacity
            value: 1
            duration: 300ms


#  88                       88  88                       
#  88                       88  88                       
#  88                       88  88                       
#  88,dPPYba,   ,adPPYYba,  88  88                       
#  88P'    "8a  ""     `Y8  88  88                       
#  88       d8  ,adPPPPP88  88  88                       
#  88b,   ,a8"  88,    ,88  88  88                       
#  8Y"Ybbd8"'   `"8bbdP"Y8  88  88                       
#  88                        88           88             
#  88                        88           88             
#  88                        88           88             
#  88,dPPYba,    ,adPPYba,   88   ,adPPYb,88  ,adPPYba,  
#  88P'    "8a  a8"     "8a  88  a8"    `Y88  I8[    ""  
#  88       88  8b       d8  88  8b       88   `"Y8ba,   
#  88       88  "8a,   ,a8"  88  "8a,   ,d88  aa    ]8I  
#  88       88   `"YbbdP"'   88   `"8bbdP"Y8  `"YbbdP"'

# ball_holds:
#   mc_intro_hold:
#     balls_to_hold: 1
#     hold_devices: bd_top_kicker
#     enable_events: mode_managers_choice_started
#     release_one_events: release_top_kicker_ball
#     disable_events: mode_managers_choice_stopping