#config_version=4

high_score:
  _overwrite: True
  categories:
  - score:
    - GRAND CHAMPION
    - HIGH SCORE 1
    - HIGH SCORE 2
    - HIGH SCORE 3
    - HIGH SCORE 4
  - quarters:
    - QUARTERS CHAMP

  defaults:
    score:
      - GHK: 10000000
      - BSM: 8000000
      - JAB: 6000000
      - QDG: 4000000
      - TIM: 2000000
    quarters:
      - JON: 5

slides:
  _overwrite:
  high_score_enter_initials:
  - type: text
    text: PLAYER (player_num)
    style: dmd_med
    anchor_y: bottom
    x: center-27
    y: bottom+21
  - type: text
    text: (award)
    style: dmd_small
    anchor_y: bottom
    x: center-27
    y: bottom+12
  - type: text_input
    key: high_score
    style: dmd_med
    anchor_y: bottom
    max_chars: 3
    y: 1
    animations:
      show_slide:
      - property: opacity
        value: 1
        duration: 0.3s
        easing: in_out_quint
      - property: opacity
        value: 0
        duration: 0.3s
        repeat: true
        easing: in_out_quint

  - type: text
    text: ""
    key: high_score
    anchor_x: left
    x: left+90
    style: dmd_big

  high_score_award_display:
  - type: text
    text: (player_name)
    color: 0
    style: dmd_huge
    y: middle-2
    animations:
      show_slide:
      - property: opacity
        value: 1
        duration: 0.05s
      - property: opacity
        value: 0
        duration: 0.05s
        repeat: true
  - type: text
    text: (award)
    style: dmd_med
    anchor_y: top
    y: top-2