#config_version=5

event_player:
  slide_jb_hurry_up_foggy_mountain_removed: fade_in_music
  slide_full_louisiana_woman_removed: fade_in_music
  slide_full_bed_of_roses_removed: fade_in_music
  slide_full_boots_are_made_for_walkin_removed: fade_in_music
  slide_mb_beer_thirty_removed: fade_in_music
  slide_htmb_miss_honky_tonk_removed: fade_in_music
  slide_full_hello_darlin_removed: fade_in_music
  slide_full_stand_by_your_man_removed: fade_in_music
  slide_jb_hard_workin_man_removed: fade_in_music
  slide_ma_12many_full_removed: fade_in_music
  slide_ma_play_something_country_removed: fade_in_music
  slide_qmb_put_a_girl_in_it_removed: fade_in_music
  slide_full_rhinestone_cowboy_removed: fade_in_music
  slide_full_every_little_thing_removed: fade_in_music
  slide_wt_boot_scoot_removed: fade_in_music
  slide_ma_my_maria_removed: fade_in_music
  slide_full_achy_breaky_removed: fade_in_music
  slide_full_convoy_removed: fade_in_music
  slide_mr_bed_removed: fade_in_music
  slide_neon_moon_100_pct_removed: fade_in_music

#             88                                                       
#             88                                                       
#             88                                                       
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   8b      db      d8   
#  I8[    ""  88P'    "8a  a8"     "8a  `8b    d88b    d8'   
#   `"Y8ba,   88       88  8b       d8   `8b  d8'`8b  d8'     
#  aa    ]8I  88       88  "8a,   ,a8"    `8bd8'  `8bd8'     
#  `"YbbdP"'  88       88   `"YbbdP"'       YP      YP     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8' 



show_player:
  mode_attract_started:
    attract_dmd_loop:
      loops: -1
    attract_stage_loop:
      priority: 100
      loops: -1
    ######gi_on: #{} #This was in there...not sure why.
    center_light_sweep:
      speed: 2
    attract_music_lights:
      loops: -1
      show_tokens:
        left: left
        center: center
        right: right
    flash:
      loops: -1
      show_tokens:
        led: l_start_button
  flipper_cancel:
    music_video: stop
  sw_right_flipper:
    attract_dmd_loop:
      action: advance
  sw_left_flipper:
    attract_dmd_loop:
      action: step_back
  mode_attract_stopped:
    attract_dmd_loop:
      action: stop
    attract_stage_loop:  # todo test if we have to do this?
      action: stop
      #target: stage
    attract_music_lights:
      action: stop
    music_video: stop

#                                                             88     
#                                                             88     
#                                                             88     
#  ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,    ,adPPYb,88     
#  I8[    ""  a8"     "8a  88       88  88P'   `"8a  a8"    `Y88     
#   `"Y8ba,   8b       d8  88       88  88       88  8b       88     
#  aa    ]8I  "8a,   ,a8"  "8a,   ,a88  88       88  "8a,   ,d88     
#  `"YbbdP"'   `"YbbdP"'    `"YbbdP'Y8  88       88   `"8bbdP"Y8     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

sound_player:
  mode_attract_started:
    base_bed_loop:
      action: play
      loops: -1
      mode_end_action: stop

  s_start_active:
    start_pool:
      action: play

  timer_video_timer_complete:
    base_bed_loop:
      fade_out: 500ms
      action: stop

  fade_in_music:
    base_bed_loop:
      fade_in: 500ms
      action: play
    
  


#                                                             88  
#                                                             88  
#                                                             88  
#  ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,    ,adPPYb,88  
#  I8[    ""  a8"     "8a  88       88  88P'   `"8a  a8"    `Y88  
#   `"Y8ba,   8b       d8  88       88  8888     88  8b       88  
#  aa    ]8I  "8a,   ,a8"  "8a,   ,a88  8888     88  "8a,   ,d88  
#  `"YbbdP"'   `"YbbdP"'    `"YbbdP'Y8  8888     88   `"8bbdP"Y8  
#
#  8b,dPPYba,    ,adPPYba,    ,adPPYba,   88  ,adPPYba,           
#  88P'    "8a  a8"     "8a  a8"     "8a  88  I8[    ""           
#  88       d8  8b       d8  8b       d8  88   `"Y8ba,            
#  88b,   ,a8"  "8a,   ,a8"  "8a,   ,a8"  88  aa    ]8I           
#  88`YbbdP"'    `"YbbdP"'    `"YbbdP"'   88  `"YbbdP"'           
#  88                                                             
#  88

sound_pools:
  start_pool:
    type: random
    track: voice
    sounds:
      - start_let_the_horses_burn
      - start_get_down
      - start_lets_go_boot_scoot

#           88                                                         
#    ,d     ""                                                         
#    88                                                                
#  MM88MMM  88  88,dPYba,,adPYba,    ,adPPYba,  8b,dPPYba,  ,adPPYba,  
#    88     88  88P'   "88"    "8a  a8P_____88  88P'   "Y8  I8[    ""  
#    88     88  88      88      88  8PP"""""""  88           `"Y8ba,   
#    88,    88  88      88      88  "8b,   ,aa  88          aa    ]8I  
#    "Y888  88  88      88      88   `"Ybbd8"'  88          `"YbbdP"'

timers:
  video_timer:
    start_value: 600
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: true
    restart_on_complete: true
    control_events:
      - event: flipper_cancel
        action: stop
      - event: test_accelerate
        action: jump
        value: 2

random_event_player:
  timer_video_timer_complete:
    scope: machine
    force_all: true
    events:
      - play_jb_hurry_up_foggy_mountain
      - play_full_louisiana_woman
      - play_full_bed_of_roses
      - play_full_boots_are_made_for_walkin
      - play_mb_beer_thirty
      - play_htmb_miss_honky_tonk
      - play_full_hello_darlin
      - play_full_stand_by_your_man
      - play_jb_hard_workin_man
      - play_ma_12many_full
      - play_ma_play_something_country
      - play_qmb_put_a_girl_in_it
      - play_full_rhinestone_cowboy
      - play_full_every_little_thing
      - play_wt_boot_scoot
      - play_ma_my_maria
      - play_full_achy_breaky
      - play_full_convoy
      - play_mr_bed
      - play_neon_moon_100_pct


slide_player:

  play_jb_hurry_up_foggy_mountain:
    jb_hurry_up_foggy_mountain:
      target: stage
      priority: 200

  play_full_louisiana_woman:
    full_louisiana_woman:
      target: stage
      priority: 200

  play_full_bed_of_roses:
    full_bed_of_roses:
      target: stage
      priority: 200

  play_full_boots_are_made_for_walkin:
    full_boots_are_made_for_walkin:
      target: stage
      priority: 200

  play_mb_beer_thirty:
    mb_beer_thirty:
      target: stage
      priority: 200

  play_htmb_miss_honky_tonk:
    htmb_miss_honky_tonk:
      target: stage
      priority: 200

  play_full_hello_darlin:
    full_hello_darlin:
      target: stage
      priority: 200

  play_full_stand_by_your_man:
    full_stand_by_your_man:
      target: stage
      priority: 200

  play_jb_hard_workin_man:
    jb_hard_workin_man:
      target: stage
      priority: 200

  play_ma_12many_full:
    ma_12many_full:
      target: stage
      priority: 200

  play_ma_play_something_country:
    ma_play_something_country:
      target: stage
      priority: 200

  play_qmb_put_a_girl_in_it:
    qmb_put_a_girl_in_it:
      target: stage
      priority: 200

  play_full_rhinestone_cowboy:
    full_rhinestone_cowboy:
      target: stage
      priority: 200

  play_full_every_little_thing:
    full_every_little_thing:
      target: stage
      priority: 200

  play_wt_boot_scoot:
    wt_boot_scoot:
      target: stage
      priority: 200

  play_ma_my_maria:
    ma_my_maria:
      target: stage
      priority: 200

  play_full_achy_breaky:
    full_achy_breaky:
      target: stage
      priority: 200

  play_full_convoy:
    full_convoy:
      target: stage
      priority: 200

  play_mr_bed:
    mr_bed:
      target: stage
      priority: 200

  play_neon_moon_100_pct:
    neon_moon_100_pct:
      target: stage
      priority: 200


slides:

  jb_hurry_up_foggy_mountain:
    widgets:
    - type: video
      video: jb_hurry_up_foggy_mountain
      volume: 0.5
    expire: 91s

  full_louisiana_woman:
    widgets:
    - type: video
      video: full_louisiana_woman  
      volume: 0.5
    expire: 124s

  full_bed_of_roses:
    widgets:
    - type: video
      video: full_bed_of_roses
      volume: 0.5
    expire: 149s

  full_boots_are_made_for_walkin:
    widgets:
    - type: video
      video: full_boots_are_made_for_walkin
      volume: 0.5
    expire: 150s

  mb_beer_thirty:
    widgets:
    - type: video
      video: mb_beer_thirty
      volume: 0.5
    expire: 152s

  htmb_miss_honky_tonk:
    widgets:
    - type: video
      video: htmb_miss_honky_tonk
      volume: 0.5
    expire: 153s

  full_hello_darlin:
    widgets:
    - type: video
      video: full_hello_darlin
      volume: 0.5
    expire: 153s

  full_stand_by_your_man:
    widgets:
    - type: video
      video: full_stand_by_your_man
      volume: 0.5
    expire: 155s

  jb_hard_workin_man:
    widgets:
    - type: video
      video: jb_hard_workin_man
      volume: 0.5
    expire: 177s

  ma_12many_full:
    widgets:
    - type: video
      video: ma_12many_full
      volume: 0.5
    expire: 180s

  ma_play_something_country:
    widgets:
    - type: video
      video: ma_play_something_country
      volume: 0.5
    expire: 185s

  qmb_put_a_girl_in_it:
    widgets:
    - type: video
      video: qmb_put_a_girl_in_it
      volume: 0.5
    expire: 185s

  full_rhinestone_cowboy:
    widgets:
    - type: video
      video: full_rhinestone_cowboy
      volume: 0.5
    expire: 189s

  full_every_little_thing:
    widgets:
    - type: video
      video: full_every_little_thing
      volume: 0.5
    expire: 193s

  wt_boot_scoot:
    widgets:
    - type: video
      video: wt_boot_scoot
      volume: 0.5
    expire: 197s

  ma_my_maria:
    widgets:
    - type: video
      video: ma_my_maria
      volume: 0.5
    expire: 205s

  full_achy_breaky:
    widgets:
    - type: video
      video: full_achy_breaky
      volume: 0.5
    expire: 214s

  full_convoy:
    widgets:
    - type: video
      video: full_convoy
      volume: 0.5
    expire: 221s

  mr_bed:
    widgets:
    - type: video
      video: mr_bed
      volume: 0.5
    expire: 236s

  neon_moon_100_pct:
    widgets:
    - type: video
      video: neon_moon_100_pct
      volume: 0.5
    expire: 251s


#             88                                                       
#             88                                                       
#             88                                                       
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   8b      db      d8  ,adPPYba,  
#  I8[    ""  88P'    "8a  a8"     "8a  `8b    d88b    d8'  I8[    ""  
#   `"Y8ba,   88       88  8b       d8   `8b  d8'`8b  d8'    `"Y8ba,   
#  aa    ]8I  88       88  "8a,   ,a8"    `8bd8'  `8bd8'    aa    ]8I  
#  `"YbbdP"'  88       88   `"YbbdP"'       YP      YP      `"YbbdP"' 

shows:
  attract_music_lights:
    - duration: .39s
      lights:
        (left): on
        (right): off
        (center): off
    - duration: .39s
      lights:
        (left): off
        (right): on
        (center): off
    - duration: .39s
      lights:
        (left): off
        (right): off
        (center): on
    - duration: .20s
      lights:
        (left): on
        (right): on
        (center): on
    - duration: .19s
      lights:
        (left): off
        (right): off
        (center): off
  