#config_version=4

show_player:
  mode_attract_started:
    attract_dmd_loop:
      loops: -1
    attract_stage_loop:
      loops: -1
    gi_on: {}
    center_light_sweep:
      speed: 2
    attract_music_lights:
      loops: -1
      show_tokens:
        left: left
        center: center
        right: right
    flash:
      loops: -1
      show_tokens:
        led: l_start_button

#slide_player:
#  game_ended: # move this to match
#    how_long_gone_stage:
#      target: stage
#
#slides:
#  how_long_gone_stage: # move this to match
#    widgets:
#      - type: video
#        video: how_long_gone
#        end_behavior: stop
#        animations:
#          show_slide:
#            - property: opacity
#              value: 1
#              duration: 10s
#            - property: opacity
#              value: 0
#              duration: 2s

  mode_attract_stopped:
    attract_dmd_loop:
      action: stop
    attract_stage_loop:  # todo test if we have to do this?
      action: stop
      target: stage
    attract_music_lights:
      action: stop

sound_player:
  mode_attract_started:
    base_bed_loop:
      action: play
      loops: -1
      mode_end_action: stop

#timers:
#  video_timer:
#    start_value: 0
#    end_value: 480
#    direction: up
#    tick_interval: 1s
#    start_running: true
#    restart_on_complete: true

random_event_player:
    timer_video_timer_complete:
      force_all: true
      events:
        full_bed_of_roses
        full_achy_breaky
        full_convoy
        full_every_little_thing
        full_boots_are_made_for_walkin
        full_hello_darlin
        full_louisiana_woman
        full_rhinestone_cowboy
        full_stand_by_your_man
        ma_my_maria
        jb_hard_workin_man
        mb_beer_thirty
        wt_boot_scoot
        pp_honky_tonk_stomp
        mr_bed

shows:
  attract_music_lights:
    - duration: .39s
      leds:
        (left): on
        (right): off
        (center): off
    - duration: .39s
      leds:
        (left): off
        (right): on
        (center): off
    - duration: .39s
      leds:
        (left): off
        (right): off
        (center): on
    - duration: .20s
      leds:
        (left): on
        (right): on
        (center): on
    - duration: .19s
      leds:
        (left): off
        (right): off
        (center): off
  full_stand_by_your_man:
    - duration: -1
      slides:
        full_stand_by_your_man:
          widgets:
          - type: video
            video: full_stand_by_your_man
            control_events:
              - event: stop_song
                action: stop
          target: stage

  full_bed_of_roses:
    - duration: -1
      slides:
        full_bed_of_roses:
          widgets:
          - type: video
            video: full_bed_of_roses
            control_events:
              - event: stop_song
                action: stop
          target: stage

  full_achy_breaky:
    - duration: -1
      slides:
        full_achy_breaky:
          widgets:
          - type: video
            video: full_achy_breaky
            control_events:
              - event: stop_song
                action: stop
          target: stage

  full_convoy:
    - duration: -1
      slides:
        full_convoy:
          widgets:
          - type: video
            video: full_convoy
            control_events:
              - event: stop_song
                action: stop
          target: stage

  full_every_little_thing:
    - duration: -1
      slides:
        full_every_little_thing:
          widgets:
          - type: video
            video: full_every_little_thing
            control_events:
              - event: stop_song
                action: stop
          target: stage

  full_boots_are_made_for_walkin:
    - duration: -1
      slides:
        full_boots_are_made_for_walkin:
          widgets:
          - type: video
            video: full_boots_are_made_for_walkin
            control_events:
              - event: stop_song
                action: stop
          target: stage

  full_hello_darlin:
    - duration: -1
      slides:
        full_hello_darlin:
          widgets:
          - type: video
            video: full_hello_darlin
            control_events:
              - event: stop_song
                action: stop
          target: stage

  full_louisiana_woman:
    - duration: -1
      slides:
        full_louisiana_woman:
          widgets:
          - type: video
            video: full_louisiana_woman
            control_events:
              - event: stop_song
                action: stop
          target: stage

  full_rhinestone_cowboy:
    - duration: -1
      slides:
        full_rhinestone_cowboy:
          widgets:
          - type: video
            video: full_rhinestone_cowboy
            control_events:
              - event: stop_song
                action: stop
          target: stage

  ma_my_maria:
    - duration: -1
      slides:
        attract_my_maria:
          widgets:
          - type: video
            video: ma_my_maria
            control_events:
              - event: stop_song
                action: stop
          target: stage

  jb_hard_workin_man:
    - duration: -1
      slides:
        attract_hard_workin_man:
          widgets:
          - type: video
            video: jb_hard_workin_man
            control_events:
              - event: stop_song
                action: stop
          target: stage

  mb_beer_thirty:
    - duration: -1
      slides:
        attract_beer_thirty:
          widgets:
          - type: video
            video: ma_beer_thirty
            control_events:
              - event: stop_song
                action: stop
          target: stage

  wt_boot_scoot:
    - duration: -1
      slides:
        attract_boot_scoot:
          widgets:
          - type: video
            video: wt_boot_scoot
            control_events:
              - event: stop_song
                action: stop
          target: stage

  pp_honky_tonk_stomp:
    - duration: -1
      slides:
        attract_honky_start_stomp:
          widgets:
          - type: video
            video: pp_honky_tonk_stomp
            control_events:
              - event: stop_song
                action: stop
          target: stage

  mr_bed:
    - duration: -1
      slides:
        attract_mr_bed:
          widgets:
          - type: video
            video: mr_bed
            control_events:
              - event: stop_song
                action: stop
          target: stage


#slide_player:
#  mode_attract_started:
#    jukebox_hurryup_stage:
#      target: stage
#
#slides:
#  jukebox_hurryup_stage:
#    widgets:
#      - type: image
#        image: jb_hurryup_arrow
#        anchor_x: middle
#        anchor_y: top
#        x: middle
#        y: top
#        animations:
#          show_slide:
#            - property: y
#              value: 0
#              duration: 800ms
#            - property: y
#              value: 289
#              duration: 800ms
#              repeat: true
#      - type: video
#        video: jb_hurry_up_foggy_mountain
#        end_behavior: loop