#config_version=5
#config_version=4 # Left for reference. Did NOT double check

show_player:
  mode_attract_started:
    attract_dmd_loop:
      loops: -1
    attract_stage_loop:
      loops: -1
    gi_on: {}
    center_light_sweep:
      speed: 2
    attract_music_lights:
      loops: -1
      show_tokens:
        left: left
        center: center
        right: right
    flash:
      loops: -1
      show_tokens:
        led: l_start_button
  full_bed_of_roses:
    full_bed_of_roses:
      key: music_video
      loops: 0
  full_achy_breaky:
    full_achy_breaky:
      key: music_video
      loops: 0
  full_convoy:
    full_convoy:
      key: music_video
      loops: 0
  full_every_little_thing:
    full_every_little_thing:
      key: music_video
      loops: 0
  full_boots_are_made_for_walkin:
    full_boots_are_made_for_walkin:
      key: music_video
      loops: 0
  full_hello_darlin:
    full_hello_darlin:
      key: music_video
      loops: 0
  full_louisiana_woman:
    full_louisiana_woman:
      key: music_video
      loops: 0
  full_rhinestone_cowboy:
    full_rhinestone_cowboy:
      loops: 0
      key: music_video
  full_stand_by_your_man:
    full_stand_by_your_man:
      loops: 0
      key: music_video
  ma_my_maria:
    ma_my_maria:
      loops: 0
      key: music_video
  jb_hard_workin_man:
    jb_hard_workin_man:
      loops: 0
      key: music_video
  mb_beer_thirty:
    mb_beer_thirty:
      loops: 0
      key: music_video
  wt_boot_scoot:
    wt_boot_scoot:
      loops: 0
      key: music_video
  pp_honky_tonk_stomp:
    pp_honky_tonk_stomp:
      loops: 0
      key: music_video
  mr_bed:
    mr_bed:
      loops: 0
      key: music_video
  htmb_miss_honky_tonk:
    htmb_miss_honky_tonk:
      loops: 0
      key: music_video
  qmb_put_a_girl_in_it:
    qmb_put_a_girl_in_it:
      loops: 0
      key: music_video
  how_long_gone:
    how_long_gone:
      loops: 0
      key: music_video
  jb_hurry_up_foggy_mountain:
    jb_hurry_up_foggy_mountain:
      loops: 0
      key: music_video
  flipper_cancel:
    music_video: stop
  sw_right_flipper:
    attract_dmd_loop:
      action: advance
  sw_left_flipper:
    attract_dmd_loop:
      action: step_back

#slide_player:
#  game_ended: # move this to match
#    how_long_gone_stage:
#      target: stage
#
#slides:
#  how_long_gone_stage: # move this to match
#    widgets:
#      - type: video
#        video: how_long_gone
#        end_behavior: stop
#        animations:
#          show_slide:
#            - property: opacity
#              value: 1
#              duration: 10s
#            - property: opacity
#              value: 0
#              duration: 2s

  mode_attract_stopped:
    attract_dmd_loop:
      action: stop
    attract_stage_loop:  # todo test if we have to do this?
      action: stop
      target: stage
    attract_music_lights:
      action: stop
    music_video: stop
    

slide_player:
  flipper_cancel:
    last_game_scores:
      priority: 1
      expire: 10s

sound_player:
  mode_attract_started:
    base_bed_loop:
      action: play
      loops: -1
      mode_end_action: stop


timers:
  video_timer:
    start_value: 0
    end_value: 480
    direction: up
    tick_interval: 1s
    start_running: true
    restart_on_complete: true
    control_events:
      - event: flipper_cancel
        action: stop

#random_event_player:
#    timer_video_timer_complete:
#      scope: machine
#      force_all: true
#      events:
#        full_bed_of_roses
#        full_achy_breaky
#        full_convoy
#        full_every_little_thing
#        full_boots_are_made_for_walkin
#        full_hello_darlin
#        full_louisiana_woman
#        full_rhinestone_cowboy
#        full_stand_by_your_man
#        ma_my_maria
#        jb_hard_workin_man
#        mb_beer_thirty
#        wt_boot_scoot
#        pp_honky_tonk_stomp
#        mr_bed
#        htmb_miss_honky_tonk
#        qmb_put_a_girl_in_it
#        how_long_gone
#        jb_hurry_up_foggy_mountain

shows:
  attract_music_lights:
    - duration: .39s
      leds:
        (left): on
        (right): off
        (center): off
    - duration: .39s
      leds:
        (left): off
        (right): on
        (center): off
    - duration: .39s
      leds:
        (left): off
        (right): off
        (center): on
    - duration: .20s
      leds:
        (left): on
        (right): on
        (center): on
    - duration: .19s
      leds:
        (left): off
        (right): off
        (center): off
  jb_hurry_up_foggy_mountain:
    - duration: -1
      slides:
        jb_hurry_up_foggy_mountain:
          widgets:
          - type: video
            video: jb_hurry_up_foggy_mountain
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage
  how_long_gone:
    - duration: -1
      slides:
        how_long_gone:
          widgets:
          - type: video
            video: how_long_gone
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage
  qmb_put_a_girl_in_it:
    - duration: -1
      slides:
        qmb_put_a_girl_in_it:
          widgets:
          - type: video
            video: qmb_put_a_girl_in_it
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage
  htmb_miss_honky_tonk:
    - duration: -1
      slides:
        htmb_miss_honky_tonk:
          widgets:
          - type: video
            video: htmb_miss_honky_tonk
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage
  full_stand_by_your_man:
    - duration: -1
      slides:
        full_stand_by_your_man:
          widgets:
          - type: video
            video: full_stand_by_your_man
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage

  full_bed_of_roses:
    - duration: -1
      slides:
        full_bed_of_roses:
          widgets:
          - type: video
            video: full_bed_of_roses
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage

  full_achy_breaky:
    - duration: -1
      slides:
        full_achy_breaky:
          widgets:
          - type: video
            video: full_achy_breaky
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage

  full_convoy:
    - duration: -1
      slides:
        full_convoy:
          widgets:
          - type: video
            video: full_convoy
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage

  full_every_little_thing:
    - duration: -1
      slides:
        full_every_little_thing:
          widgets:
          - type: video
            video: full_every_little_thing
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage

  full_boots_are_made_for_walkin:
    - duration: -1
      slides:
        full_boots_are_made_for_walkin:
          widgets:
          - type: video
            video: full_boots_are_made_for_walkin
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage

  full_hello_darlin:
    - duration: -1
      slides:
        full_hello_darlin:
          widgets:
          - type: video
            video: full_hello_darlin
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage

  full_louisiana_woman:
    - duration: -1
      slides:
        full_louisiana_woman:
          widgets:
          - type: video
            video: full_louisiana_woman
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage

  full_rhinestone_cowboy:
    - duration: -1
      slides:
        full_rhinestone_cowboy:
          widgets:
          - type: video
            video: full_rhinestone_cowboy
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage

  ma_my_maria:
    - duration: -1
      slides:
        attract_my_maria:
          widgets:
          - type: video
            video: ma_my_maria
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage

  jb_hard_workin_man:
    - duration: -1
      slides:
        attract_hard_workin_man:
          widgets:
          - type: video
            video: jb_hard_workin_man
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage

  mb_beer_thirty:
    - duration: -1
      slides:
        attract_beer_thirty:
          widgets:
          - type: video
            video: ma_beer_thirty
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage

  wt_boot_scoot:
    - duration: -1
      slides:
        attract_boot_scoot:
          widgets:
          - type: video
            video: wt_boot_scoot
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage

  pp_honky_tonk_stomp:
    - duration: -1
      slides:
        attract_honky_start_stomp:
          widgets:
          - type: video
            video: pp_honky_tonk_stomp
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage

  mr_bed:
    - duration: -1
      slides:
        attract_mr_bed:
          widgets:
          - type: video
            video: mr_bed
            volume: 0
            animations:
              show_slide:
                - property: volume
                  value: 1
                  duration: 2s
            control_events:
              - event: flipper_cancel
                action: stop
          target: stage


#slide_player:
#  mode_attract_started:
#    jukebox_hurryup_stage:
#      target: stage
#
#slides:
#  jukebox_hurryup_stage:
#    widgets:
#      - type: image
#        image: jb_hurryup_arrow
#        anchor_x: middle
#        anchor_y: top
#        x: middle
#        y: top
#        animations:
#          show_slide:
#            - property: y
#              value: 0
#              duration: 800ms
#            - property: y
#              value: 289
#              duration: 800ms
#              repeat: true
#      - type: video
#        video: jb_hurry_up_foggy_mountain
#        end_behavior: loop
