#config_version=4

#todo
# Sound pool for kickers, slings, and pops

mode:
  start_events: ball_starting
  priority: 100

event_player:
  mode_base_started:
    jukebox_up
    light_mission_select
  world_tour_fail:
    light_mission_select
  money_bags_fail:
    light_mission_select
  music_awards_fail: #made
    light_mission_select
  jukebox_fail: #made
    light_mission_select
  play_poker_fail:
    light_mission_select
#  mode_jukebox_mode_starting: #made
#    fade_out_base_music
#  mode_world_tour_starting:
#    fade_out_base_music
#  mode_play_poker_starting: #made
#    fade_out_base_music
#  mode_money_bags_starting: #made
#    fade_out_base_music
#  mode_music_awards_starting:
#    fade_out_base_music
#  mode_jukebox_two_ball_starting:
#    fade_out_base_music

config:
  - display

sound_pools:
    beats:
        type: random
        sounds:
          drum1
          drum2
          drum3
          drum5
          drum6
          drum7
          drum8
          drum9
          drum10
          drum11
          drum12
          drum13
          drum14
          drum15
          drum16


sound_player:
  mode_base_started:
    wait_to_plunge:
        action: play
        loops: -1
        events_when_looping: wait_to_plunge_looped
  balldevice_bd_plunger_ball_eject_success:
    plunged:
        action: play
        loops: 0
        #events_when_stopped: start_step_3
    wait_to_plunge:
        action: stop
#  start_step_3:
    base_bed_loop:
        action: play
        loops: -1
  fade_in_base_music:
    base_bed_loop:
        action: play
        fade_in: 500ms
  fade_out_base_music: # all possible base game music is in this section, though only one plays at a time
    plunged:
        action: stop
        fade_out: 500ms
    wait_to_plunge:
        action: stop
        fade_out: 500ms
    base_bed_loop:
        action: stop
        fade_out: 500ms
  timer_sound_timer_complete:
    base_bed_loop:
        action: stop
        fade_out: 500ms
  sw_toggle:
    beats:
        action: play
        loops: 0
  sw_quarter:
    quarter:
        action: play
        loops: 0
#    sw_beat:
#        action: play

#timers:
#    __valid_in__: mode
#    debug: single|bool|False
#    start_value: single|int|0
#    end_value: single|int|None
#    direction: single|str|up
#    max_value: single|ms|None
#    tick_interval: single|ms|1s
#    start_running: single|bool|False
#    control_events: list|subconfig(control_events)|None
#    restart_on_complete: single|bool|False
#    bcp: single|bool|False

timers:
  sound_timer:
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 500ms
    control_events:
      - event: fade_out_base_music
        action: start


logic_blocks:
  counter:
    lb_jukebox_counter:
      count_events: sw_jukebox
      events_when_hit: jukebox_hit #Hook the "count" parameter of this event ?? Can I do that in config?
      starting_count: 0
      count_complete_value: 100
      direction: up
      events_when_complete: jukebox_maxed #Maybe this lights everything for 15 secs. Extra ball, super jets, special, etc...
#  sequence:
#    sound_timing:
#      events:
#        - balldevice_playfield_enter
#        - wait_to_plunge_looped
#      events_when_complete: start_step_2

scoring:
    shot_pops_hit:
        score: 10
        jackpot: 5000
    bd_lower_vuk_ball_enter:
        score: 500
    s_jukeboxOpto_active:
        score: 9999
    shot_left_lane_hit:
        score: 500
    shot_right_lane_hit:
        score: 500
    upper_lanes_default_lit_complete:
        score: 10000
    shot_left_drops_hit:
        score: 500
    shot_right_drops_hit:
        score: 500
    s_spinner_active:
        score: 1000
    shot_right_ramp_full_loop_hit:
        score: 3000
    s_leftorbit_active:
        score: 25000
    shot_standups_hit:
        score: 500
    shot_slings_hit:
        score: 10
    s_topkickingtarget_active:
        score: 10
    s_bottomkickingtarget_active:
        score: 500
        jackpot: 50000
    shot_spinner_to_vuk_hit:
        score: 500
    shot_pops_to_vuk_hit:
        score: 300
    s_leftinlane_active:
        score: 5000
    s_rightinlane_active:
        score: 5000
    s_topkicker_active:
        score: 5000





#  managers_choice:
#    hit_events: balldevice_bd_top_kicker_ball_enter
#    reset_events: managers_choice_done
#    enable_events: None
#    show_tokens:
#      led: l_managers_choice


show_player:
  s_spinner_active:
    flash_once:
      loops: 0
      speed: 1.5
      show_tokens:
        led: l_center_longhorn
      priority: 1000000
      sync_ms: 0
  s_leftpop_active:
    flash_once:
      loops: 0
      show_tokens:
        led: l_left_pop
      priority: 1000000
      sync_ms: 0
  s_bottompop_active:
    flash_once:
      loops: 0
      show_tokens:
        led: l_bottom_pop
      priority: 1000000
      sync_ms: 0
  s_rightpop_active:
    flash_once:
      loops: 0
      show_tokens:
        led: l_right_pop
      priority: 1000000
      sync_ms: 0
  s_rightrampopto_active:
    flash_once:
      loops: 3
      speed: 1
      show_tokens:
        led: l_right_ramp_flasher
      sync_ms: 0
  s_leftrampopto_active:
    flash_once:
      loops: 3
      speed: 1
      show_tokens:
        led: l_left_ramp_flasher
      sync_ms: 0

shots:
  album_rotator:
    hit_events: shot_pops_hit, shot_slings_hit
    profile: album_rotator

  shot_left_lane:
    switch: s_LeftLane
  shot_right_lane:
    switch: s_RightLane
  shot_pops:
    switch: s_leftpop, s_rightpop, s_bottompop
  shot_left_drops:
    switch: s_droptarget1, s_DropTarget2, s_droptarget3
  shot_right_drops: #Broken up so I can block this shot when I need to knock down targets
    switch:  s_droptarget4, s_droptarget5
  shot_standups:
    switch: s_rightbanktop, s_rightbankbottom, s_toprightstandup
  shot_slings:
    switch: s_leftsling, s_rightsling
  shot_pops_to_vuk:
    switch: s_TopRightVUK
    delay_switch:
      s_spinner: 2s # this matches the value in the spinner_to_vuk sequence.
  rotate_album_multipliers:
    switch: s_leftpop, s_rightpop, s_bottompop, s_leftsling, s_rightsling, s_bottomkickingtarget, s_topkickingtarget

#Shot with sequences
  shot_right_ramp_full_loop:
    switch_sequence: s_rightRampOpto, s_LeftRampOpto
    time: 1000ms
  shot_subway_shot:   # Seems like a weird name, but probably should have this one
    switch_sequence: s_SubwayOpto, s_LowerVUKOpto
    time: 500ms
  shot_lower_vuk_from_playfield:
    hit_events: bd_lower_vuk_ball_enter
    delay_switch:
      s_subwayopto: 2s
  shot_spinner_to_vuk:
    switch_sequence: s_spinner, s_TopRightVUK
    time: 2s
  shot_jukebox_loop:
    switch: s_jukeboxopto
    delay_switch:
      s_jukeboxopto: 1s



shot_profiles:
#    album_rotator:
#        states:
#            - name: silver
#              show: silver
#            - name: gold
#              show: gold
#            - name: platinum
#              show: platinum
#            - name: double
#              show: double
#            - name: quintuple
#              show: quintuple
#        loop: yes

    album_rotator:
      show: album_rotator
      states:
        - name: silver
        - name: gold
        - name: platinum
        - name: double
        - name: quintuple
      loop: yes
      player_variable: lit_album

    managers_choice:
        states:
          - name: unlit
            show: off
          - name: lit
            show: flash
          - name: active
            show: on
        loop: no

    stealth:
      states:
        - name: off
          show: off
      advance_on_hit: false

shows:
  album_rotator:
      - leds:
          l_silver: on
          l_quintuple_platinum: off
      - leds:
          l_gold: on
          l_silver: off
      - leds:
          l_single_platinum: on
          l_gold: off
      - leds:
          l_double_platinum: on
          l_single_platinum: off
      - leds:
          l_quintuple_platinum: on
          l_double_platinum: off

  flash_once:
    - time: 0
      leds:
        (led): on
    - time: 50ms
      leds:
        (led): off
  flash_jukebox:
    - duration: 125ms
      leds:
        l_jukebox_left: on-f0
        l_jukebox_right: off-f0
    - duration: 125ms
      leds:
        l_jukebox_left: off-f0
        l_jukebox_right: on-f0

shot_groups:
    upper_lanes:
        shots: shot_left_lane, shot_right_lane
        profile: default
        rotate_left_events: s_leftflipper_active
        rotate_right_events: s_rightflipper_active
        reset_events: upper_lanes_default_lit_complete
        enable_events: ball_started
        disable_events: ball_ending
