#config_version=4
Mode:
  start_events: ball_starting
  priority: 100
  code: base.Base

event_player:
  mode_base_started:
    jukebox_up

Logic_blocks:
  counters:
    lb_jukebox_counter:
      count_events: sw_jukebox
      events_when_hit: jukebox_hit #Hook the "count" parameter of this event ?? Can I do that in config?
      starting_count: 0
      count_complete_value: 100
      direction: up
      events_when_complete: jukebox_maxed #Maybe this lights everything for 15 secs. Extra ball, super jets, special, etc...

scoring:
    shot_pops_hit:
        score:	10
        jackpot: 5000
    switch_s_lowerVUKOpto_active:
        score:	500
    s_jukeboxOpto_active:
        score:	9999
    shot_left_lane_hit:
        score:	500
    shot_right_lane_hit:
        score:	500
    upper_lanes_default_lit_complete:
        score:	10000
    shot_left_drops_hit:
        score:	500
    shot_right_drops_hit:
        score:	500
    s_spinner_active:
        score:	1000
    shot_right_ramp_full_loop_hit:
        score:	3000
    s_leftorbit_active:
        score:	25000
    shot_standups_hit:
        score:	500
    shot_slings_hit:
        score:	10
    s_topkickingtarget_active:
        score:	10
    s_bottomkickingtarget_active:
        score:	500
        jackpot: 50000
    shot_spinner_to_vuk_hit:
        score:	500
    shot_pops_to_vuk_hit:
        score:	300
    s_leftinlane_active:
        score:	5000
    s_rightinlane_active:
        score:	5000
    s_topkicker_active:
        score:	5000