#config_version=4

#todo
# Sound pool for kickers, slings, and pops

mode:
  start_events: ball_starting
  priority: 100
  #code: base.Base

event_player:
  mode_base_started:
    jukebox_up
    light_mission_select
  light_mission_select_started:
    light_mystery
  mode_mission_rotator_started:
    stop_mystery
  mode_jukebox_two_ball_stopped:
    light_mission_select
  mode_metal_rodeo_stopped:
    light_mission_select
  mode_honky_tonk_multiball_stopped:
    light_mission_select
  world_tour_fail:
    light_mission_select
  money_bags_fail:
    light_mission_select
  music_awards_fail: #made
    light_mission_select
  jukebox_fail: #made
    light_mission_select
  play_poker_fail:
    light_mission_select
  hit_jukebox{count==5}:
    start_jukebox_hurryup
  hit_jukebox{count==13}:
    light_hilo
  hit_jukebox{count==23}:
    start_jukebox_hurryup
  hit_jukebox{count==35}:
    light_hilo
  hit_jukebox{count==45}:
    start_jukebox_hurryup
  hit_jukebox{count%4==0}:
    start_light_lock
  ball_ending:
    fade_out_base_music
  drop_target_bank_drop_targets_down:
    reset_drop_targets|1s
  shot_top_kicker_managers_choice_unlit_hit:
    enable_base_top_kicker_hold
  shot_top_kicker_managers_choice_lit_hit:
    start_managers_choice
  player_htmb_balls_locked{current_player.htmb_balls_locked == 3}:
    start_honky_tonk_multiball
    stop_light_lock|1s
  ball_hold_left_vuk_held_ball{mode.mystery_lit.active}:
    start_mystery
  ball_hold_left_vuk_held_ball{mode.hilo_lit.active and not mode.mystery_lit.active}:
    start_hilo
  ball_hold_left_vuk_held_ball{device.achievement_groups.missions["enabled"] and not mode.mystery_lit.active and not mode.hilo_lit.active}:
    start_mission
  ball_hold_left_vuk_held_ball{not mode.mystery_lit.active and not device.achievement_groups.missions["enabled"] and not mode.hilo_lit.active}:
    release_left_vuk_ball

random_event_player:
  mys_choose_award:
    force_all: true
    events:
      mys_spot_quarters
      mys_start_ball_saver
      mys_extra_ball
      mys_10_points
      mys_big_points
      mys_start_multiball
      mys_award_lock
      #mys_weak_flippers

      #mys_hold_album_value #todo need to figure this one out yet

config:
  - display

sound_pools:
    beats:
        type: random
        sounds:
          drum1
          drum2
          drum3
          drum5
          drum6
          drum7
          drum8
          drum9
          drum10
          drum11
          drum12
          drum13
          drum14
          drum15
          drum16

sound_player:
  mode_base_started:
    wait_to_plunge:
        action: play
        loops: -1
        events_when_looping: wait_to_plunge_looped
  start_base_music_bed:
    plunged:
        action: play
        loops: 0
        #events_when_stopped: start_step_3
    wait_to_plunge:
        action: stop
#  start_step_3:
    base_bed_loop:
        action: play
        loops: -1
  fade_in_base_music:
    base_bed_loop:
        action: play
        fade_in: 500ms
  fade_out_base_music: # all possible base game music is in this section, though only one plays at a time
    plunged:
        action: stop
        fade_out: 500ms
    wait_to_plunge:
        action: stop
        fade_out: 500ms
    base_bed_loop:
        action: stop
        fade_out: 500ms
  timer_sound_timer_complete:
    base_bed_loop:
        action: stop
        fade_out: 500ms
  sw_toggle:
    beats:
        action: play
        loops: 0
  drop_target_bank_drop_targets_mixed{down==1}:
    applause_1:
      action: play
      loops: 0
  drop_target_bank_drop_targets_mixed{down==2}:
    applause_2:
      action: play
      loops: 0
  drop_target_bank_drop_targets_mixed{down==3}:
    applause_3:
      action: play
      loops: 0
  drop_target_bank_drop_targets_mixed{down==4}:
    applause_4:
      action: play
      loops: 0
  drop_target_bank_drop_targets_down:
    applause_5:
      action: play
      loops: 0
  s_leftorbit_active:
    left_loop:
      action: play
      loops: 0
  s_rightrampopto:
    fire_whoosh:
      action: play
      loops: 0

timers:
  sound_timer:
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 500ms
    control_events:
      - event: fade_out_base_music
        action: start

logic_blocks:
  counters:
    lb_jukebox_counter:
      count_events: sw_jukebox_hit
      events_when_hit: hit_jukebox #Hook the "count" parameter of this event ?? Can I do that in config?
      starting_count: 0
#      count_complete_value: 100
      direction: up
      # Brian: I think there is no max to this? Just keep counting
#      events_when_complete: jukebox_maxed #Maybe this lights everything for 15 secs. Extra ball, super jets, special, etc...
      disable_events: mission_started, mode_jukebox_hurryup_started, block_jukebox_hits
      enable_events: mode_base_started, end_jukebox_mode, money_bags_done, music_awards_done, play_poker_done, stop_world_tour, jukebox_hurryup_done, unblock_jukebox_hits
    lb_music_gate:
      count_events: s_plungerlane_inactive
      starting_count: 0
      count_complete_value: 1
      events_when_complete: start_base_music_bed
      enable_events: mode_base_started
      disable_events: start_base_music_bed|1s
#   started, mode_jukebox_hurryup_started, block_jukebox_hits


scoring:
    shot_pops_hit:
        score: 110
        jackpot: 5000
    bd_lower_vuk_ball_enter:
        score: 1500
    sw_jukebox:
        score: 19070
    shot_left_lane_hit:
        score: 1560
    shot_right_lane_hit:
        score: 1560
    upper_lanes_default_lit_complete:
        score: 10000
    shot_left_drops_hit:
        score: 1750
    shot_right_drops_hit:
        score: 1750
    s_spinner_active:
        score: 1000
    shot_right_ramp_full_loop_hit:
        score: 150000
    s_leftorbit_active:
        score: 25000
        wizard_score: 25000
#    shot_standups_hit:
#        score: 500
    shot_slings_hit:
        score: 110
    s_topkickingtarget_active:
        score: 1100
    s_bottomkickingtarget_active:
        score: 1500
        jackpot: 50000
    shot_spinner_to_vuk_hit:
        score: 1560
    shot_pops_to_vuk_hit:
        score: 1370
    s_leftinlane_active:
        score: 5320
    s_rightinlane_active:
        score: 5320
    s_topkicker_active:
        score: 5320
    player_quarters{value < 7}:
        mr_shot_score:
          score: 1
          action: set
    player_quarters{value >= 7 and value <= 12}:
        mr_shot_score:
          score: 2
          action: set
    player_quarters{value >= 13 and value <= 24}:
        mr_shot_score:
          score: 3
          action: set
    player_quarters{value >= 25}:
        mr_shot_score:
          score: 5
          action: set

#slides:
#  widgets:
#    - type: camera
#      width: 800
#      height: 480
#
#slide_player:
#  s_spinner_active:
#    camera:
#      target: stage

queue_relay_player:
  balldevice_bd_lower_vuk_ball_eject_attempt:
    post: eject_flash
    wait_for: eject_alert_over
  balldevice_bd_top_right_vuk_ball_eject_attempt:
    post: top_eject_flash
    wait_for: top_eject_alert_over

# When the left VUK is shot from the playfield, there could up to three inserts
# lit and we want to service those one-by-one. So the first thing we have to
# do is hold the ball, which we do here. Modes that may start from this shot
# can post the release_left_vuk_ball event when they want to release the ball.
# They can also post the disable_base_left_vuk_hold if they don't want to
# hold the ball there in their mode, and then post enable_base_left_vuk_hold
# to re-enable it in the base mode when they're done.
ball_holds:
  left_vuk:
    # we only need to hold the ball if the ball enters directly from the pf,
    # not if it gets here via the subway from the jukebox
    enable_events: balldevice_bd_lower_vuk_ball_eject_attempt, mode_base_started, enable_base_left_vuk_hold
    disable_events: s_subwayopto_active, disable_base_left_vuk_hold
    balls_to_hold: 1
    hold_devices: bd_lower_vuk
    release_one_events: release_left_vuk_ball
    console_log: full
  top_kicker:
    enable_events: enable_base_top_kicker_hold
    disable_events: disable_base_top_kicker_hold
    balls_to_hold: 1
    hold_devices: bd_top_kicker
    release_one_events: release_top_kicker_ball
    console_log: full


# ------------------------------------------------------------------------------------
# Save the below until we write a tutorial, but this has been replaced with simpler
# event_player entries since we only want to start one per shot

# Next we use a queue_event_player to watch for the ball being held, and then
# we post the left_vuk_hit queue event. Any of the associated modes for those
# three inserts can service this, and when they're all done, we post
# release_left_vuk_ball which will cause the ball_hold to release the ball.
# This nice thing about this is we don't care how many (or even if any) other
# modes grab this queue event. If they don't, then the release event will be
# posted right away.


#queue_event_player:
#  ball_hold_left_vuk_held_ball:
#    queue_event: left_vuk_hit
#    events_when_finished: release_left_vuk_ball


# End section to save ---------------------------------------------------------------

show_player:
  flipper_cradle:  # play the status show when one flipper is active for 3s
    flipper_status:
      priority: 9900
      loops: -1
  flipper_cradle_release:  # stop the show when the active flipper is released
    flipper_status:
      action: stop
  flipper_cancel.1:
    # When the second flipper is active (which is flipper cancel), pause the show so it
    # stops auto-advancing
    flipper_status:
      action: pause
  flipper_cancel.2:  # and also manually advance the show to the next step (next slide)
    flipper_status:
      action: advance
  eject_flash:
    eject_alert:
      loops: 0
      show_tokens:
        led: l_lower_left_flasher
      priority: 1000000
  top_eject_flash:
    top_eject_alert:
      loops: 0
      show_tokens:
        led: l_right_ramp_flasher
      priority: 1000000
  s_spinner_active:
    flash_once:
      loops: 0
      speed: 1.5
      show_tokens:
        led: l_center_longhorn
      priority: 1000000
      sync_ms: 0
  s_leftpop_active:
    flash_once:
      loops: 0
      show_tokens:
        led: l_left_pop
      priority: 1000000
      sync_ms: 0
  s_bottompop_active:
    flash_once:
      loops: 0
      show_tokens:
        led: l_bottom_pop
      priority: 1000000
      sync_ms: 0
  s_rightpop_active:
    flash_once:
      loops: 0
      show_tokens:
        led: l_right_pop
      priority: 1000000
      sync_ms: 0
  disable_base_left_vuk_hold:
    off:
      key: mute_left_hole_lights
      show_tokens:
        leds: l_hi_lo, l_begin_round, l_mystery
      priority: 1000000
  enable_base_left_vuk_hold:
    mute_left_hole_lights: stop
  disable_base_top_kicker_hold:
    off:
      key: mute_managers_choice_light
      show_tokens:
        leds: l_managers_choice
      priority: 1000000
  enabled_base_top_kicker_hold:
    mute_managers_choice_light: stop
  s_rightrampopto_active:
    flash_once:
      loops: 3
      speed: 1
      show_tokens:
        led: l_right_ramp_flasher
      sync_ms: 0
  s_leftrampopto_active:
    flash_once:
      loops: 3
      speed: 1
      show_tokens:
        led: l_left_ramp_flasher
      sync_ms: 0
  ball_save_main_enabled:
    flash:
      show_tokens:
        leds: l_shoot, l_again
      key: ball_save
  ball_save_main_hurry_up:
    flash:
      show_tokens:
        leds: l_shoot, l_again
      key: ball_save
      speed: 2
  ball_save_main_disabled:
      ball_save: stop
  ball_save_mystery_enabled:
    flash:
      show_tokens:
        leds: l_shoot, l_again
      key: ball_save
  ball_save_mystery_hurry_up:
    flash:
      show_tokens:
        leds: l_shoot, l_again
      key: ball_save
      speed: 2
  ball_save_mystery_disabled:
      ball_save: stop

shots:
  shot_left_lane:
    switch: s_LeftLane
  shot_right_lane:
    switch: s_RightLane
  shot_pops:
    switch: s_leftpop, s_rightpop, s_bottompop
  shot_left_drops:
    switch: s_droptarget1, s_DropTarget2, s_droptarget3
  shot_right_drops: #Broken up so I can block this shot when I need to knock down targets
    switch:  s_droptarget4, s_droptarget5
  shot_slings:
    switch: s_leftsling, s_rightsling
  shot_pops_to_vuk:
    switch: s_TopRightVUK
    delay_switch:
      s_spinner: 2s # this matches the value in the spinner_to_vuk sequence.
  shot_right_ramp_full_loop:
    switch_sequence: s_rightRampOpto, s_LeftRampOpto
    time: 3000ms
  shot_subway_shot:   # Seems like a weird name, but probably should have this one
    switch_sequence: s_SubwayOpto, s_LowerVUKOpto
    time: 500ms
  shot_lower_vuk_from_playfield:
    hit_events: balldevice_bd_lower_vuk_ball_enter
    delay_switch:
      s_subwayopto: 2s
  shot_spinner_to_vuk:
    switch_sequence: s_spinner, s_TopRightVUK
    time: 2s
  shot_jukebox_loop:
    switch: s_jukeboxopto
  shot_top_kicker:
    hit_events: balldevice_bd_top_kicker_ball_enter
    show_tokens:
      leds: l_managers_choice
    profile: managers_choice
    disable_events: mission_started, mode_jukebox_hurryup_started, block_jukebox_hits, light_metal_rodeo
    enable_events: mode_base_started, end_jukebox_mode, money_bags_done, music_awards_done, play_poker_done, stop_world_tour, jukebox_hurryup_done, unblock_jukebox_hits, mode_metal_rodeo_stopping
    reset_events: reset_managers_choice

shot_profiles:
    managers_choice:
        states:
          - name: unlit
            show: off
          - name: lit
            show: flash
          - name: active
            show: on
        loop: no

    stealth:
      states:
        - name: off
          show: off
      advance_on_hit: false

shows:
  flash_once:
    - duration: 200ms
      leds:
        (led): off
  flash_jukebox:
    - duration: 125ms
      leds:
        l_jukebox_left: on-f0
        l_jukebox_right: off-f0
    - duration: 125ms
      leds:
        l_jukebox_left: off-f0
        l_jukebox_right: on-f0
  eject_alert:
    - time: 0
      leds:
        (led): on
    - time: 300ms
      leds:
        (led): off
    - time: 450ms
      leds:
        (led): on
    - time: 750ms
      leds:
        (led): off
    - time: 900ms
      leds:
        (led): on
    - time: 1200ms
      leds:
        (led): off
    - time: 1350ms
      events: eject_alert_over
  top_eject_alert:
    - time: 0
      leds:
        (led): on
    - time: 300ms
      leds:
        (led): off
    - time: 450ms
      leds:
        (led): on
    - time: 750ms
      leds:
        (led): off
    - time: 900ms
      leds:
        (led): on
    - time: 1200ms
      leds:
        (led): off
    - time: 1350ms
      events: top_eject_alert_over
  rainbow:
    - duration: 150ms
      leds:
        (leds): red-f100ms
    - duration: 150ms
      leds:
        (leds): orange-f100ms
    - duration: 150ms
      leds:
        (leds): yellow-f100ms
    - duration: 150ms
      leds:
        (leds): green-f100ms
    - duration: 150ms
      leds:
        (leds): blue-f100ms
    - duration: 150ms
      leds:
        (leds): purple-f100ms

shot_groups:
    upper_lanes:
        shots: shot_left_lane, shot_right_lane
        profile: default
        rotate_left_events: s_leftflipper_active
        rotate_right_events: s_rightflipper_active
        reset_events: upper_lanes_default_lit_complete
        enable_events: ball_started
        disable_events: ball_ending

ball_saves:
  main:
    active_time: 8s
    hurry_up_time: 2s
    grace_period: 1s
    early_ball_save_events: s_rightoutlane_active, s_leftoutlane_active
    timer_start_events: playfield_active
  mystery:
    active_time: 15s
    hurry_up_time: 2s
    grace_period: 1s
    enable_events: start_mys_ball_saver
    early_ball_save_events: s_rightoutlane_active, s_leftoutlane_active
    timer_start_events: balldevice_bd_lower_vuk_ball_eject_success
  vuk_eject:
    active_time: 4s
    enable_events: balldevice_bd_lower_vuk_ejecting_ball
    disable_events: s_leftsling_active, s_rightsling_active

