#config_version=4
Mode:
  start_events: ball_starting
  priority: 100
  code: base.Base

event_player:
  mode_base_started:
    jukebox_up

Logic_blocks:
  counters:
    lb_jukebox_counter:
      count_events: sw_jukebox
      events_when_hit: jukebox_hit #Hook the "count" parameter of this event ?? Can I do that in config?
      starting_count: 0
      count_complete_value: 100
      direction: up
      events_when_complete: jukebox_maxed #Maybe this lights everything for 15 secs. Extra ball, super jets, special, etc...

scoring:
    shot_pops_hit:
        score: 10
        jackpot: 5000
    switch_s_lowerVUKOpto_active:
        score: 500
    s_jukeboxOpto_active:
        score: 9999
    shot_left_lane_hit:
        score: 500
    shot_right_lane_hit:
        score: 500
    upper_lanes_default_lit_complete:
        score: 10000
    shot_left_drops_hit:
        score: 500
    shot_right_drops_hit:
        score: 500
    s_spinner_active:
        score: 1000
    shot_right_ramp_full_loop_hit:
        score: 3000
    s_leftorbit_active:
        score: 25000
    shot_standups_hit:
        score: 500
    shot_slings_hit:
        score: 10
    s_topkickingtarget_active:
        score: 10
    s_bottomkickingtarget_active:
        score: 500
        jackpot: 50000
    shot_spinner_to_vuk_hit:
        score: 500
    shot_pops_to_vuk_hit:
        score: 300
    s_leftinlane_active:
        score: 5000
    s_rightinlane_active:
        score: 5000
    s_topkicker_active:
        score: 5000


#        ::::::::  :::    :::  :::::::: ::::::::::: ::::::::
#      :+:    :+: :+:    :+: :+:    :+:    :+:    :+:    :+:
#     +:+        +:+    +:+ +:+    +:+    +:+    +:+
#    +#++:++#++ +#++:++#++ +#+    +:+    +#+    +#++:++#++
#          +#+ +#+    +#+ +#+    +#+    +#+          +#+
#  #+#    #+# #+#    #+# #+#    #+#    #+#    #+#    #+#
#  ########  ###    ###  ########     ###     ########


shots:
# Shots to group
  shot_left_lane:
    switch: s_LeftLane
  shot_right_lane:
    switch: s_RightLane
  shot_pops:
    switch: s_leftpop, s_rightpop, s_bottompop
  shot_left_drops:
    switch: s_droptarget1, s_DropTarget2, s_droptarget3
  shot_right_drops: #Broken up so I can block this shot when I need to knock down targets
    switch:  s_droptarget4, s_droptarget5
  shot_standups:
    switch: s_rightbanktop, s_rightbankbottom, s_toprightstandup
  shot_slings:
    switch: s_leftsling, s_rightsling
  shot_pops_to_vuk:
    switch: s_TopRightVUK
    delay_switch:
      s_spinner: 2s #this matches the value in the spinner_to_vuk sequence.
  rotate_album_multipliers:
    switch: s_leftpop, s_rightpop, s_bottompop, s_leftsling, s_rightsling, s_bottomkickingtarget, s_topkickingtarget



#Shot with sequences
  shot_right_ramp_full_loop:
    switch_sequence: s_rightRampOpto, s_LeftRampOpto
    time: 1000ms
  shot_subway_shot:   # Seems like a weird name, but probably should have this one
    switch_sequence: s_SubwayOpto, s_LowerVUKOpto
    time: 500ms
  shot_spinner_to_vuk:
    switch_sequence: s_spinner, s_TopRightVUK
    time: 2s

#        ::::::::  :::    :::  :::::::: :::::::::::
#      :+:    :+: :+:    :+: :+:    :+:    :+:
#     +:+        +:+    +:+ +:+    +:+    +:+
#    +#++:++#++ +#++:++#++ +#+    +:+    +#+
#          +#+ +#+    +#+ +#+    +#+    +#+
#  #+#    #+# #+#    #+# #+#    #+#    #+#
#  ########  ###    ###  ########     ###
#        ::::::::  :::::::::   ::::::::  :::    ::: :::::::::   ::::::::
#      :+:    :+: :+:    :+: :+:    :+: :+:    :+: :+:    :+: :+:    :+:
#     +:+        +:+    +:+ +:+    +:+ +:+    +:+ +:+    +:+ +:+
#    :#:        +#++:++#:  +#+    +:+ +#+    +:+ +#++:++#+  +#++:++#++
#   +#+   +#+# +#+    +#+ +#+    +#+ +#+    +#+ +#+               +#+
#  #+#    #+# #+#    #+# #+#    #+# #+#    #+# #+#        #+#    #+#
#  ########  ###    ###  ########   ########  ###         ########


shot_groups:
    upper_lanes:
        shots: shot_left_lane, shot_right_lane
        profile: default
        rotate_left_events: s_leftflipper_active
        rotate_right_events: s_rightflipper_active
        reset_events: upper_lanes_default_lit_complete
        enable_events: ball_started
        disable_events: ball_ending


shot_profiles:
    album_rotator:
        states:
            - name: silver
              show: silver
            - name: gold
              show: gold
            - name: platinum
              show: platinum
            - name: double
              show: double
            - name: quintuple
              show: quintuple
        loop: yes

shows:
    silver:
        - duration: 1
          leds:
            l_silver: white
            l_gold: 00
            l_single_platinum: 00
            l_double_platinum: 00
            l_quintuple_platinum: 00
    gold:
        - duration: 1
          leds:
            l_silver: 00
            l_gold: white
            l_single_platinum: 00
            l_double_platinum: 00
            l_quintuple_platinum: 00
    platinum:
        - duration: 1
          leds:
            l_silver: 00
            l_gold: 00
            l_single_platinum: white
            l_double_platinum: 00
            l_quintuple_platinum: 00
    double:
        - duration: 1
          leds:
            l_silver: 00
            l_gold: 00
            l_single_platinum: 00
            l_double_platinum: white
            l_quintuple_platinum: 00
    quintuple:
        - duration: 1
          leds:
            l_silver: 00
            l_gold: 00
            l_single_platinum: 00
            l_double_platinum: 00
            l_quintuple_platinum: white