#config_version=4

# base mode display-related configs

event_player:
  multiplayer_game: player_1_multiplayer_slide
  player_1_ball_started: player_1_multiplayer_slide
  show_score_slide{game.num_players==1}: single_player_score
  show_score_slide{game.num_players>1 and current_player.number==1}: multi_player_p1_score
  show_score_slide{current_player.number==2}: multi_player_p2_score
  show_score_slide{current_player.number==3}: multi_player_p3_score
  show_score_slide{current_player.number==4}: multi_player_p4_score
  slide_dmd_blank_active: show_score_slide

slide_player:
  single_player_ball_started: single_player_score
  player_1_multiplayer_slide: multi_player_p1_score
  player_2_ball_started: multi_player_p2_score
  player_3_ball_started: multi_player_p3_score
  player_4_ball_started: multi_player_p4_score
  ball_save_vuk_eject_saving_ball:
    phantom_ball_save:
      priority: 1000
      expire: 2s
  mode_base_started:
    base_background:
      target: stage
  ball_save_main_saving_ball:
    ball_saved:
      widgets:
        - type: text
          text: BALL SAVED!
          style: dmd_big
      expire: 2s
      priority: 5000
  player_add_success:
    player_added:
      widgets:
        - type: text
          text: PLAYER (num) ADDED
          style: dmd_huge
      expire: 2s
      priority: 5500

slides:
  base_background:
  - type: image
    image: bnd_background
    anchor_x: center
    anchor_y: middle

  single_player_score:
  - type: text
    text: (player1|score)
    number_grouping: true
    min_digits: 2
    y: middle+2
    style: dmd_huge
  - type: text
    text: BALL (player1|ball)    (machine|credits_string)
    anchor_y: bottom
    style: dmd_small
    y: bottom+1

  multi_player_p1_score:
  - type: text
    text: (player1|score)
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: right
    x: right-60
    y: top-2
    style: dmd_big
  - type: text
    text: (player2|score)
    style: dmd_med
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    x: right-2
    y: top-2
  - type: text
    text: (player3|score)
    style: dmd_med
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-60
    number_grouping: true
    min_digits: 2
  - type: text
    text: (player4|score)
    style: dmd_med
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-2
    number_grouping: true
    min_digits: 2
  - type: text
    text: BALL (player1|ball)    (machine|credits_string)
    anchor_y: bottom
    style: dmd_small
    y: bottom+1

  multi_player_p2_score:
  - type: text
    text: (player1|score)
    style: dmd_med
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: right
    x: right-60
    y: top-2
  - type: text
    text: (player2|score)
    style: dmd_big
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    x: right-2
    y: top-2
  - type: text
    text: (player3|score)
    style: dmd_med
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-60
    number_grouping: true
    min_digits: 2
  - type: text
    text: (player4|score)
    style: dmd_med
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-2
    number_grouping: true
    min_digits: 2
  - type: text
    text: BALL (player2|ball)    (machine|credits_string)
    anchor_y: bottom
    style: dmd_small
    y: bottom+1

  multi_player_p3_score:
  - type: text
    text: (player1|score)
    style: dmd_med
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: right
    x: right-60
    y: top-2
  - type: text
    text: (player2|score)
    style: dmd_med
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    x: right-2
    y: top-2
  - type: text
    text: (player3|score)
    style: dmd_big
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-60
    number_grouping: true
    min_digits: 2
  - type: text
    text: (player4|score)
    style: dmd_med
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-2
    number_grouping: true
    min_digits: 2
  - type: text
    text: BALL (player3|ball)    (machine|credits_string)
    anchor_y: bottom
    style: dmd_small
    y: bottom+1

  multi_player_p4_score:
  - type: text
    text: (player1|score)
    style: dmd_med
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: right
    x: right-60
    y: top-2
  - type: text
    text: (player2|score)
    style: dmd_med
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    x: right-2
    y: top-2
  - type: text
    text: (player3|score)
    style: dmd_med
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-60
    number_grouping: true
    min_digits: 2
  - type: text
    text: (player4|score)
    style: dmd_big
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-2
    number_grouping: true
    min_digits: 2
  - type: text
    text: BALL (player4|ball)    (machine|credits_string)
    anchor_y: bottom
    style: dmd_small
    y: bottom+1

  phantom_ball_save:
    widgets:
      type: text
      text: SIT TIGHT!
      style: dmd_big