#config_version=5

mode:
  priority: 600
  start_events: start_ma_two_ball
  stop_events: multiball_ma_two_ball_ended

#                                                      ,d            
#                                                      88            
#   ,adPPYba,  8b       d8   ,adPPYba,  8b,dPPYba,   MM88MMM         
#  a8P_____88  `8b     d8'  a8P_____88  88P'   `"8a    88            
#  8PP"""""""   `8b   d8'   8PP"""""""  88       88    88            
#  "8b,   ,aa    `8b,d8'    "8b,   ,aa  88       88    88,           
#   `"Ybbd8"'   88 "8"       `"Ybbd8"'  88       88    "Y888         
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

event_player:
  mode_ma_two_ball_started:
    - stop_quarters_mode
    - stop_mission_select
    - show_default_slide|3s
  mode_ma_two_ball_stopping:
    - fade_in_base_music
    - start_quarters_mode
    - enable_base_left_vuk_hold
  s_rightrampopto_active:
    - ma_jackpot
  s_leftorbit_active:
    - ma_jackpot

#                                   88           88  88                       88  88             
#                                   88    ,d     ""  88                       88  88             
#                                   88    88         88                       88  88             
#  88,dPYba,,adPYba,   88       88  88  MM88MMM  88  88,dPPYba,   ,adPPYYba,  88  88  ,adPPYba,  
#  88P'   "88"    "8a  88       88  88    88     88  88P'    "8a  ""     `Y8  88  88  I8[    ""  
#  88      88      88  88       88  88    88     88  88       d8  ,adPPPPP88  88  88   `"Y8ba,   
#  88      88      88  "8a,   ,a88  88    88,    88  88b,   ,a8"  88,    ,88  88  88  aa    ]8I  
#  88      88      88   `"YbbdP'Y8  88    "Y888  88  8Y"Ybbd8"'   `"8bbdP"Y8  88  88  `"YbbdP"'  

multiballs:
  ma_two_ball:
    ball_count: 2
    shoot_again: 5s
    start_events: mode_ma_two_ball_started

#                                               88                   
#    ,d                                         88                   
#    88                                         88                   
#  MM88MMM  8b,dPPYba,  ,adPPYYba,   ,adPPYba,  88   ,d8             
#    88     88P'   "Y8  ""     `Y8  a8"     ""  88 ,a8"              
#    88     88         ,adPPPPP88  8b          8888[                
#    88,    88  88      88,    ,88  "8a,   ,aa  88`"Yba,             
#    "Y888  88  88      `"8bbdP"Y8   `"Ybbd8"'  88   `Y8a 
#               88
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8' 

track_player:
  music_awards_quick_fade_out:
    ma_bass_track:
      action: set_volume
      volume: 0.2
      fade: .5s
    ma_drums_track:
      action: set_volume
      volume: 0.2
      fade: .5s
    ma_vocal_track:
      action: set_volume
      volume: 0.2
      fade: .5s
    ma_other_track:
      action: set_volume
      volume: 0.2
      fade: .5s
  music_awards_quick_fade_in:
    ma_bass_track:
      action: set_volume
      volume: 1.0
      fade: .5s
    ma_drums_track:
      action: set_volume
      volume: 1.0
      fade: .5s
    ma_vocal_track:
      action: set_volume
      volume: 1.0
      fade: .5s
    ma_other_track:
      action: set_volume
      volume: 1.0
      fade: .5s

#             88  88           88                                    
#             88  ""           88                                    
#             88               88                                    
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,                        
#  I8[    ""  88  88  a8"    `Y88  a8P_____88                        
#   `"Y8ba,   88  88  8b       88  8PP"""""""                        
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa                        
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

slide_player:
  mode_ma_two_ball_started:
    ma2b_dmd_intro:
      target: dmd
    music_awards_dmd:
      action: remove
  show_default_slide:
    ma_two_ball_dmd:
      target: dmd
    ma2b_dmd_intro:
      action: remove
  ma_jackpot:
    ma_jackpot_dmd:
      target: dmd
      expire: 1.5s

#                                                88                                   
#                                                88                                   
#                                                88                                   
#  8b,dPPYba,  ,adPPYYba,  8b,dPPYba,    ,adPPYb,88   ,adPPYba,   88,dPYba,,adPYba,   
#  88P'   "Y8  ""     `Y8  88P'   `"8a  a8"    `Y88  a8"     "8a  88P'   "88"    "8a  
#  88          ,adPPPPP88  88       88  8b       88  8b       d8  88      88      88  
#  88          88,    ,88  88       88  "8a,   ,d88  "8a,   ,a8"  88      88      88  
#  88          `"8bbdP"Y8  88       88   `"8bbdP"Y8   `"YbbdP"'   88      88      88  
#                                                      ,d            
#                                                      88            
#   ,adPPYba,  8b       d8   ,adPPYba,  8b,dPPYba,   MM88MMM         
#  a8P_____88  `8b     d8'  a8P_____88  88P'   `"8a    88            
#  8PP"""""""   `8b   d8'   8PP"""""""  88       88    88            
#  "8b,   ,aa    `8b,d8'    "8b,   ,aa  88       88    88,           
#   `"Ybbd8"'   88 "8"       `"Ybbd8"'  88       88    "Y888         
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

random_event_player:
  play_award_video:
    force_all: true
    events:
      - show_ma_award1
      - show_ma_award2
      - show_ma_award3
      - show_ma_award4
      - show_ma_award5
      - show_ma_award6

#                                                             88     
#                                                             88     
#                                                             88     
#  ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,    ,adPPYb,88     
#  I8[    ""  a8"     "8a  88       88  88P'   `"8a  a8"    `Y88     
#   `"Y8ba,   8b       d8  88       88  88       88  8b       88     
#  aa    ]8I  "8a,   ,a8"  "8a,   ,a88  88       88  "8a,   ,d88     
#  `"YbbdP"'   `"YbbdP"'    `"YbbdP'Y8  88       88   `"8bbdP"Y8     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

sound_player:
  ma_jackpot:
    jackpots:
      action: play
      loops: 0
      events_when_played: play_award_video
  mode_ma_two_ball_started:
    ma_ronnie_music_award_multiball:
      action: play
      loops: 0

#             88  88           88                         
#             88  ""           88                         
#             88               88                         
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,  ,adPPYba,  
#  I8[    ""  88  88  a8"    `Y88  a8P_____88  I8[    ""  
#   `"Y8ba,   88  88  8b       88  8PP"""""""   `"Y8ba,   
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa  aa    ]8I  
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'  `"YbbdP"'

slides:
  award_1:
    widgets:
      - type: video
        video: ma_award1
        end_behavior: stop
        anchor_x: left
        x: left
  award_2:
    widgets:
      - type: video
        video: ma_award2
        end_behavior: stop
        anchor_x: left
        x: left
  award_3:
    widgets:
      - type: video
        video: ma_award3
        end_behavior: stop
        anchor_x: left
        x: left
  award_4:
    widgets:
      - type: video
        video: ma_award4
        end_behavior: stop
        anchor_x: left
        x: left
  award_5:
    widgets:
      - type: video
        video: ma_award5
        end_behavior: stop
        anchor_x: left
        x: left
  award_6:
    widgets:
      - type: video
        video: ma_award6
        end_behavior: stop
        anchor_x: left
        x: left
  ma2b_dmd_intro:
    widgets:
      - type: text
        text: "MUSIC AWARDS"
        anchor_y: top
        style: big #dmd_big
        y: top-1
        anchor_x: left
        x: left+22
      - type: text
        text: MULTIBALL
        style: big #dmd_huge
        font_size: 0
        color: red
        y: bottom-3
        x: left+65
        anchor_y: bottom
        animations:
          show_slide:
            - property: font_size
              value: 10
              duration: .1s
            - property: font_size
              value: 40
              duration: .2s
            - property: font_size
              value: 10
              duration: .2s
            - property: font_size
              value: 20
              duration: .1s
            - property: opacity
              value: 1
              duration: .3s
  ma_two_ball_dmd:
    widgets:
      - type: video
        video: ma_grammy_loop_3
        end_behavior: loop
        anchor_x: left
        x: left
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        anchor_x: right
        x: right-1
        y: middle
        style: tall_title
      - type: text
        text: Each hit = 100k
        anchor_y: top
        style: small 
        y: top-1
        anchor_x: right
        x: right-1
  ball_saved:
    widgets:
      - type: text
        text: BALL SAVED!
        expire: 2s
        style: huge #dmd_huge
  ma_jackpot_dmd:
    widgets:
      - type: text
        text: JACKPOT!!!
        style: huge #dmd_huge
        font_size: 0
        color: red
        animations:
          show_slide:
            - property: font_size
              value: 60
              duration: .3s
            - property: font_size
              value: 30
              duration: .1s
            - property: font_size
              value: 60
              duration: .2s
            - property: font_size
              value: 40
              duration: .1s

#             88                                                       
#             88                                                       
#             88                                                       
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   8b      db      d8   
#  I8[    ""  88P'    "8a  a8"     "8a  `8b    d88b    d8'   
#   `"Y8ba,   88       88  8b       d8   `8b  d8'`8b  d8'     
#  aa    ]8I  88       88  "8a,   ,a8"    `8bd8'  `8bd8'     
#  `"YbbdP"'  88       88   `"YbbdP"'       YP      YP     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8' 

show_player:
  ma_jackpot:
    yellow_radar:
      action: play
      loops: 1
      speed: 60
  mode_ma_two_ball_started:
    flash_jukebox:
      action: play
      loops: 0
  show_ma_award1:
    ma_award1:
      action: play
      loops: 0
  show_ma_award2:
    ma_award2:
      action: play
      loops: 0
  show_ma_award3:
    ma_award3:
      action: play
      loops: 0
  show_ma_award4:
    ma_award4:
      action: play
      loops: 0
  show_ma_award5:
    ma_award5:
      action: play
      loops: 0
  show_ma_award6:
    ma_award6:
      action: play
      loops: 0

#             88                                                       
#             88                                                       
#             88                                                       
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   8b      db      d8  ,adPPYba,  
#  I8[    ""  88P'    "8a  a8"     "8a  `8b    d88b    d8'  I8[    ""  
#   `"Y8ba,   88       88  8b       d8   `8b  d8'`8b  d8'    `"Y8ba,   
#  aa    ]8I  88       88  "8a,   ,a8"    `8bd8'  `8bd8'    aa    ]8I  
#  `"YbbdP"'  88       88   `"YbbdP"'       YP      YP      `"YbbdP"' 

shows:
  ma_award1:
    - duration: 200ms
      events:
        - music_awards_quick_fade_out
    - duration: 2600ms
      slides:
        award_1:
          target: stage
          priority: 501
          transition_out: fade
    - duration: 200ms
      events:
        - music_awards_quick_fade_in
  ma_award2:
    - duration: 200ms
      events:
        - music_awards_quick_fade_out
    - duration: 6300ms
      slides:
        award_2:
          target: stage
          priority: 501
          transition_out: fade
    - duration: 200ms
      events:
        - music_awards_quick_fade_in
  ma_award3:
    - duration: 200ms
      events:
        - music_awards_quick_fade_out
    - duration: 4430ms
      slides:
        award_3:
          target: stage
          priority: 501
          transition_out: fade
    - duration: 200ms
      events:
        - music_awards_quick_fade_in
  ma_award4:
    - duration: 200ms
      events:
        - music_awards_quick_fade_out
    - duration: 3570ms
      slides:
        award_4:
          target: stage
          priority: 501
          transition_out: fade
    - duration: 200ms
      events:
        - music_awards_quick_fade_in
  ma_award5:
    - duration: 200ms
      events:
        - music_awards_quick_fade_out
    - duration: 6000ms
      slides:
        award_5:
          target: stage
          priority: 501
          transition_out: fade
    - duration: 200ms
      events:
        - music_awards_quick_fade_in
  ma_award6:
    - duration: 200ms
      events:
        - music_awards_quick_fade_out
    - duration: 4000ms
      slides:
        award_6:
          target: stage
          priority: 501
          transition_out: fade
    - duration: 200ms
      events:
        - music_awards_quick_fade_in

#                                       88              88           88              
#                                       ""              88           88              
#                                                       88           88              
#  8b       d8  ,adPPYYba,  8b,dPPYba,  88  ,adPPYYba,  88,dPPYba,   88   ,adPPYba,  
#  `8b     d8'  ""     `Y8  88P'   "Y8  88  ""     `Y8  88P'    "8a  88  a8P_____88  
#   `8b   d8'   ,adPPPPP88  88          88  ,adPPPPP88  88       d8  88  8PP"""""""  
#    `8b,d8'    88,    ,88  88          88  88,    ,88  88b,   ,a8"  88  "8b,   ,aa  
#      "8"      `"8bbdP"Y8  88          88  `"8bbdP"Y8  8Y"Ybbd8"'   88   `"Ybbd8"'
#               88                                                                   
#               88                                                                   
#               88                                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,                  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8                  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88                          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88                          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88                          
#  88                               d8'                                              
#  88                              d8'

variable_player:
  ma_jackpot:
    score: 100000
