#config_version=4
mode:
  priority: 600
  start_events: start_bnd_two_ball
  stop_events: multiball_bnd_two_ball_ended

multiballs:
  bnd_two_ball:
    ball_count: 2
    shoot_again: 5s
    start_events: mode_bnd_two_ball_started

slide_player:
  mode_bnd_two_ball_started:
    multiball:
      expire: 3s

slides:
  multiball:
    widgets:
      - type: text
        text: MULTIBALL
        expire: 2s
        style: dmd_huge
  ball_saved:
    widgets:
      - type: text
        text: BALL SAVED!
        expire: 2s
        style: dmd_huge