#config_version=4

mode:
  priority: 300
  start_events: light_mystery
  stop_events: stop_managers_choice

event_player:
  shot_lower_vuk_from_playfield_hit:
      start_managers_choice

show_player:
  mode_mystery_lit_started: flash_mystery
  stop_managers_choice:
    flash_mystery:
      action: stop
    on:
      show_tokens:
        led: l_mystery

slide_player:
  mode_mystery_lit_started:
    mystery_lit:
      expire: 2s

sound_player:
  mode_mystery_lit_started:
    mystery_riff:
      action: play
      loops: 0

slides:
  mystery_lit:
    widgets:
      - type: line # part of an apostrophe
        points: 65, 32, 65, 30
        color: white
      - type: line # part of an apostrophe
        points: 66, 32, 66, 28
        color: white
      - type: points # part of an apostrophe
        points: 65, 28
        color: white
        pointsize: .5
      - type: text
        text: S
        style: dmd_big
        anchor_y: top
        y: top-1
        anchor_x: left
        x: 67
      - type: text
        text: MANAGER
        style: dmd_big
        anchor_y: top
        y: top-1
        anchor_x: right
        x: 64
      - type: text
        text: CHOICE
        style: dmd_big
        anchor_y: top
        y: top-1
        anchor_x: left
        x: 79
      - type: text
        text: IS LIT!
        style: dmd_big
        anchor_y: top
        y: center+2
      - type: text
        text: SHOOT LEFT POPPER
        style: dmd_small
        anchor_y: bottom
        y: bottom

shows:
  flash_mystery:
    - duration: 250ms
      leds:
        l_mystery: on
    - duration: 250ms
      leds:
        l_mystery: off


