#config_version=5
#config_version=4 # Left for reference. Did NOT double check

mode:
  priority: 300
  start_events: light_mystery
  stop_events: stop_mystery

queue_relay_player:
  left_vuk_hit:
      post: start_mystery
      wait_for: mode_mystery_lit_stopping

show_player:
  mode_mystery_lit_started: flash_mystery
  stop_managers_choice:
    flash_mystery:
      action: stop
    on:
      show_tokens:
        led: l_mystery

slide_player:
  mode_mystery_lit_started:
    mystery_lit:
      expire: 2s

sound_player:
  mode_mystery_lit_started:
    mystery_riff:
      action: play
      loops: 0

slides:
  mystery_lit:
    widgets:
      - type: text
        text: "MYSTERY IS LIT"
        style: huge 
        anchor_y: top
        y: top-1
        color: lime
        animations:
          show_slide:
            - property: opacity
              value: .2
              duration: .3s
            - property: opacity
              value: 1
              duration: .3s
              repeat: true
      - type: text
        text: SHOOT LEFT HOLE
        style: small 
        color: yellow
        anchor_y: bottom
        y: bottom+2

shows:
  flash_mystery:
    - duration: 250ms
      lights:
        l_mystery: on
    - duration: 250ms
      lights:
        l_mystery: off


