#config_version=4

#todo collect_mystery doesn't currently do anything

mode:
  priority: 300
  start_events: ball_started, light_mystery
  stop_events: stop_mystery

# Watch for the left_vuk_hit queue event which is posted by the queue_event_player
# in the base mode when a ball is shot into the left vuk. This will post the
# collect_mystery event
queue_relay_player:
  left_vuk_hit:
      post: collect_mystery
      wait_for: mode_mystery_lit_stopping

show_player:
  mode_mystery_lit_started: flash_mystery
  collect_mystery:
    flash_mystery:
      action: stop
    on:
      show_tokens:
        led: l_mystery
    collect_mystery_display_show:
      loops: 0

event_player:
  mystery_done:
    stop_mystery

shows:
  flash_mystery:
    - duration: 250ms
      leds:
        l_mystery: on
    - duration: 250ms
      leds:
        l_mystery: off
  collect_mystery_display_show:
    - duration: 2s
      slides:
        collect_mystery_slide_1:
        - type: text
          text: MYSTERY COLLECTED
          style: dmd_med
    - duration: 100ms
      events:
        mystery_done:


