#config_version=5
#config_version=4 # Left for reference. Did NOT double check

mode_settings:
  display_delay_ms: 1500
  hurry_up_delay_ms: 500
  hurry_up_event: flipper_cancel
  bonus_entries:
      - event: quarter_bonus
        # number quarters * album value
        score: current_player.quarters * current_player.album_value
      - event: wizard_bonus
        # 25k per wizard shot * num albums completed
        score: current_player.wizard_score * current_player.num_albums

sound_player:
  bonus_start:
    bonus_bed:
        action: play
        loops: -1
  mode_bonus_stopping:
    bonus_bed:
      action: stop

slide_player:
  bonus_start:
    bonus_start:
    - type: image
      image: bonus_bg_cc
      anchor_x: middle
      anchor_y: top
      x: middle
      y: top
    - type: text
      text: END OF BALL BONUS
      style: big #dmd_big
  quarter_bonus:
    quarter_bonus:
    - type: image
      image: bonus_bg_cc
      anchor_x: middle
      anchor_y: top
      x: middle
      y: top
    - type: text
      text: (quarters) QUARTERS
      y: top-7
      anchor_y: top
      style: big #dmd_big
    - type: text
      y: middle-4
      text: X
      style: small #dmd_small
    - type: text
      text: "(album_name) VALUE: (album_value)"
      y: bottom+1
      anchor_y: bottom
      style: small #dmd_small
      number_grouping: true
  wizard_bonus:
    wizard_bonus:
    - type: image
      image: bonus_bg_cc
      anchor_x: middle
      anchor_y: top
      x: middle
      y: top
    - type: text
      text: (num_albums) ALBUMS
      style: big #dmd_big
      anchor_x: right
      x: 67
    - type: text
      text: 25,000
      style: big #dmd_big
      anchor_x: left
      x: 78
    - type: text
      text: x
      style: medium #dmd_med
      x: 72
  bonus_subtotal:
    bonus_subtotal:
      - type: text
        text: (score)
        style: big #dmd_big
        number_grouping: true
  bonus_multiplier:
    bonus_multiplier:
      - type: text
        text: (multiplier)X
        style: huge #dmd_huge
        font_size: 40
        color: red
  bonus_total:
    bonus_total:
    - type: image
      image: bonus_bg_cc
      anchor_x: middle
      anchor_y: top
      x: middle
      y: top
    - type: text
      text: "TOTAL BONUS"
      style: big #dmd_big
      y: 64%
    - type: text
      text: (score)
      style: big #dmd_big
      number_grouping: true
      color: gold
      y: 24%
      animations:
        pre_show_slide:
        - property: opacity
          value: 0
          duration: 50ms
          easing: in_quint
        - property: opacity
          value: 1
          duration: 50ms
          repeat: true
          easing: in_quint
