#config_version=4

mode_settings:
  display_delay_ms: 4000
  hurry_up_delay_ms: 500
  hurry_up_event: flipper_cancel
  bonus_entries:
      - event: quarter_bonus
        # number quarters * album value
        score: current_player.quarters * current_player.album_value
      - event: wizard_bonus
        # 25k per wizard shot * num albums completed
        score: 25000
        player_score_entry: num_albums

scoring:
  mode_bonus_started:
    quarters: 2
    album_value: 750000
    album_name:
        string: GOLD

sound_player:
  mode_bonus_started:
    bonus_bed:
        action: play
        loops: -1
  mode_bonus_ending:
    bonus_bed:
      action: stop

slide_player:
  bonus_start:
    bonus_start:
    - type: image
      image: bonus_bg
      anchor_x: middle
      anchor_y: top
      x: middle
      y: top
    - type: text
      text: END OF BALL BONUS
      style: dmd_big
#    - type: line
#      points: 1, 1, 1, 32, 128, 32, 128, 1
#      color: green
  quarter_bonus:
    quarter_bonus:
    - type: image
      image: bonus_bg
      anchor_x: middle
      anchor_y: top
      x: middle
      y: top
    - type: text
      text: (quarters) QUARTERS
      y: top-7
      anchor_y: top
      style: dmd_big
    - type: text
      y: middle-4
      text: X
      style: dmd_small
    - type: text
      text: "(album_name) VALUE: (album_value)"
      y: bottom+1
      anchor_y: bottom
      style: dmd_small
      number_grouping: true
  wizard_bonus:
    wizard_bonus:
    - type: image
      image: bonus_bg
      anchor_x: middle
      anchor_y: top
      x: middle
      y: top
    - type: text
      text: (num_albums) ALBUMS x 25,000
      style: dmd_big
  bonus_total:
    bonus_total:
    - type: image
      image: bonus_bg
      anchor_x: middle
      anchor_y: top
      x: middle
      y: top
    - type: text
      text: "TOTAL BONUS"
      style: dmd_big
      y: 64%
    - type: text
      text: (score)
      style: dmd_big
      number_grouping: true
      color: gold
      y: 24%
      animations:
        pre_show_slide:
        - property: opacity
          value: 0
          duration: 50ms
          easing: in_quint
        - property: opacity
          value: 1
          duration: 50ms
          repeat: true
          easing: in_quint