#config_version=5
#config_version=4 # Left for reference. Did NOT double check


#                                            88                                      
#                                            88                                      
#                                            88                                      
#  88,dPYba,,adPYba,    ,adPPYba,    ,adPPYb,88   ,adPPYba,                          
#  88P'   "88"    "8a  a8"     "8a  a8"    `Y88  a8P_____88                          
#  88      88      88  8b       d8  8b       88  8PP"""""""                          
#  88      88      88  "8a,   ,a8"  "8a,   ,d88  "8b,   ,aa                          
#  88      88      88   `"YbbdP"'    `"8bbdP"Y8   `"Ybbd8"'                                                                                                  
#                                           88                                       
#                           ,d       ,d     ""                                       
#                           88       88                                              
#  ,adPPYba,   ,adPPYba,  MM88MMM  MM88MMM  88  8b,dPPYba,    ,adPPYb,d8  ,adPPYba,  
#  I8[    ""  a8P_____88    88       88     88  88P'   `"8a  a8"    `Y88  I8[    ""  
#   `"Y8ba,   8PP"""""""    88       88     88  88       88  8b       88   `"Y8ba,   
#  aa    ]8I  "8b,   ,aa    88,      88,    88  88       88  "8a,   ,d88  aa    ]8I  
#  `"YbbdP"'   `"Ybbd8"'    "Y888    "Y888  88  88       88   `"YbbdP"Y8  `"YbbdP"'  
#                                                             aa,    ,88             
#                                                              "Y8bbdP"  

mode_settings:
  display_delay_ms: 1500
  hurry_up_delay_ms: 500
  hurry_up_event: flipper_cancel
  bonus_entries:
      - event: quarter_bonus
        # number quarters * album value
        score: current_player.quarters * 25000 #
      # - event: album_bonus
      #   score: current_player.quarter_bonus_total * current_player.num_albums
      # - event: wizard_bonus
      #   # 25k per wizard shot * num albums completed
      #   score: current_player.wizard_score * current_player.num_albums

variable_player:
  quarter_bonus:
    quarter_value:
      int: current_player.quarters * 25000
    total_bonus_value:
      int: current_player.quarters * 25000 * current_player.multiplier
      action: set
    
    # These are set every time, but not always used. Base mode custom code uses these to determine what to do.
    temp_multiplier:
      int: current_player.multiplier
      action: set
    temp_album_value:
      int: current_player.album_value
      action: set
    temp_album_name:
      string: (player|album_name)
      action: set
  bonus_total:
    score: current_player.total_bonus_value





#                                                             88     
#                                                             88     
#                                                             88     
#  ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,    ,adPPYb,88     
#  I8[    ""  a8"     "8a  88       88  88P'   `"8a  a8"    `Y88     
#   `"Y8ba,   8b       d8  88       88  88       88  8b       88     
#  aa    ]8I  "8a,   ,a8"  "8a,   ,a88  88       88  "8a,   ,d88     
#  `"YbbdP"'   `"YbbdP"'    `"YbbdP'Y8  88       88   `"8bbdP"Y8     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

sound_player:
  bonus_start:
    bonus_bed:
        action: play
        loops: -1
  mode_bonus_stopping:
    bonus_bed:
      action: stop

#             88  88           88                                    
#             88  ""           88                                    
#             88               88                                    
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,                        
#  I8[    ""  88  88  a8"    `Y88  a8P_____88                        
#   `"Y8ba,   88  88  8b       88  8PP"""""""                        
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa                        
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

slide_player:
  bonus_start:
    bonus_start:
    - type: image
      image: bonus_bg_cc
      anchor_x: middle
      anchor_y: top
      x: middle
      y: top
    - type: text
      text: END OF BALL BONUS
      style: big #dmd_big
  quarter_bonus:
    quarter_bonus:
    - type: image
      image: bonus_bg_cc
      anchor_x: middle
      anchor_y: top
      x: middle
      y: top
    - type: text
      text: (player|quarters) QUARTERS
      y: top-7
      anchor_y: top
      style: big #dmd_big
    - type: text
      y: middle-5
      text: X
      style: small 
    - type: text
      text: "25,000"
      #text: "(player|album_name) VALUE: (player|album_value)"
      y: bottom+2
      anchor_y: bottom
      style: small 
      number_grouping: true





      
  # wizard_bonus:
  #   wizard_bonus:
  #   - type: image
  #     image: bonus_bg_cc
  #     anchor_x: middle
  #     anchor_y: top
  #     x: middle
  #     y: top
  #   - type: text
  #     text: (player|num_albums) ALBUMS
  #     style: big #dmd_big
  #     anchor_x: right
  #     x: 67
  #   - type: text
  #     text: 25,000
  #     style: big #dmd_big
  #     anchor_x: left
  #     x: 78
  #   - type: text
  #     text: x
  #     style: medium 
  #     x: 72
  bonus_subtotal:
    bonus_subtotal:
      - type: text
        text: (player|quarter_value)
        style: big #dmd_big
        number_grouping: true
  bonus_multiplier:
    bonus_multiplier:
      - type: text
        text: (player|multiplier)X
        style: huge
        x: left+20
        anchor_x: left
        font_size: 44
        color: red
      - type: text
        text: ALBUM
        style: huge
        font_size: 21
        y: top+4
        anchor_y: top
        color: red
        x: 82
      - type: text
        text: AWARDS
        style: huge
        font_size: 21
        y: bottom-4
        anchor_y: bottom
        color: red
        x: 82
  bonus_total:
    bonus_total:
    - type: image
      image: bonus_bg_cc
      anchor_x: middle
      anchor_y: top
      x: middle
      y: top
    - type: text
      text: "TOTAL BONUS"
      style: big #dmd_big
      y: 64%
    - type: text
      text: (player|total_bonus_value)
      style: big #dmd_big
      number_grouping: true
      color: gold
      y: 24%
      animations:
        pre_show_slide:
        - property: opacity
          value: 0
          duration: 50ms
          easing: in_quint
        - property: opacity
          value: 1
          duration: 50ms
          repeat: true
          easing: in_quint
