#config_version=5
#config_version=4 # Left for reference. Did NOT double check

mode:
  priority: 600
  start_events: extra_ball_lit
  stop_events: stop_extra_ball_lit_mode

light_player:
  mode_extra_ball_lit_started:
    l_extra_ball: on

event_player:
  shot_pops_to_vuk_hit:
    award_lit_extra_ball
    stop_extra_ball_lit_mode|3.3s

sound_player:
  extra_ball_awarded:
    yeehaw:
      loops: 0
  extra_ball_lit_awarded:
    cowbell_alert2:
      loops: 0

slide_player:
#  extra_ball_awarded:
#    extra_ball:
#      expire: 2s
  extra_ball_lit_awarded:
    extra_ball_lit:
      expire: 3.376s

show_player:
  extra_ball_awarded:
    extra_ball_awarded:
      show_tokens:
        left: left
        center: center
        right: right
        gi: gi

slides:
  extra_ball:
    widgets:
      - type: text
        text: EXTRA BALL
        style: dmd_huge
        color: red
        font_size: 0
        reset_animations_events: pre_show_slide
        animations:
          show_slide:
           - property: font_size
             value: 100
             duration: .3s
           - property: font_size
             value: 35
             duration: .3s
           - property: font_size
             value: 100
             duration: .3s
           - property: font_size
             value: 35
             duration: .3s
           - property: font_size
             value: 100
             duration: .3s
           - property: font_size
             value: 35
             duration: .3s
  extra_ball_lit:
      - type: text
        text: EXTRA BALL IS LIT!
        style: dmd_huge
        color: red
        font_size: 25
        reset_animations_events: pre_show_slide
        animations:
          show_slide:
           - property: opacity
             value: 0
             duration: 211ms
           - property: opacity
             value: 1
             duration: 211ms
             repeat: true

widgets:
  extra_ball_indicator:
      - type: image
        image: down_arrow
        anchor_y: bottom
        y: bottom
        anchor_x: right
        x: right-70
        animations:
          add_to_slide:
            - property: y
              value: 30
              duration: 1s
            - property: y
              value: 0
              duration: 1s
              repeat: true
      - type: text
        text: EXTRA BALL IS LIT!
        style: dmd_huge
        font_size: 100
        anchor_y: top
        y: top

widget_player:
  mode_extra_ball_lit_started:
    extra_ball_indicator:
      target: stage
  shot_pops_to_vuk_hit:
    extra_ball_indicator:
      action: remove

shows:
  extra_ball_awarded:
    - time: 0
      slides:
        extra_ball:
          target: dmd
    - time: 150ms
      leds:
        (right): red-f150ms
        (center): red-f150ms
        (left): red-f150ms
        (gi): red-f150ms
    - time: 300ms
      leds:
        (right): off-f150ms
        (center): off-f150ms
        (left): off-f150ms
        (gi): off-f150ms
    - time: 750ms
      leds:
        (right): red-f150ms
        (center): red-f150ms
        (left): red-f150ms
        (gi): red-f150ms
    - time: 900ms
      leds:
        (right): off-f150ms
        (center): off-f150ms
        (left): off-f150ms
        (gi): off-f150ms
    - time: 1050ms
      leds:
        (right): red-f150ms
        (center): red-f150ms
        (left): red-f150ms
        (gi): red-f150ms
    - time: 1200ms
      duration: 150ms
      leds:
        (right): off-f150ms
        (center): off-f150ms
        (left): off-f150ms
        (gi): off-f150ms
