#config_version=5
#config_version=4 # Left for reference. Did NOT double check

mode:
  priority: 600
  start_events: extra_ball_lit
  stop_events: stop_extra_ball_lit_mode

#  88  88               88                                           
#  88  ""               88             ,d                            
#  88                   88             88                            
#  88  88   ,adPPYb,d8  88,dPPYba,   MM88MMM                         
#  88  88  a8"    `Y88  88P'    "8a    88                            
#  88  88  8b       88  88       88    88                            
#  88  88  "8a,   ,d88  88       88    88,                           
#  88  88   `"YbbdP"Y8  88       88    "Y888                         
#           aa,    ,88                                               
#            "Y8bbdP"                                                
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

light_player:
  mode_extra_ball_lit_started:
    l_extra_ball: on

#                                                      ,d            
#                                                      88            
#   ,adPPYba,  8b       d8   ,adPPYba,  8b,dPPYba,   MM88MMM         
#  a8P_____88  `8b     d8'  a8P_____88  88P'   `"8a    88            
#  8PP"""""""   `8b   d8'   8PP"""""""  88       88    88            
#  "8b,   ,aa    `8b,d8'    "8b,   ,aa  88       88    88,           
#   `"Ybbd8"'   88 "8"       `"Ybbd8"'  88       88    "Y888         
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

event_player:
  shot_pops_to_vuk_hit:
    - award_lit_extra_ball
    - stop_extra_ball_lit_mode|3.3s

#                                                             88     
#                                                             88     
#                                                             88     
#  ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,    ,adPPYb,88     
#  I8[    ""  a8"     "8a  88       88  88P'   `"8a  a8"    `Y88     
#   `"Y8ba,   8b       d8  88       88  88       88  8b       88     
#  aa    ]8I  "8a,   ,a8"  "8a,   ,a88  88       88  "8a,   ,d88     
#  `"YbbdP"'   `"YbbdP"'    `"YbbdP'Y8  88       88   `"8bbdP"Y8     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

sound_player:
  extra_ball_awarded:
    yeehaw:
      loops: 0
  extra_ball_lit_awarded:
    cowbell_alert2:
      loops: 0

#             88  88           88                                    
#             88  ""           88                                    
#             88               88                                    
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,                        
#  I8[    ""  88  88  a8"    `Y88  a8P_____88                        
#   `"Y8ba,   88  88  8b       88  8PP"""""""                        
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa                        
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

slide_player:
  extra_ball_lit_awarded:
    extra_ball_lit:
      expire: 3.376s

#             88                                                     
#             88                                                     
#             88                                                     
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   8b      db      d8           
#  I8[    ""  88P'    "8a  a8"     "8a  `8b    d88b    d8'           
#   `"Y8ba,   8888     88  8b       d8   `8b  d8'`8b  d8'            
#  aa    ]8I  8888     88  "8a,   ,a8"    `8bd8'  `8bd8'             
#  `"YbbdP"'  8888     88   `"YbbdP"'       YP      YP               
#
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8' 

show_player:
  extra_ball_awarded:
    extra_ball_awarded:
      show_tokens:
        left: left
        center: center
        right: right
        gi: gi

#             88  88           88                         
#             88  ""           88                         
#             88               88                         
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,  ,adPPYba,  
#  I8[    ""  88  88  a8"    `Y88  a8P_____88  I8[    ""  
#   `"Y8ba,   88  88  8b       88  8PP"""""""   `"Y8ba,   
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa  aa    ]8I  
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'  `"YbbdP"'

slides:
  extra_ball:
    widgets:
      - type: text
        text: EXTRA BALL
        style: huge 
        color: red
        font_size: 0
        reset_animations_events: pre_show_slide
        animations:
          show_slide:
           - property: font_size
             value: 100
             duration: .3s
           - property: font_size
             value: 35
             duration: .3s
           - property: font_size
             value: 100
             duration: .3s
           - property: font_size
             value: 35
             duration: .3s
           - property: font_size
             value: 100
             duration: .3s
           - property: font_size
             value: 35
             duration: .3s
  extra_ball_lit:
      - type: text
        text: EXTRA BALL IS LIT!
        style: huge 
        color: red
        font_size: 25
        reset_animations_events: pre_show_slide
        animations:
          show_slide:
           - property: opacity
             value: 0
             duration: 211ms
           - property: opacity
             value: 1
             duration: 211ms
             repeat: true

#                      88           88                                               
#                      ""           88                             ,d                
#                                   88                             88                
#  8b      db      d8  88   ,adPPYb,88   ,adPPYb,d8   ,adPPYba,  MM88MMM  ,adPPYba,  
#  `8b    d88b    d8'  88  a8"    `Y88  a8"    `Y88  a8P_____88    88     I8[    ""  
#   `8b  d8'`8b  d8'   88  8b       88  8b       88  8PP"""""""    88      `"Y8ba,   
#    `8bd8'  `8bd8'    88  "8a,   ,d88  "8a,   ,d88  "8b,   ,aa    88,    aa    ]8I  
#      YP      YP      88   `"8bbdP"Y8   `"YbbdP"Y8   `"Ybbd8"'    "Y888  `"YbbdP"'  
#                                        aa,    ,88                                  
#                                         "Y8bbdP"    

widgets:
  extra_ball_indicator:
      - type: image
        image: down_arrow
        anchor_y: bottom
        y: bottom
        anchor_x: right
        x: right-70
        animations:
          add_to_slide:
            - property: y
              value: 30
              duration: 1s
            - property: y
              value: 0
              duration: 1s
              repeat: true
      - type: text
        text: EXTRA BALL IS LIT!
        style: huge 
        font_size: 100
        anchor_y: top
        y: top

#                      88           88                                    
#                      ""           88                             ,d     
#                                   88                             88     
#  8b      db      d8  88   ,adPPYb,88   ,adPPYb,d8   ,adPPYba,  MM88MMM  
#  `8b    d88b    d8'  88  a8"    `Y88  a8"    `Y88  a8P_____88    88     
#   `8b  d8'`8b  d8'   88  8b       88  8b       88  8PP"""""""    88     
#    `8bd8'  `8bd8'    88  "8a,   ,d88  "8a,   ,d88  "8b,   ,aa    88,    
#      YP      YP      88   `"8bbdP"Y8   `"YbbdP"Y8   `"Ybbd8"'    "Y888  
#               88                       aa,    ,88                       
#               88                        "Y8bbdP"                        
#               88                                                        
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,       
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8       
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88               
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88               
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88               
#  88                               d8'                                   
#  88                              d8'

widget_player:
  mode_extra_ball_lit_started:
    extra_ball_indicator:
      target: stage
  shot_pops_to_vuk_hit:
    extra_ball_indicator:
      action: remove

#             88                                                       
#             88                                                       
#             88                                                       
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   8b      db      d8  ,adPPYba,  
#  I8[    ""  88P'    "8a  a8"     "8a  `8b    d88b    d8'  I8[    ""  
#   `"Y8ba,   88       88  8b       d8   `8b  d8'`8b  d8'    `"Y8ba,   
#  aa    ]8I  88       88  "8a,   ,a8"    `8bd8'  `8bd8'    aa    ]8I  
#  `"YbbdP"'  88       88   `"YbbdP"'       YP      YP      `"YbbdP"' 

shows:
  extra_ball_awarded:
    - time: 0
      slides:
        extra_ball:
          target: dmd
    - time: 150ms
      lights:
        (right): red
        (center): red
        (left): red
        (gi): red
    - time: 300ms
      lights:
        (right): off
        (center): off
        (left): off
        (gi): off
    - time: 750ms
      lights:
        (right): red
        (center): red
        (left): red
        (gi): red
    - time: 900ms
      lights:
        (right): off
        (center): off
        (left): off
        (gi): off
    - time: 1050ms
      lights:
        (right): red
        (center): red
        (left): red
        (gi): red
    - time: 1200ms
      duration: 150ms
      lights:
        (right): off
        (center): off
        (left): off
        (gi): off
