#config_version=4

# todo
# We also need a way to reset all of those states when the everything
# has been done.

mode:
  start_events: mode_base_started
  priority: 200

queue_relay_player:
  left_vuk_hit{device.achievement_groups.missions["enabled"]}:
      post: start_mission
      wait_for: mode_hilo_stopping

achievements:
  world_tour:
    show_tokens:
      leds: l_world_tour
    show_when_selected: flash
    show_when_started: flash
    show_when_completed: on
    events_when_started: start_world_tour_mode, mission_started
    events_when_completed: light_mission_select
    events_when_enabled: light_mission_select
    restart_after_stop_possible: true
    complete_events: world_tour_success
    enable_events: world_tour_fail, mode_mission_rotator_started

  money_bags:
    show_tokens:
      leds: l_money_bags
    show_when_selected: flash
    show_when_started: flash
    show_when_completed: on
    events_when_started: start_money_bags_mode, mission_started
    events_when_completed: light_mission_select
    events_when_enabled: light_mission_select
    restart_after_stop_possible: true
    complete_events: money_bags_success
    enable_events: money_bags_fail, mode_mission_rotator_started

  music_awards:
    show_tokens:
      leds: l_music_awards
    show_when_selected: flash
    show_when_started: flash
    show_when_completed: on
    events_when_started: start_music_awards_mode, mission_started
    events_when_completed: light_mission_select
    events_when_enabled: light_mission_select
    restart_after_stop_possible: true
    complete_events: music_awards_success
    enable_events: music_awards_fail, mode_mission_rotator_started

  jukebox:
    show_tokens:
      leds: l_jukebox_insert
    show_when_selected: flash
    show_when_started: flash
    show_when_completed: on
    events_when_started: start_jukebox_mode, mission_started
#    events_when_completed: light_mission_select  # Commented out because we start a multiball
    events_when_enabled: light_mission_select
    restart_after_stop_possible: true
    complete_events: jukebox_success
    enable_events: jukebox_fail, mode_mission_rotator_started

  play_poker:
    show_tokens:
      leds: l_play_poker
    show_when_selected: flash
    show_when_started: flash
    show_when_completed: on
    events_when_started: start_play_poker_mode, mission_started
    events_when_completed: light_mission_select
    events_when_enabled: light_mission_select
    restart_after_stop_possible: true
    complete_events: play_poker_success
    enable_events: play_poker_fail, mode_mission_rotator_started

achievement_groups:
  missions:
    achievements: world_tour, money_bags, music_awards, jukebox, play_poker
    auto_select: true
    enable_events: enable_mission_selection
    select_random_achievement_events: mc_pick_mission
    start_selected_events: start_mission
    events_when_enabled: mission_rotator_ready
    rotate_right_events: sw_toggle
    show_tokens:
      leds:
        l_begin_round
    show_when_enabled: flash
    enable_while_no_achievement_started: false
    events_when_all_completed: light_metal_rodeo
    events_when_no_more_enabled: light_metal_rodeo




