#config_version=4

#todo
# This mode is almost done, but needs to have something in it to know
# when a mission is complete and set the light's state to complete.
# We also need a way to reset all of those states when the everything
# has been done.

# Is this mode where we keep track of incomplete modes that are resumed?
# Need stuff for that, too.

mode:
  start_events: ball_starting
#  stop_events: ball_ending, start_money_bags_mode, start_world_tour_mode, start_music_awards_mode, start_jukebox_mode, start_play_poker_mode
  priority: 200

shots:
    light_mission_select:
      switch: s_rightrampopto
      enable_events: light_mission_select
      disable_events: disable_mission_select, light_mission_select_hit
      profile: light_mission_select
      show_tokens:
        leds: l_ramp_fire
      debug: true

shot_profiles:
    light_mission_select:
        loop: true
        advance_on_hit: false
        states:
            - name: lit
              show: flash

show_player:
  light_mission_select_hit:
    flash_once:
      loops: 3
      speed: 1.5
      show_tokens:
        led: l_right_ramp_flasher

achievements:
  world_tour:
    show_tokens:
      leds: l_world_tour
    show_when_selected: flash
    show_when_started: flash
    show_when_completed: on
    events_when_started: start_world_tour_mode
    restart_after_stop_possible: true
    start_enabled: True
    events_when_completed: rotate_mission_rotator
    complete_events: world_tour_success

  money_bags:
    show_tokens:
      leds: l_money_bags
    show_when_selected: flash
    show_when_started: flash
    show_when_completed: on
    events_when_started: start_money_bags_mode
    restart_after_stop_possible: true
    start_enabled: True
    events_when_completed: rotate_mission_rotator

  music_awards:
    show_tokens:
      leds: l_music_awards
    show_when_selected: flash
    show_when_started: flash
    show_when_completed: on
    events_when_started: start_music_awards_mode
    restart_after_stop_possible: true
    start_enabled: True
    events_when_completed: rotate_mission_rotator

  jukebox:
    show_tokens:
      leds: l_jukebox_insert
    show_when_selected: flash
    show_when_started: flash
    show_when_completed: on
    events_when_started: start_jukebox_mode
    restart_after_stop_possible: true
    start_enabled: True
    events_when_completed: rotate_mission_rotator

  play_poker:
    show_tokens:
      leds: l_play_poker
    show_when_selected: flash
    show_when_started: flash
    show_when_completed: on
    events_when_started: start_play_poker_mode
    restart_after_stop_possible: true
    start_enabled: True
    events_when_completed: rotate_mission_rotator

achievement_groups:
  my_group:
    achievements: world_tour, money_bags, music_awards, jukebox, play_poker
    enable_events: light_mission_select_light_mission_select_lit_hit
    disable_events: ball_ending
    start_selected_events: shot_lower_vuk_from_playfield_hit
    select_random_achievement_events: mode_mission_rotator_started
    events_when_enabled: select_next_mission
    rotate_right_events: sw_toggle, rotate_mission_rotator
    show_tokens:
      leds:
        l_begin_round
    show_when_enabled: flash
