#config_version=4

#todo
# This mode is almost done, but needs to have something in it to know
# when a mission is complete and set the light's state to complete.
# We also need a way to reset all of those states when the everything
# has been done.

# Is this mode where we keep track of incomplete modes that are resumed?
# Need stuff for that, too.

mode:
  start_events: ball_started
#  stop_events: ball_ending, start_money_bags_mode, start_world_tour_mode, start_music_awards_mode, start_jukebox_mode, start_play_poker_mode
  priority: 200

logic_blocks:
  sequences:
    advance_random_mission:
      events: mode_mission_rotator_started
      events_when_complete: advance_random_mission
      reset_on_complete: false
      persist_state: true

random_event_player:
    advance_random_mission:
        - world_tour_advance
        - money_bags_advance
        - music_awards_advance
        - jukebox_mode_advance
        - play_poker_advance

event_player:
    money_bags_mission_rotator_lit_hit: start_money_bags_mode
    world_tour_mission_rotator_lit_hit: start_world_tour_mode
    music_awards_mission_rotator_lit_hit: start_music_awards_mode
    jukebox_mode_mission_rotator_lit_hit: start_jukebox_mode
    play_poker_mission_rotator_lit_hit: start_play_poker_mode

shots:
    light_mission_select:
      switch: s_rightrampopto
      enable_events: mode_mission_rotator_stared, light_mission_select
      disable_events: disable_mission_select, light_mission_select_hit
      profile: light_mission_select
      show_tokens:
        leds: l_ramp_fire
    world_tour:
      label: world_tour
      hit_events: shot_lower_vuk_from_playfield_hit
      advance_events: world_tour_advance
      profile: mission_rotator
      show_tokens:
        leds: l_world_tour
    money_bags:
      label: money_bags
      hit_events: shot_lower_vuk_from_playfield_hit
      advance_events: money_bags_advance
      profile: mission_rotator
      show_tokens:
        leds: l_money_bags
    music_awards:
      label: music_awards
      hit_events: shot_lower_vuk_from_playfield_hit
      advance_events: music_awards_advance
      profile: mission_rotator
      show_tokens:
        leds: l_music_awards
    jukebox_mode:
      label: jukebox
      hit_events: shot_lower_vuk_from_playfield_hit
      advance_events: jukebox_mode_advance
      profile: mission_rotator
      show_tokens:
        leds: l_jukebox_insert
    play_poker:
      label: play_poker
      hit_events: shot_lower_vuk_from_playfield_hit
      advance_events: play_poker_advance
      profile: mission_rotator
      show_tokens:
        leds: l_play_poker

shot_groups:
    missions:
      shots: world_tour, money_bags, music_awards, jukebox_mode, play_poker
      profile: mission_rotator
      enable_events: mode_mission_rotator_started, mission_ended
      disable_events: mission_started
      reset_events: all_missions_completed
      rotate_right_events: sw_toggle, rotate_mission_rotator

shot_profiles:
    mission_rotator:
        loop: true
        state_names_to_rotate: lit, unlit
        advance_on_hit: false
        show_when_disabled: true
        states:
            - name: unlit
              show: "off"
            - name: lit
              show: flash
              speed: 4
            - name: completed
              show: "on"
    light_mission_select:
        loop: true
        advance_on_hit: false
        states:
#            - name: unlit
#              show: "off"
            - name: lit
              show: flash
              speed: 4

show_player:
  light_mission_select_hit:
    flash_once:
      loops: 3
      speed: 1.5
      show_tokens:
        led: l_right_ramp_flasher
