#config_version=5

# Doesn't stop super jackpot show or award based on timer
# Light shows need to be FASTER


#                                            88              
#                                            88              
#                                            88              
#  88,dPYba,,adPYba,    ,adPPYba,    ,adPPYb,88   ,adPPYba,  
#  88P'   "88"    "8a  a8"     "8a  a8"    `Y88  a8P_____88  
#  88      88      88  8b       d8  8b       88  8PP"""""""  
#  88      88      88  "8a,   ,a8"  "8a,   ,d88  "8b,   ,aa  
#  88      88      88   `"YbbdP"'    `"8bbdP"Y8   `"Ybbd8"'

mode:
  priority: 600
  start_events: start_jukebox_two_ball
  stop_events: multiball_jukebox_two_ball_ended

#                                                      ,d            
#                                                      88            
#   ,adPPYba,  8b       d8   ,adPPYba,  8b,dPPYba,   MM88MMM         
#  a8P_____88  `8b     d8'  a8P_____88  88P'   `"8a    88            
#  8PP"""""""   `8b   d8'   8PP"""""""  88       88    88            
#  "8b,   ,aa    `8b,d8'    "8b,   ,aa  88       88    88,           
#   `"Ybbd8"'   88 "8"       `"Ybbd8"'  88       88    "Y888         
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'   

event_player:
  mode_jukebox_two_ball_started:
    - fade_out_base_music
    - stop_quarters_mode
    - block_jukebox_hits
    - start_achievements|2s
    - stop_mission_select
    - enable_jb_single_jackpot
  mode_jukebox_two_ball_stopping:
    - fade_in_base_music
    - start_quarters_mode
    - unblock_jukebox_hits
    - light_mission_select
  jb_single_jackpot_hit:
    - enable_jb_double_jackpot
    - disable_jb_single_jackpot
  jb_double_jackpot_hit:
    - enable_jb_super_jackpot
    - start_jb_super_jackpot_timer
    - disable_jb_double_jackpot
  jb_super_jackpot_hit:
    - enable_jb_single_jackpot
    - disable_jb_super_jackpot
    - stop_jb_super_jackpot_timer
    - reset_jb_super_jackpot_timer|0.1s
  timer_jb_super_jackpot_timer_complete:
    - enable_jb_single_jackpot
    - disable_jb_super_jackpot
    - reset_jb_super_jackpot_timer|0.1s
  multiball_jukebox_two_ball_ending:
    - disable_jb_single_jackpot
    - disable_jb_double_jackpot
    - disable_jb_super_jackpot
    
#             88                                            
#             88                          ,d                
#             88                          88                
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   MM88MMM  ,adPPYba,  
#  I8[    ""  88P'    "8a  a8"     "8a    88     I8[    ""  
#   `"Y8ba,   88       88  8b       d8    88      `"Y8ba,   
#  aa    ]8I  88       88  "8a,   ,a8"    88,    aa    ]8I  
#  `"YbbdP"'  88       88   `"YbbdP"'     "Y888  `"YbbdP"'  

# need sound instructions and slides

shots:
  jb_single_jackpot:
    hit_events: sw_jukebox_hit
    disable_events: disable_jb_single_jackpot
    enable_events: enable_jb_single_jackpot
  jb_double_jackpot:
    hit_events: seq_shot_right_ramp_full_loop_hit
    disable_events: disable_jb_double_jackpot
    enable_events: enable_jb_double_jackpot
  jb_super_jackpot:
    hit_events: shot_pops_to_vuk_hit
    disable_events: disable_jb_super_jackpot
    enable_events: enable_jb_super_jackpot  

#           88                                                         
#    ,d     ""                                                         
#    88                                                                
#  MM88MMM  88  88,dPYba,,adPYba,    ,adPPYba,  8b,dPPYba,  ,adPPYba,  
#    88     88  88P'   "88"    "8a  a8P_____88  88P'   "Y8  I8[    ""  
#    88     88  88      88      88  8PP"""""""  88           `"Y8ba,   
#    88,    88  88      88      88  "8b,   ,aa  88          aa    ]8I  
#    "Y888  88  88      88      88   `"Ybbd8"'  88          `"YbbdP"' 

timers:
  jb_super_jackpot_timer:
    start_value: 6
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: start_jb_super_jackpot_timer
        action: start
      - event: stop_jb_super_jackpot_timer
        action: stop
      - event: reset_jb_super_jackpot_timer
        action: reset

#                                   88           88  88                       88  88             
#                                   88    ,d     ""  88                       88  88             
#                                   88    88         88                       88  88             
#  88,dPYba,,adPYba,   88       88  88  MM88MMM  88  88,dPPYba,   ,adPPYYba,  88  88  ,adPPYba,  
#  88P'   "88"    "8a  88       88  88    88     88  88P'    "8a  ""     `Y8  88  88  I8[    ""  
#  88      88      88  88       88  88    88     88  88       d8  ,adPPPPP88  88  88   `"Y8ba,   
#  88      88      88  "8a,   ,a88  88    88,    88  88b,   ,a8"  88,    ,88  88  88  aa    ]8I  
#  88      88      88   `"YbbdP'Y8  88    "Y888  88  8Y"Ybbd8"'   `"8bbdP"Y8  88  88  `"YbbdP"' 

multiballs:
  jukebox_two_ball:
    ball_count: 2
    shoot_again: 5s
    start_events: mode_jukebox_two_ball_started

#             88  88           88                                    
#             88  ""           88                                    
#             88               88                                    
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,                        
#  I8[    ""  88  88  a8"    `Y88  a8P_____88                        
#   `"Y8ba,   88  88  8b       88  8PP"""""""                        
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa                        
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

slide_player:
  mode_jukebox_two_ball_started:
    jb2b_dmd_intro:
      expire: 3s
      target: dmd
  slide_jb2b_dmd_intro_removed:
    jb2b_dmd_shoot_ramp:
      target: dmd
  double_jackpot_complete:
    jb2b_dmd_shoot_ramp:
      target: dmd
  jackpot_complete:
    jb2b_dmd_shoot_loop:
      target: dmd

#                                                             88     
#                                                             88     
#                                                             88     
#  ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,    ,adPPYb,88     
#  I8[    ""  a8"     "8a  88       88  88P'   `"8a  a8"    `Y88     
#   `"Y8ba,   8b       d8  88       88  88       88  8b       88     
#  aa    ]8I  "8a,   ,a8"  "8a,   ,a88  88       88  "8a,   ,d88     
#  `"YbbdP"'   `"YbbdP"'    `"YbbdP'Y8  88       88   `"8bbdP"Y8     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

sound_player:
  jb_single_jackpot_hit:
    jackpot:
      action: play
      loops: 0
      events_when_played: duck
      events_when_stopped: unduck
  jb_double_jackpot_hit:
    double_jackpot2:
      action: play
      loops: 0
      events_when_played: duck
    woo_baby:
      action: play
      loops: 0
      events_when_stopped: unduck
  jb_super_jackpot_hit:
    super_jackpot:
      action: play
      loops: 0
      events_when_played: duck
      events_when_stopped: unduck


#             88  88           88                         
#             88  ""           88                         
#             88               88                         
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,  ,adPPYba,  
#  I8[    ""  88  88  a8"    `Y88  a8P_____88  I8[    ""  
#   `"Y8ba,   88  88  8b       88  8PP"""""""   `"Y8ba,   
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa  aa    ]8I  
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'  `"YbbdP"'

slides:
  jb2b_dmd_shoot_loop:
    widgets:
      - type: text
        text: (score)
        anchor_y: top
        style: huge #dmd_huge
        number_grouping: true
        y: top-2
        anchor_x: right
        x: right-1
      - type: text
        text: SHOOT JUKEBOX LOOP!
        style: small #dmd_small
        anchor_y: bottom
        y: bottom+1
        anchor_x: right
        x: right-1
      - type: video
        video: jb2b_jukebox
        anchor_x: left
        x: left
        end_behavior: loop
  jb2b_dmd_shoot_ramp:
    widgets:
      - type: text
        text: (score)
        anchor_y: top
        style: huge #dmd_huge
        number_grouping: true
        y: top-2
        anchor_x: right
        x: right-1
      - type: text
        text: SHOOT RIGHT RAMP!
        style: small #dmd_small
        anchor_y: bottom
        y: bottom+1
        anchor_x: right
        x: right-1
      - type: video
        video: jb2b_jukebox
        anchor_x: left
        x: left
        end_behavior: loop
  jb2b_dmd_intro:
    widgets:
      - type: text
        text: MULTIBALL
        style: huge #dmd_huge
        font_size: 0
        color: yellow
        animations:
          show_slide:
            - property: font_size
              value: 60
              duration: .3s
            - property: font_size
              value: 30
              duration: .1s
            - property: font_size
              value: 60
              duration: .2s
            - property: font_size
              value: 40
              duration: .1s
            - property: opacity
              value: 0
              duration: .3s
      - type: rectangle
        width: 128
        height: 32
        color: black
        animations:
          show_slide:
            - property: opacity
              value: 100
              duration: .7s
            - property: opacity
              value: 0
              duration: .3s
      - type: text
        text: "LONGHORN MULTIBALL!"
        anchor_y: top
        style: big #dmd_big
        y: top-1
        anchor_x: right
        x: right-1
      - type: text
        text: "Shoot         to"
        style: small #dmd_small
        anchor_y: bottom
        y: center-5
        anchor_x: right
        x: right-10
      - type: text
        text: JACKPOT
        style: small #dmd_small
        anchor_y: bottom
        y: center-5
        anchor_x: right
        x: right-25
        color: lime
      - type: text
        text: light
        style: small #dmd_small
        anchor_y: bottom
        y: bottom+4
        anchor_x: right
        x: right-74
      - type: text
        text: Double Jackpot
        style: small #dmd_small
        anchor_y: bottom
        y: bottom+4
        anchor_x: right
        x: right-1
        color: red
      - type: image
        image: jb2b_still
        anchor_x: left
        x: left
  ball_saved:
    widgets:
      - type: text
        text: BALL SAVED!
        expire: 2s
        style: huge #dmd_huge

#             88                                                       
#             88                                                       
#             88                                                       
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   8b      db      d8   
#  I8[    ""  88P'    "8a  a8"     "8a  `8b    d88b    d8'   
#   `"Y8ba,   88       88  8b       d8   `8b  d8'`8b  d8'     
#  aa    ]8I  88       88  "8a,   ,a8"    `8bd8'  `8bd8'     
#  `"YbbdP"'  88       88   `"YbbdP"'       YP      YP     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8' 

show_player:
  mode_jukebox_two_ball_started:
    jb_play_bnd_song:
      key: jb_active_video
  enable_jb_single_jackpot:  
    flash_jukebox:
      action: play
  disable_jb_single_jackpot:
    flash_jukebox:
      action: stop
  enable_jb_double_jackpot:
    right_ramp_lights:
      action: play
      speed: 20
  disable_jb_double_jackpot:
    right_ramp_lights:
      action: stop
  enable_jb_super_jackpot:
    pops_to_vuk_lights:
      action: play
      speed: 20
  disable_jb_super_jackpot:
    pops_to_vuk_lights:
      action: stop



#             88                                                       
#             88                                                       
#             88                                                       
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   8b      db      d8  ,adPPYba,  
#  I8[    ""  88P'    "8a  a8"     "8a  `8b    d88b    d8'  I8[    ""  
#   `"Y8ba,   88       88  8b       d8   `8b  d8'`8b  d8'    `"Y8ba,   
#  aa    ]8I  88       88  "8a,   ,a8"    `8bd8'  `8bd8'    aa    ]8I  
#  `"YbbdP"'  88       88   `"YbbdP"'       YP      YP      `"YbbdP"' 

shows:
  jb_play_bnd_song:
    - duration: -1
      slides:
        jb_play_bnd_song:
          widgets:
          - type: video
            video: jb_hard_workin_man
            end_behavior: loop
            control_events:
              - event: stop_song
                action: stop
            animations:
              duck:
                - property: volume
                  value: .4
                  duration: .01s
              unduck:
                - property: volume
                  value: 1
                  duration: .5s
          target: stage

#                                       88              88           88              
#                                       ""              88           88              
#                                                       88           88              
#  8b       d8  ,adPPYYba,  8b,dPPYba,  88  ,adPPYYba,  88,dPPYba,   88   ,adPPYba,  
#  `8b     d8'  ""     `Y8  88P'   "Y8  88  ""     `Y8  88P'    "8a  88  a8P_____88  
#   `8b   d8'   ,adPPPPP88  88          88  ,adPPPPP88  88       d8  88  8PP"""""""  
#    `8b,d8'    88,    ,88  88          88  88,    ,88  88b,   ,a8"  88  "8b,   ,aa  
#      "8"      `"8bbdP"Y8  88          88  `"8bbdP"Y8  8Y"Ybbd8"'   88   `"Ybbd8"'
#               88                                                                   
#               88                                                                   
#               88                                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,                  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8                  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88                          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88                          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88                          
#  88                               d8'                                              
#  88                              d8' 

variable_player:
  jb_single_jackpot_hit:
    score: 100000
  jb_double_jackpot_hit:
    score: 200000
  jb_super_jackpot_hit:
    score: 1000000
