#config_version=5
#config_version=4 # Left for reference. Did NOT double check
mode:
  priority: 600
  start_events: start_jukebox_two_ball
  stop_events: multiball_jukebox_two_ball_ended

event_player:
  mode_jukebox_two_ball_started:
    fade_out_base_music
    stop_quarters_mode
    block_jukebox_hits
    start_achievements|2s
    stop_mission_select
  mode_jukebox_two_ball_stopping:
    fade_in_base_music
    start_quarters_mode
    unblock_jukebox_hits

multiballs:
  jukebox_two_ball:
    ball_count: 2
    shoot_again: 5s
    start_events: mode_jukebox_two_ball_started

slide_player:
  mode_jukebox_two_ball_started:
    jb2b_dmd_intro:
      expire: 3s
      target: dmd
  slide_jb2b_dmd_intro_removed:
    jb2b_dmd_shoot_ramp:
      target: dmd
  double_jackpot_complete:
    jb2b_dmd_shoot_ramp:
      target: dmd
  jackpot_complete:
    jb2b_dmd_shoot_loop:
      target: dmd

sound_player:
  jackpot_complete:
    woo_baby:
      action: play
      loops: 0
      events_when_played: duck
      events_when_stopped: unduck
  double_jackpot_complete:
    woo_baby:
      action: play
      loops: 0
      events_when_played: duck
      events_when_stopped: unduck

slides:
  jb2b_dmd_shoot_loop:
    widgets:
      - type: text
        text: (score)
        anchor_y: top
        style: dmd_huge
        number_grouping: true
        y: top-2
        anchor_x: right
        x: right-1
      - type: text
        text: SHOOT JUKEBOX LOOP!
        style: dmd_small
        anchor_y: bottom
        y: bottom+1
        anchor_x: right
        x: right-1
      - type: video
        video: jb2b_jukebox
        anchor_x: left
        x: left
        end_behavior: loop
  jb2b_dmd_shoot_ramp:
    widgets:
      - type: text
        text: (score)
        anchor_y: top
        style: dmd_huge
        number_grouping: true
        y: top-2
        anchor_x: right
        x: right-1
      - type: text
        text: SHOOT RIGHT RAMP!
        style: dmd_small
        anchor_y: bottom
        y: bottom+1
        anchor_x: right
        x: right-1
      - type: video
        video: jb2b_jukebox
        anchor_x: left
        x: left
        end_behavior: loop
  jb2b_dmd_intro:
    widgets:
      - type: text
        text: MULTIBALL
        style: dmd_huge
        font_size: 0
        color: yellow
        animations:
          show_slide:
            - property: font_size
              value: 60
              duration: .3s
            - property: font_size
              value: 30
              duration: .1s
            - property: font_size
              value: 60
              duration: .2s
            - property: font_size
              value: 40
              duration: .1s
            - property: opacity
              value: 0
              duration: .3s
      - type: rectangle
        width: 128
        height: 32
        color: black
        animations:
          show_slide:
            - property: opacity
              value: 100
              duration: .7s
            - property: opacity
              value: 0
              duration: .3s
      - type: text
        text: "LONGHORN MULTIBALL!"
        anchor_y: top
        style: dmd_big
        y: top-1
        anchor_x: right
        x: right-1
      - type: text
        text: "Shoot         to"
        style: dmd_small
        anchor_y: bottom
        y: center-5
        anchor_x: right
        x: right-10
      - type: text
        text: JACKPOT
        style: dmd_small
        anchor_y: bottom
        y: center-5
        anchor_x: right
        x: right-25
        color: lime
      - type: text
        text: light
        style: dmd_small
        anchor_y: bottom
        y: bottom+4
        anchor_x: right
        x: right-74
      - type: text
        text: Double Jackpot
        style: dmd_small
        anchor_y: bottom
        y: bottom+4
        anchor_x: right
        x: right-1
        color: red
      - type: image
        image: jb2b_still
        anchor_x: left
        x: left

  ball_saved:
    widgets:
      - type: text
        text: BALL SAVED!
        expire: 2s
        style: dmd_huge

show_player:
  mode_jukebox_two_ball_started:
    jb_play_bnd_song:
      key: jb_active_video
    flash_jukebox:
      action: play

shows:
  jb_play_bnd_song:
    - duration: -1
      slides:
        jb_play_bnd_song:
          widgets:
          - type: video
            video: jb_hard_workin_man
            end_behavior: loop
            control_events:
              - event: stop_song
                action: stop
            animations:
              duck:
                - property: volume
                  value: .4
                  duration: .01s
              unduck:
                - property: volume
                  value: 1
                  duration: .5s
          target: stage

achievements:
  jackpot:
    show_when_started: flash
    show_when_completed: off
    show_tokens:
      led: jackpot
    reset_events: s_topkicker_active
#    enable_events: mode_jukebox_two_ball_started
    start_events: start_achievements, double_jackpot_complete
    complete_events: shot_right_ramp_full_loop_hit
    events_when_completed: jackpot_complete
    restart_after_stop_possible: true

  double_jackpot:
    show_when_started: flash
    show_when_completed: off
    show_tokens:
      led: double_jackpot
    reset_events: shot_right_ramp_full_loop_hit
#    enable_events: mode_jukebox_two_ball_started
    start_events: jackpot_complete
    complete_events: s_topkicker_active
    events_when_completed: double_jackpot_complete
    restart_after_stop_possible: true

#scoring: #leaving for reference
variable_player:
  jackpot_complete:
    score: 1000000
  double_jackpot_complete:
    score: 2000000
