#config_version=4

mode:
  priority: 300
  start_events: light_managers_choice, managers_choice_managers_choice_flashing_hit
  stop_events: end_managers_choice

event_player:
  finish_managers_choice:
    release_managers_choice_ball
    end_managers_choice|1s

#ball_locks:  CONFIG SPEC
#    __valid_in__: machine, mode
#    balls_to_lock: single|int|
#    lock_devices: list|machine(ball_devices)|
#    source_playfield: single|machine(ball_devices)|playfield
#    request_new_balls_to_pf: single|bool|True
#    enable_events: dict|str:ms|None
#    disable_events: dict|str:ms|None
#    reset_events: dict|str:ms|machine_reset_phase_3, ball_starting, ball_will_end
#    release_one_events: dict|str:ms|None

ball_locks:
  managers_choice:
    balls_to_lock: 1
    lock_devices: bd_top_kicker
    enable_events: mode_managers_choice_lit_started
    request_new_balls_to_pf: False
    release_one_events: release_managers_choice_ball
    disable_events: release_managers_choice_ball

show_player:
  mode_managers_choice_lit_started: flash_managers_choice
  finish_managers_choice:  # todo why is this needed???
    flash_managers_choice:
      action: stop

shows:
  flash_managers_choice:
    - duration: 250ms
      leds:
        l_managers_choice: on
    - duration: 250ms
      leds:
        l_managers_choice: off
