#config_version=5

config:
  - machine_config.yaml

#                                                                                                            
#   ,adPPYb,d8  ,adPPYYba,  88,dPYba,,adPYba,    ,adPPYba,                                                   
#  a8"    `Y88  ""     `Y8  88P'   "88"    "8a  a8P_____88                                                   
#  8b       88  ,adPPPPP88  88      88      88  8PP"""""""                                                   
#  "8a,   ,d88  88,    ,88  88      88      88  "8b,   ,aa                                                   
#   `"YbbdP"Y8  `"8bbdP"Y8  88      88      88   `"Ybbd8"'                                                   
#  88a,    ,88                                   88                                                          
#  88"Y8bbdP"                                    88                                                          
#  88                                            88                                                          
#  88,dPPYba,   ,adPPYYba,  8b,dPPYba,   ,adPPYb,88  8b      db      d8  ,adPPYYba,  8b,dPPYba,   ,adPPYba,  
#  88P'    "8a  ""     `Y8  88P'   "Y8  a8"    `Y88  `8b    d88b    d8'  ""     `Y8  88P'   "Y8  a8P_____88  
#  88       88  ,adPPPPP88  88          8b       88   `8b  d8'`8b  d8'   ,adPPPPP88  88          8PP"""""""  
#  88       88  88,    ,88  88          "8a,   ,d88    `8bd8'  `8bd8'    88,    ,88  88          "8b,   ,aa  
#  88       88  `"8bbdP"Y8  88           `"8bbdP"Y8      YP      YP      `"8bbdP"Y8  88           `"Ybbd8"'  
#  

hardware:
  platform: fast
  driverboards: fast
  rgb_dmd: smartmatrix

fast:
  #ports: /dev/tty.usbserial-141C, /dev/tty.usbserial-141B #, /dev/tty.usbserial-141A
  ports: com12, com13
  # Brian, comment out for Gabe
  #  ports: /dev/tty.usbserial-1415C, /dev/tty.usbserial-1415B #, /dev/tty.usbserial-1415A
  config_number_format: int
  rgb_buffer: 10
  hardware_led_fade_time: 65ms

smartmatrix:
    baud: 3400000
    #port: /dev/tty.usbmodem1030681
    port: com3

# led_settings:
#   default_led_fade_ms: 100

window:
  width: 800
  height: 480
  title: Mission Pinball Framework - Brooks & Dunn
  resizable: false
  fullscreen: false
  borderless: false
  exit_on_escape: true
  source_display: stage

displays:
  stage:
    height: 480
    width: 800
  dmd:
    width: 128
    height: 32
    default: true

rgb_dmds:
  smartmatrix:
    brightness: .5
    fps: 25
    gamma: 2.2