#config_version=4

hardware:
  platform: fast
  driverboards: fast
  rgb_dmd: smartmatrix

fast:
  #ports: /dev/tty.usbserial-141C, /dev/tty.usbserial-141B #, /dev/tty.usbserial-141A
  ports: com12, com13
  # Brian, comment out for Gabe
  #  ports: /dev/tty.usbserial-1415C, /dev/tty.usbserial-1415B #, /dev/tty.usbserial-1415A
  config_number_format: int
  rgb_buffer: 10
  hardware_led_fade_time: 65ms

smartmatrix:
    baud: 3400000
    #port: /dev/tty.usbmodem1030681
    port: com3

#led_settings:
#    default_led_fade_ms: 100

config:
  - machine_config

window:
  width: 800
  height: 480
  title: Mission Pinball Framework - Brooks & Dunn
  resizable: false
  fullscreen: false
  borderless: false
  exit_on_escape: true
  source_display: stage

displays:
  stage:
    height: 480
    width: 800
  dmd:
    width: 128
    height: 32
    default: true

physical_rgb_dmds:
  smartmatrix:
    brightness: .1
    fps: 25
