#config_version=5
#config_version=4 # Left for reference. Did NOT double check
mode:
  start_events: start_hilo
  stop_events: stop_hilo
  priority: 1000
  code: hilo.HiLo

#                      88           88                                               
#                      ""           88                             ,d                
#                                   88                             88                
#  8b      db      d8  88   ,adPPYb,88   ,adPPYb,d8   ,adPPYba,  MM88MMM  ,adPPYba,  
#  `8b    d88b    d8'  88  a8"    `Y88  a8"    `Y88  a8P_____88    88     I8[    ""  
#   `8b  d8'`8b  d8'   88  8b       88  8b       88  8PP"""""""    88      `"Y8ba,   
#    `8bd8'  `8bd8'    88  "8a,   ,d88  "8a,   ,d88  "8b,   ,aa    88,    aa    ]8I  
#      YP      YP      88   `"8bbdP"Y8   `"YbbdP"Y8   `"Ybbd8"'    "Y888  `"YbbdP"'  
#                                        aa,    ,88                                  
#                                         "Y8bbdP"   

widgets:
  hilo_players_card:
      - type: image
        image:
        x: 34
  hilo_dealer_card:
      - type: image
        image:
        x: 100

#                                                      ,d            
#                                                      88            
#   ,adPPYba,  8b       d8   ,adPPYba,  8b,dPPYba,   MM88MMM         
#  a8P_____88  `8b     d8'  a8P_____88  88P'   `"8a    88            
#  8PP"""""""   `8b   d8'   8PP"""""""  88       88    88            
#  "8b,   ,aa    `8b,d8'    "8b,   ,aa  88       88    88,           
#   `"Ybbd8"'   88 "8"       `"Ybbd8"'  88       88    "Y888         
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

event_player:
  mode_hilo_stopping: 
    - fade_in_base_music
    - release_left_vuk_ball
    - disable_base_left_vuk_hold
  hilo_done:
    - stop_hilo|2s


timers:
  time_out:
    start_value: 10
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_hilo_started
      - action: restart
        event: reset_timer
    

sound_pools:
  hilo_gamble_or_cash_out_pool:
    type: random_force_all
    track: voice
    sounds:
      - hilo_gamble_or_cash_out1 # Whatcha Thinkin?
      - hilo_gamble_or_cash_out2 # What's it gonna be?
      - hilo_gamble_or_cash_out3 # Feelin' Lucky?

  hilo_higher_lower_pool:
    type: random_force_all
    track: voice
    sounds:
      - hilo_higher_lower1 # Higher or lower
      - hilo_higher_lower2 # You goin high or low?
      - hilo_higher_lower3 # Up or down?

  hilo_win_pool:
    type: random_force_all
    track: voice
    sounds:
      - hilo_win1 # Got me that time
      - hilo_win2 # Hey look at you
      - hilo_win3 # Are you gonna let me win once in a while?
      - hilo_win4 # Damn, you win.
  
  hilo_lose_pool:
    type: random_force_all
    track: voice
    sounds:
      - hilo_lose1 # Uh huh. I win this round
      - hilo_lose2 # Better luck next time
      - hilo_lose3 # Gotcha that time
      - hilo_lose4 # You can come back another time (unless you know what's good for ya)

  hilo_higher_pool:
    type: random_force_all
    track: voice
    sounds:
      - hilo_higher1 # Let's see higher
      - hilo_higher2 # Ok higher it is buddy
      - hilo_higher3 # You want higher? Done.

  hilo_lower_pool:
    type: random_force_all
    track: voice
    sounds:
      - hilo_lower1 # Let's see lower
      - hilo_lower2 # Come on lower
      - hilo_lower3 # You want lower? Ok I guess.

  hilo_gamble_pool:
    type: random_force_all
    track: voice
    sounds:
      - hilo_gamble1 # Hey I like you're style
      - hilo_gamble2 # Let's do this
      - hilo_gamble3 # I hope you know what you're doin

  hilo_cash_out_pool:
    type: random_force_all
    track: voice
    sounds:
      - hilo_cash_out1 # Callin it a day, huh?
      - hilo_cash_out2 # See you again soon!
      - hilo_cash_out3 # That's all for now

  


#                                                             88     
#                                                             88     
#                                                             88     
#  ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,    ,adPPYb,88     
#  I8[    ""  a8"     "8a  88       88  88P'   `"8a  a8"    `Y88     
#   `"Y8ba,   8b       d8  88       88  88       88  8b       88     
#  aa    ]8I  "8a,   ,a8"  "8a,   ,a88  88       88  "8a,   ,d88     
#  `"YbbdP"'   `"YbbdP"'    `"YbbdP'Y8  88       88   `"8bbdP"Y8     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

sound_player:
  mode_hilo_started:
    poker_loop:
      action: play
      loops: -1
      mode_end_action: stop
  
  slide_hilo_intro_active:
    hilo_you_ready:
      action: play

  play_hilo_higher_lower_sound:
    hilo_higher_lower_pool:
      action: play

  hilo_show_card:
    hilo_gamble_or_cash_out_pool:
      action: play

  play_hilo_cash_out_sound:
    hilo_cash_out_pool:
      action: play

  play_hilo_guess_lower_sound:
    hilo_lower_pool:
      action: play
    
  play_hilo_gamble_sound:
    hilo_gamble_pool:
      action: play
  
  play_hilo_guess_higher_sound:
    hilo_higher_pool:
      action: play

  play_hilo_win_sound:
    hilo_win_pool:
      action: play

  play_hilo_lose_sound:
    hilo_lose_pool:
      action: play

  

#                      88           88                                    
#                      ""           88                             ,d     
#                                   88                             88     
#  8b      db      d8  88   ,adPPYb,88   ,adPPYb,d8   ,adPPYba,  MM88MMM  
#  `8b    d88b    d8'  88  a8"    `Y88  a8"    `Y88  a8P_____88    88     
#   `8b  d8'`8b  d8'   88  8b       88  8b       88  8PP"""""""    88     
#    `8bd8'  `8bd8'    88  "8a,   ,d88  "8a,   ,d88  "8b,   ,aa    88,    
#      YP      YP      88   `"8bbdP"Y8   `"YbbdP"Y8   `"Ybbd8"'    "Y888  
#               88                       aa,    ,88                       
#               88                        "Y8bbdP"                        
#               88                                                        
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,       
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8       
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88               
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88               
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88               
#  88                               d8'                                   
#  88                              d8'

widget_player:
  show_player_card: hilo_players_card
  show_dealer_card: hilo_dealer_card
  hilo_clear_cards:
    hilo_players_card:
      action: remove
    hilo_dealer_card:
      action: remove

#             88  88           88                                    
#             88  ""           88                                    
#             88               88                                    
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,                        
#  I8[    ""  88  88  a8"    `Y88  a8P_____88                        
#   `"Y8ba,   88  88  8b       88  8PP"""""""                        
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa                        
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

slide_player:
  hilo_intro: hilo_intro
  hilo_show_card: hilo_show_card
  hilo_show_gamble_slide: hilo_gamble
  hilo_show_next_card: hilo_show_next_card
  hilo_cash_out: hilo_cash_out
  hilo_win: hilo_win
  hilo_lose: hilo_lose
  hilo_game_win: hilo_game_win
  hilo_total: hilo_total

#             88  88           88                         
#             88  ""           88                         
#             88               88                         
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,  ,adPPYba,  
#  I8[    ""  88  88  a8"    `Y88  a8P_____88  I8[    ""  
#   `"Y8ba,   88  88  8b       88  8PP"""""""   `"Y8ba,   
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa  aa    ]8I  
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'  `"YbbdP"'

slides:
  hilo_intro:
    widgets:
      - type: text
        text: LET'S PLAY SOME HI/LO!
        color: red
        style: medium 
        y: 25
      - type: text
        text: WILL THE NEXT CARD
        style: small 
        y: 13
      - type: text
        text: BE HIGHER OR LOWER?
        style: small 
        y: 5
      - type: line
        points: 1, 1, 1, 32, 128, 32, 128, 1, 1, 1
        color: violet

  hilo_show_card:
    widgets:
      - type: text
        text: "YOUR"
        style: small 
        anchor_x: left
        x: left+1
        y: 22
      - type: text
        text: "CARD"
        style: small 
        anchor_x: left
        x: left+1
        y: 15
      - type: text
        text: "LEFT FLIPPER:"
        anchor_x: left
        x: 49
        y: 29
        style: small 
        color: lime
        animations:
          show_slide:
          - property: opacity
            value: 0.5
            duration: 500ms
          - property: opacity
            value: 1
            duration: 500ms
            repeat: true
          hilo_gamble:
          - property: opacity
            value: 0
        reset_animations_events: pre_show_slide, hilo_gamble
      - type: text
        text: CASH OUT (cash_out)
        style: small 
        anchor_x: left
        x: 49
        y: 23
        color: lime
        animations:
          show_slide:
          - property: opacity
            value: 0.5
            duration: 500ms
          - property: opacity
            value: 1
            duration: 500ms
            repeat: true
          hilo_gamble:
          - property: opacity
            value: 0
        reset_animations_events: pre_show_slide
      - type: text
        text: "RIGHT FLIPPER:"
        anchor_x: right
        x: right
        y: 10
        style: small 
        color: yellow
        opacity: 0
        animations:
          show_slide:
          - property: opacity
            value: 1
            duration: 500ms
          - property: opacity
            value: 0.5
            duration: 500ms
            repeat: true
          hilo_gamble:
          - property: opacity
            value: 0
        reset_animations_events: pre_show_slide, hilo_gamble
      - type: text
        text: GAMBLE FOR (next_bet)
        style: small 
        anchor_x: right
        x: right
        y: 3
        color: yellow
        opacity: 0
        animations:
          hilo_gamble:
          - property: opacity
            value: 0
            duration: 50ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 50ms
            repeat: true
            easing: in_quint
          show_slide:
          - property: opacity
            value: 1
            duration: 500ms
          - property: opacity
            value: 0.5
            duration: 500ms
            repeat: true
        reset_animations_events: pre_show_slide, hilo_gamble

  hilo_gamble:
    widgets:
      - type: text
        text: "YOUR"
        style: small 
        anchor_x: left
        x: left+1
        y: 22
      - type: text
        text: "CARD"
        style: small 
        anchor_x: left
        x: left+1
        y: 15
      - type: text
        text: "LEFT FLIPPER:"
        anchor_x: left
        x: 49
        y: 29
        style: small 
        color: lime
        animations:
          show_slide:
          - property: opacity
            value: 0.5
            duration: 500ms
          - property: opacity
            value: 1
            duration: 500ms
            repeat: true
          hilo_guess_higher:
          - property: opacity
            value: 0
          hilo_guess_lower:
          - property: opacity
            value: 0
        reset_animations_events: pre_show_slide, hilo_guess_higher
      - type: text
        text: NEXT CARD LOWER
        style: small 
        anchor_x: left
        x: 49
        y: 23
        color: lime
        animations:
          hilo_guess_lower:
          - property: opacity
            value: 0
            duration: 50ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 50ms
            repeat: true
            easing: in_quint
          show_slide:
          - property: opacity
            value: 0.5
            duration: 500ms
          - property: opacity
            value: 1
            duration: 500ms
            repeat: true
          hilo_guess_higher:
          - property: opacity
            value: 0
        reset_animations_events: pre_show_slide, hilo_guess_higher
      - type: text
        text: "RIGHT FLIPPER:"
        anchor_x: right
        x: right
        y: 10
        style: small 
        color: yellow
        opacity: 0
        animations:
          show_slide:
          - property: opacity
            value: 1
            duration: 500ms
          - property: opacity
            value: 0.5
            duration: 500ms
            repeat: true
          hilo_guess_lower:
          - property: opacity
            value: 0
          hilo_guess_higher:
          - property: opacity
            value: 0
        reset_animations_events: pre_show_slide, hilo_guess_lower
      - type: text
        text: NEXT CARD HIGHER
        style: small 
        anchor_x: right
        x: right
        y: 3
        color: yellow
        opacity: 0
        animations:
          hilo_guess_higher:
          - property: opacity
            value: 0
            duration: 50ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 50ms
            repeat: true
            easing: in_quint
          hilo_guess_lower:
          - property: opacity
            value: 0
          show_slide:
          - property: opacity
            value: 1
            duration: 500ms
          - property: opacity
            value: 0.5
            duration: 500ms
            repeat: true
        reset_animations_events: pre_show_slide, hilo_guess_lower

  hilo_show_next_card:
    widgets:
      - type: text
        text: "YOUR"
        style: small 
        anchor_x: left
        x: left+1
        y: 22
      - type: text
        text: "CARD"
        style: small 
        anchor_x: left
        x: left+1
        y: 15
      - type: text
        text: "DEALER'S"
        style: small 
        anchor_x: left
        x: 50
        y: 22
      - type: text
        text: "CARD"
        style: small 
        anchor_x: left
        x: 50
        y: 15

  hilo_cash_out:
    widgets:
      - type: text
        text: CASH OUT!
        style: big #dmd_big
        y: 20
        color: yellow
      - type: text
        text: "WINNINGS: (points)"
        style: medium 
        y: 10
        color: lime
        number_grouping: true

  hilo_win:
    widgets:
      - type: text
        text: WINNER!
        style: big #dmd_big
        y: 20
        color: yellow
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 50ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 50ms
            repeat: true
            easing: in_quint
      - type: text
        text: NEXT BET WORTH (points)
        style: medium 
        y: 10
        color: lime
        number_grouping: true

  hilo_lose:
    widgets:
      - type: text
        text: YOU LOST IT ALL
        style: big #dmd_big
        y: 20
        color: red
      - type: text
        text: YOU GET NOTHING
        style: medium 
        y: 10

  hilo_game_win:
    widgets:
      - type: text
        text: BIG WINNER!
        style: big #dmd_big
        y: 17
        color: yellow
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 50ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 50ms
            repeat: true
            easing: in_quint

  hilo_total:
    widgets:
      - type: text
        text: HI/LO GAME TOTAL
        style: medium 
        y: 28
        color: red
      - type: text
        text: (score)
        style: huge 
        y: 13
        color: yellow
        number_grouping: true
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 50ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 50ms
            repeat: true
            easing: in_quint
