#config_version=5
#config_version=4 # Left for reference. Did NOT double check

mode:
  priority: 500
  start_events: start_money_bags_mode
  stop_events: money_bags_done

#todo
# intro dots
# mode timer
# money bag animation
# stage video?

event_player:
  mode_money_bags_started:
    mode_running|5s
    fade_out_base_music
#  logicblock_stop_adding_time_complete:
  logicblock_money_bags_counter_complete:  # brian added
    money_bags_done|5s
    money_bags_fade_out|3s
    money_bags_success|4s   # is there a fail mode todo
  timer_money_bags_timer_complete:
    money_bags_fail
    money_bags_done|1
  mode_money_bags_stopping:
    fade_in_base_music
    enable_base_left_vuk_hold
  ball_will_end:
    money_bags_fail
  timer_mb_intro_timer_complete:
    release_left_vuk_ball
    disable_base_left_vuk_hold
    release_top_kicker_ball
    disable_base_top_kicker_hold

shots:
    left_kicking_target:
        switch: s_bottomkickingtarget
        show_tokens:
            light: l_left_longhorn
        advance_events: mode_money_bags_started
        disable_events: timer_money_bags_timer_complete

sequence_shots:
    spinner_to_vuk:
        switch_sequence: s_spinner, s_toprightvuk
        # Commented this out since it won't pass config validation. Need to replicate it though.
        # Why aren't show_tokens in sequence_shots?
        # show_tokens:  
        #     light: l_center_longhorn
        cancel_events: timer_money_bags_timer_complete

shot_groups:
    money_bags:
        shots: left_kicking_target, spinner_to_vuk
        # profile: advertise # Why is this gone? Where did the feature go?
        disable_events: timer_money_bags_timer_complete
        rotate_events: money_bags_advertise_flashing_hit

timers:
    mb_intro_timer:
        start_value: 3
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: mode_money_bags_started
    money_bags_timer:
        start_value: 30
        end_value: 0
        direction: down
        tick_interval: 1.25s
        control_events:
            - action: start
              event: timer_mb_intro_timer_complete
            - action: reset
              event: money_bags_advertise_flashing_hit
            - action: stop
              event: logicblock_money_bags_counter_complete

#logic_blocks:
counters:
    money_bags_counter:
        enable_events: mode_money_bags_started
        disable_events: mode_money_bags_ended
        count_events: money_bags_advertise_flashing_hit
        persist_state: true
        player_variable: money_bags_hit
        count_complete_value: 5
        starting_count: 0
        direction: up

slide_player:
  mode_money_bags_starting:
    mb_intro_dmd:
      target: dmd
    money_bags_stage:
      target: stage
  mode_running:
    money_bags_dmd:
      target: dmd
  logicblock_money_bags_counter_complete:
    money_bags_complete:
      target: dmd

slides:
  mb_intro_dmd:
    widgets:
      - type: text
        text: Shooting lit shots
        anchor_y: top
        style: dmd_small
        y: top-1
        anchor_x: right
        x: right-1
      - type: text
        text: collects and increases
        style: dmd_small
        anchor_y: bottom
        y: center
        anchor_x: right
        x: right-1
      - type: text
        text: Money Bags Value
        style: dmd_big
        anchor_y: bottom
        y: bottom+1
        anchor_x: right
        x: right-1
      - type: rectangle
        color: 000000
        height: 32
        width: 128
        opacity: .2
      - type: video
        video: mb_dmd_loop_2
        end_behavior: loop
        anchor_x: left
        x: left
    target: dmd
  money_bags_stage:
    widgets:
      - type: video
        video: mb_beer_thirty
        end_behavior: loop
        animations:
          money_bags_fade_out:
            - property: volume
              value: 0
              duration: 2s
  money_bags_dmd:
    widgets:
      - type: text
        text: Time left (money_bags_money_bags_timer_tick)
        anchor_y: bottom
        style: dmd_small
        y: bottom+1
        anchor_x: right
        x: right-1
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        anchor_x: right
        x: right-1
        y: middle
        style: tall title
      - type: text
        text: Each hit =
        anchor_y: top
        style: dmd_small
        y: top-1
        anchor_x: right
        x: center+16
      - type: text
        text: (player|mb_shot_score)
        anchor_y: top
        style: dmd_small
        y: top-1
        anchor_x: right
        x: right-1
      - type: rectangle
        color: 000000
        height: 32
        width: 128
        opacity: .2
      - type: video
        video: mb_dmd_loop_2
        end_behavior: loop
        anchor_x: left
        x: left
  money_bags_complete:
    widgets:
      - type: text
        text: Money Bags
        anchor_y: top
        style: dmd_med
        y: top-4
        anchor_x: right
        x: right-9
      - type: text
        text: Complete!
        number_grouping: true
        min_digits: 2
        anchor_x: right
        x: right-6
        anchor_y: bottom
        y: bottom+1
        style: tall title
      - type: rectangle
        color: 000000
        height: 32
        width: 128
        opacity: .2
      - type: video
        video: mb_dmd_loop_2
        end_behavior: loop
        anchor_x: left
        x: left

#scoring: #leaving for reference
variable_player:
    mode_money_bags_started:
      mb_shot_score:
        score: (current_player.money_bags_hit + 1) * 1000000
        action: set
    money_bags_advertise_flashing_hit:
      score: (current_player.money_bags_hit + 1) * 1000000

shot_profiles:
    advertise:
      states:
        - name: flashing
          show: flash
        - name: unlit
          show: off
      loop: yes
      advance_on_hit: false

