#config_version=5

#                                            88              
#                                            88              
#                                            88              
#  88,dPYba,,adPYba,    ,adPPYba,    ,adPPYb,88   ,adPPYba,  
#  88P'   "88"    "8a  a8"     "8a  a8"    `Y88  a8P_____88  
#  88      88      88  8b       d8  8b       88  8PP"""""""  
#  88      88      88  "8a,   ,a8"  "8a,   ,d88  "8b,   ,aa  
#  88      88      88   `"YbbdP"'    `"8bbdP"Y8   `"Ybbd8"'

mode:
  priority: 500
  start_events: start_money_bags_mode
  stop_events: money_bags_done

#                                                      ,d            
#                                                      88            
#   ,adPPYba,  8b       d8   ,adPPYba,  8b,dPPYba,   MM88MMM         
#  a8P_____88  `8b     d8'  a8P_____88  88P'   `"8a    88            
#  8PP"""""""   `8b   d8'   8PP"""""""  88       88    88            
#  "8b,   ,aa    `8b,d8'    "8b,   ,aa  88       88    88,           
#   `"Ybbd8"'   88 "8"       `"Ybbd8"'  88       88    "Y888         
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

event_player:
  mode_money_bags_started:
    - mode_running|5s
    - fade_out_base_music
  #logicblock_stop_adding_time_complete:
  logicblock_money_bags_counter_complete:  # brian added
    - money_bags_done|5s
    - money_bags_fade_out|3s
    - money_bags_success|4s   # is there a fail mode todo
  timer_money_bags_timer_complete:
    - money_bags_fail
    - money_bags_done|1
  mode_money_bags_stopping:
    - fade_in_base_music
    - enable_base_left_vuk_hold
  ball_will_end:
    - money_bags_fail
  timer_mb_intro_timer_complete:
    - release_left_vuk_ball
    - disable_base_left_vuk_hold
    - release_top_kicker_ball
    - disable_base_top_kicker_hold

#             88                                            
#             88                          ,d                
#             88                          88                
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   MM88MMM  ,adPPYba,  
#  I8[    ""  88P'    "8a  a8"     "8a    88     I8[    ""  
#   `"Y8ba,   88       88  8b       d8    88      `"Y8ba,   
#  aa    ]8I  88       88  "8a,   ,a8"    88,    aa    ]8I  
#  `"YbbdP"'  88       88   `"YbbdP"'     "Y888  `"YbbdP"'  

shots:
  shot_left_kicking_target:
    switch: s_bottomkickingtarget
    show_tokens:
      light: l_left_longhorn
    profile: advertise
    #advance_events: mode_money_bags_started
    disable_events: timer_money_bags_timer_complete, shot_left_kicking_target_flashing_hit, mode_money_bags_ending
    enable_events: mode_money_bags_started, shot_spinner_to_vuk_advertise_flashing_hit
  
  shot_spinner_to_vuk:
    hit_events: seq_shot_spinner_to_vuk_hit
    profile: advertise
    show_tokens:
      light: l_center_longhorn
    disable_events: timer_money_bags_timer_complete, shot_spinner_to_vuk_flashing_hit, mode_money_bags_ending
    enable_events: shot_left_kicking_target_advertise_flashing_hit

# shot_groups:
#   money_bags:
#     shots: shot_left_kicking_target, shot_spinner_to_vuk
#     #profile: advertise # <<< todo: Where did specifying a profile go? It was in 0.50, but gone after that.
#     rotate_left_events: shot_group_money_bags_flashing_hit
#     disable_events: timer_money_bags_timer_complete
#     rotate_events: money_bags_advertise_flashing_hit

timers:
  mb_intro_timer:
    start_value: 3
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_money_bags_started
  money_bags_timer:
    start_value: 30
    end_value: 0
    direction: down
    tick_interval: 1.25s
    control_events:
      - action: start
        event: timer_mb_intro_timer_complete
      - action: reset
        event: money_bags_hit
      - action: stop
        event: logicblock_money_bags_counter_complete

#                                                       ,d                                        
#                                                       88                                        
#   ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,   MM88MMM   ,adPPYba,  8b,dPPYba,  ,adPPYba,  
#  a8"     ""  a8"     "8a  88       88  88P'   `"8a    88     a8P_____88  88P'   "Y8  I8[    ""  
#  8b          8b       d8  88       88  88       88    88     8PP"""""""  88           `"Y8ba,   
#  "8a,   ,aa  "8a,   ,a8"  "8a,   ,a88  88       88    88,    "8b,   ,aa  88          aa    ]8I  
#   `"Ybbd8"'   `"YbbdP"'    `"YbbdP'Y8  88       88    "Y888   `"Ybbd8"'  88          `"YbbdP"' 

counters:
  money_bags_counter:
    enable_events: mode_money_bags_started
    disable_events: mode_money_bags_ended
    count_events: shot_spinner_to_vuk_advertise_flashing_hit, shot_left_kicking_target_advertise_flashing_hit
    persist_state: true
    events_when_hit: money_bags_hit
    count_complete_value: 5
    starting_count: 0
    direction: up

#             88  88           88                                    
#             88  ""           88                                    
#             88               88                                    
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,                        
#  I8[    ""  88  88  a8"    `Y88  a8P_____88                        
#   `"Y8ba,   88  88  8b       88  8PP"""""""                        
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa                        
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

slide_player:
  mode_money_bags_started:
    mb_intro_dmd:
      target: dmd
    money_bags_stage:
      target: stage
  mode_running:
    money_bags_dmd:
      target: dmd
  logicblock_money_bags_counter_complete:
    money_bags_complete:
      target: dmd

#             88  88           88                         
#             88  ""           88                         
#             88               88                         
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,  ,adPPYba,  
#  I8[    ""  88  88  a8"    `Y88  a8P_____88  I8[    ""  
#   `"Y8ba,   88  88  8b       88  8PP"""""""   `"Y8ba,   
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa  aa    ]8I  
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'  `"YbbdP"'      

slides:
  mb_intro_dmd:
    widgets:
      - type: text
        text: Shooting lit shots
        anchor_y: top
        style: small #dmd_small
        y: top-1
        anchor_x: right
        x: right-1
      - type: text
        text: collects and increases
        style: small #dmd_small
        anchor_y: bottom
        y: center
        anchor_x: right
        x: right-1
      - type: text
        text: Money Bags Value
        style: big #dmd_big
        anchor_y: bottom
        y: bottom+1
        anchor_x: right
        x: right-1
      - type: rectangle
        color: 000000
        height: 32
        width: 128
        opacity: .2
      - type: video
        video: mb_dmd_loop_2
        end_behavior: loop
        anchor_x: left
        x: left
  money_bags_stage:
    widgets:
      - type: video
        video: mb_beer_thirty
        end_behavior: loop
        animations:
          money_bags_fade_out:
            - property: volume
              value: 0
              duration: 2s
  money_bags_dmd:
    widgets:
      - type: text
        text: Time left (money_bags_money_bags_timer_tick)
        anchor_y: bottom
        style: small #dmd_small
        y: bottom+1
        anchor_x: right
        x: right-1
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        anchor_x: right
        x: right-1
        y: middle
        style: tall_title
      - type: text
        text: Each hit =
        anchor_y: top
        style: small #dmd_small
        y: top-1
        anchor_x: right
        x: center+16
      - type: text
        text: (player|mb_shot_score)
        anchor_y: top
        style: small #dmd_small
        y: top-1
        anchor_x: right
        x: right-1
      - type: rectangle
        color: 000000
        height: 32
        width: 128
        opacity: .2
      - type: video
        video: mb_dmd_loop_2
        end_behavior: loop
        anchor_x: left
        x: left
  money_bags_complete:
    widgets:
      - type: text
        text: Money Bags
        anchor_y: top
        style: medium #dmd_med
        y: top-4
        anchor_x: right
        x: right-9
      - type: text
        text: Complete!
        number_grouping: true
        min_digits: 2
        anchor_x: right
        x: right-6
        anchor_y: bottom
        y: bottom+1
        style: tall_title
      - type: rectangle
        color: 000000
        height: 32
        width: 128
        opacity: .2
      - type: video
        video: mb_dmd_loop_2
        end_behavior: loop
        anchor_x: left
        x: left

#                                       88              88           88              
#                                       ""              88           88              
#                                                       88           88              
#  8b       d8  ,adPPYYba,  8b,dPPYba,  88  ,adPPYYba,  88,dPPYba,   88   ,adPPYba,  
#  `8b     d8'  ""     `Y8  88P'   "Y8  88  ""     `Y8  88P'    "8a  88  a8P_____88  
#   `8b   d8'   ,adPPPPP88  88          88  ,adPPPPP88  88       d8  88  8PP"""""""  
#    `8b,d8'    88,    ,88  88          88  88,    ,88  88b,   ,a8"  88  "8b,   ,aa  
#      "8"      `"8bbdP"Y8  88          88  `"8bbdP"Y8  8Y"Ybbd8"'   88   `"Ybbd8"'
#               88                                                                   
#               88                                                                   
#               88                                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,                  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8                  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88                          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88                          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88                          
#  88                               d8'                                              
#  88                              d8' 

variable_player:
  mode_money_bags_started:
    mb_shot_score:
      int: (current_player.money_bags_hit + 1) * 1000000
      action: set
  money_bags_hit:
    score: (current_player.money_bags_hit + 1) * 1000000



shot_profiles:
  advertise:
    states:
      - name: flashing
        show: flash
    #   # - name: unlit
    #   #   show: off
    # loop: yes
    # advance_on_hit: true
