#config_version=4

# Wizard mode. Let's map this out:

#We need the initial show/dots/whatever after Begin Round is shot. This shows METAL RODEO! > NUM QUARTERS >
#SCORE PER SHOT > UNLIMITED BALLS FOR 60 SECONDS on DMD while playing light show synchronized with the Only in America
#video on the LCD.
#
#Eject from lower VUK kicks off multiball. This is a timed multiball, so need to figure that out.
#  I think we can just use a shoot_again time of 60s or whatever. After that runs out, though, we need
#  a way to stop the game, collect the balls, and continue the ball. Maybe we just disable flippers? I don't want
#  the ball to end, though, so that has to be worked around. We could just change timer to 30s, then let the round play
#  out like a normal multiball, but I like that effect.
#
#All shots lit:
#  N. America (disable diverter)
#  Loop around Jukebox
#  Europe (Spinner to VUK)
#  Australia (drop two targets)
#  S. America (right ramp)
#  Jukebox
#
#Need to figure out scoring based on a lookup table or something. Or just use logic, like:
#  if num_quarters <7 score = 1M
#
#  <7 Quarters, 1M per shot
#  7-12 Quarters, 2M per shot
#  13-24 Quarters, 3M per shot
#  25+ Quarters, 5M per shot
#
#  Also, shooting Collect Wizard shot (Australia) collects wizard bonus as well as shot score.
#
#Need light show for shots hit during this. Maybe also a big sound, like STTNG's sound during FF.
#
#Keep track of score during MR. When over, before launching ball to continue playing, darken playfield, show on DMD:
#  MODE SCORE > PLAYER NUM > KEEP SHOOTING
#
#Mode restarting just goes back to base mode.

mode:
  start_events: s_rightinlane_active
  stop_events: s_rightoutlane_active
  priority: 2000

event_player:
  mode_metal_rodeo_started:
    fade_out_base_music

#multiballs:
#  metal_rodeo_multiball:
#    ball_count: 4
#    shoot_again: 40
#    start_events: s_rightinlane_active

show_player:
  mode_metal_rodeo_started:
    mr_mode_sweep:
      loops: -1
    mr_music_lights_show:
      loops: 0
      show_tokens:
        left: left
        center: center
        right: right
        gi: gi

#slide_player:
#  mode_metal_rodeo_started:
#    mr_stage:
#      target: stage

slides:
  mr_stage:
    widgets:
      - type: video
        video: mr_bed3
        end_behavior: stop
        animations:
          mr_fade_out:
            - property: volume
              value: 0
              duration: 2s