#config_version=4

# Wizard mode. Let's map this out:

#We need the initial show/dots/whatever after Begin Round is shot. This shows METAL RODEO! > NUM QUARTERS >
#SCORE PER SHOT > UNLIMITED BALLS FOR 60 SECONDS on DMD while playing light show synchronized with the Only in America
#video on the LCD.
#
#Eject from lower VUK kicks off multiball. This is a timed multiball, so need to figure that out.
#  I think we can just use a shoot_again time of 60s or whatever. After that runs out, though, we need
#  a way to stop the game, collect the balls, and continue the ball. Maybe we just disable flippers? I don't want
#  the ball to end, though, so that has to be worked around. We could just change timer to 30s, then let the round play
#  out like a normal multiball, but I like that effect.

#Here's the plan:

#Set multiball timer super high, like 100s (gives lots of time for balls to return. Doesn't matter how
#long because we're going to turn it off manually anyway)

#Set mode timer to 30s for amount of time for unlimited balls

#after 30s, disable flippers. Kill multiball. Enable Ball Saver and tell it not to autolaunch

#  Also, play wrap-up show.
#    Lights out
#    Maybe show mr total score ( var is "mr_score")
#    Keep Shooting
#    Lights on
#  Release queue or whatever to let ball shoot again. Ball should continue.

#
#All shots lit:
#  N. America (disable diverter)
#  Loop around Jukebox
#  Europe (Spinner to VUK)
#  Australia (drop two targets)
#  S. America (right ramp)
#  Jukebox
#
#Need to figure out scoring based on a lookup table or something. Or just use logic, like:
#  if num_quarters <7 score = 1M
#
#  <7 Quarters, 1M per shot
#  7-12 Quarters, 2M per shot
#  13-24 Quarters, 3M per shot
#  25+ Quarters, 5M per shot
#
#  Also, shooting Collect Wizard shot (Australia) collects wizard bonus as well as shot score.
#
#Need light show for shots hit during this. Maybe also a big sound, like STTNG's sound during FF.
#
#Keep track of score during MR. When over, before launching ball to continue playing, darken playfield, show on DMD:
#  MODE SCORE > PLAYER NUM > KEEP SHOOTING
#
#Mode restarting just goes back to base mode.

mode:
  start_events: start_metal_rodeo
  stop_events: metal_rodeo_done
  priority: 2000

event_player:
  mode_metal_rodeo_started:
    fade_out_base_music
    play_intro
    block_jukebox_hits
    stop_quarters_mode
    mode_running|5s
  mode_metal_rodeo_stopping:
    fade_in_base_music
    unblock_jukebox_hits
    start_quarters_mode

multiballs:
  mr_launch_balls:
    ball_count: 4
    shoot_again: 100
    start_events: mr_launch_balls
    stop_events: timer_mr_multiball_timer_complete, mode_metal_rodeo_stopping

timers:
  mr_multiball_timer:
    start_value: 30 # This is how long unlimited balls goes for
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mr_launch_balls

ball_saves:
  mr_ball_save:
    active_time: 30s # This just gives time to collect balls from the playfield.
    timer_start_events: timer_mr_multiball_timer_complete
    auto_launch: False

show_player:
  play_intro:
    mr_intro_show:
      loops: 0
      show_tokens:
        left: left
        center: center
        right: right
        gi: gi
  mr_go:
    mr_mode_sweep:
      loops: -1
    mr_music_lights_show:
      loops: 0
      sync_ms: 250
      show_tokens:
        left: left
        center: center
        right: right
        gi: gi
    mr_bed_show:
      loops: -1
      sync_ms: 250

#slide_player:
#  mode_metal_rodeo_started:
#    mr_stage:
#      target: stage

slides:
  mr_stage:
    widgets:
      - type: video
        video: mr_bed3
        end_behavior: stop
        animations:
          mr_fade_out:
            - property: volume
              value: 0
              duration: 2s
  mr_total_score:
    widgets:
      - type: text
        text: "METAL RODEO TOTAL:"
        color: black
        style: dmd_med
        anchor_y: top
        y: top-2
      - type: text
        number_grouping: True
        text: (player|mr_score)
        color: black
        style: dmd_huge
        anchor_y: bottom
        y: bottom
      - type: rectangle
        color: white
        height: 32
        width: 128
  mr_keep_shooting:
    widgets:
      - type: text
        text: KEEP SHOOTING
        style: dmd_huge
        color: ff4400
        anchor_y: center
        y: center-1
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 150ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 150ms
            repeat: true
            easing: in_quint
      - type: text
        text: "PLAYER (number):"
        style: dmd_med
        anchor_y: top
        y: top
        color: red
      - type: text
        text: BALL (ball)
        style: dmd_small
        anchor_y: bottom
        y: 0
  mr_good_job:
    widgets:
      - type: text
        color: red
        y: center-1
        font_size: 30
        style: dmd_huge
        text: GOOD JOB!
  mr_intro_stage:
    widgets:
      - type: rectangle
        width: 800
        height: 480
        color: black
        x: center
        y: center
  mr_intro_dmd_1:
    widgets:
      - type: video
        video: mr_intro_movie
        end_behavior: stop
  all_shots_lit:
    widgets:
      - type: text
        text: ALL SHOTS LIT
        color: red
        y: center-1
        font_size: 30
        style: dmd_huge
  unlimited_balls:
    widgets:
      - type: text
        text: Unlimited balls
        color: red
        style: dmd_big
        anchor_y: top
        y: top-4
      - type: text
        text: for 40 seconds
        color: yellow
        style: dmd_big
        anchor_y: bottom
        y: bottom+4
  quarter_count:
    widgets:
      - type: text
        text: (player|quarters) QUARTERS
        color: gray
        style: dmd_huge
        font_size: 30
        y: center-1
  shot_score:
    widgets:
      - type: text
        text: EACH SHOT SCORES
        color: gray
        style: dmd_med
        anchor_y: top
        y: top-2
      - type: text
        text: (player|mr_shot_score) MILLION!
        color: red
        style: dmd_huge
        anchor_y: bottom
        y: bottom

scoring:
  sw_jukebox:
    score: current_player.mr_shot_score * 1000000
    mr_score: current_player.mr_shot_score * 1000000
  shot_spinner_to_vuk_hit:
    score: current_player.mr_shot_score * 1000000
    mr_score: current_player.mr_shot_score * 1000000
  shot_right_ramp_full_loop_hit:
    score: current_player.mr_shot_score * 1000000
    mr_score: current_player.mr_shot_score * 1000000
  shot_pops_to_vuk_hit:
    score: (current_player.mr_shot_score * 1000000) + (current_player.wizard_score * current_player.num_albums)
    mr_score: current_player.mr_shot_score * 1000000
  s_leftorbit_active:
    score: current_player.mr_shot_score * 1000000
    mr_score: current_player.mr_shot_score * 1000000
  shot_lower_vuk_from_playfield_hit:
    score: current_player.mr_shot_score * 1000000
    mr_score: current_player.mr_shot_score * 1000000

sound_player:
  sw_jukebox:
    boom:
      action: play
      loops: 0
  shot_spinner_to_vuk_hit:
    boom:
      action: play
      loops: 0
  shot_right_ramp_full_loop_hit:
    boom:
      action: play
      loops: 0
  shot_pops_to_vuk_hit:
    boom:
      action: play
      loops: 0
  s_leftorbit_active:
    boom:
      action: play
      loops: 0
  shot_lower_vuk_from_playfield_hit:
    boom:
      action: play
      loops: 0




