#config_version=4
Mode:
  start_events: light_mission_select
  stop_events: mission_rotator_ready
  priority: 200

show_player:
  s_rightrampopto_active:
    flash_once:
      loops: 3
      speed: 4
      show_tokens:
        led: l_right_ramp_flasher
  mode_light_mission_select_started:
    flash:
      loops: -1
      show_tokens:
        led: l_ramp_fire

event_player:
    s_rightrampopto_active: enable_mission_selection
