#config_version=4

# this mode handles the lighting of the right ramp and the lower vuk "begin_round" shot

# the mode starts when a mission is not running, and stops when a mission starts


mode:
  start_events: light_mission_select
  stop_events: mission_started, stop_mission_select
  priority: 200

show_player:
  s_rightrampopto_active:
    flash_once:
      loops: 3
      speed: 4
      show_tokens:
        led: l_right_ramp_flasher
  mode_light_mission_select_started:
    flash:
      loops: -1
      show_tokens:
        led: l_ramp_fire

event_player:
    s_rightrampopto_active: enable_mission_selection

shots:
  begin_round:
    profile: begin_round
    enable_events: s_rightrampopto_active
    hit_events: shot_lower_vuk_from_playfield_hit

shot_profiles:
  begin_round:
    states:
      - name: lit
        show: on
    advance_on_hit: false