#config_version=4

# player needs to build a poker hand of 5 cards. The current selected card is
# changed by hitting the spinner, and that card is "locked in" by hitting the
# left VUK. Once the player locks in all five cards, the mode is complete and
# the player is awarded a prize based on the hand they built.

# Each hit of the spinner changes the selected card. Once a card is locked, it
# cannot be changed.

# This mode has a ball-to-ball memory and will pick up where it left off if
# it starts again.

# The mode has a 30s timer, and the player can add 5s by collecting a card.

# Scoring table:
# High card = point value of card. (hah!)
# 1 pair = 1,000,000 pts (he also says to award Mystery, but we haven't gotten that far)
# 2 pair = 2,000,000 pts (he also says to award Mystery, but we haven't gotten that far)
# 3 of a kind = 5,000,000 pts (he also says to award Managers Choice, but we haven't gotten that far)
# Straight = Extra Ball
# Flush = Extra Ball
# Full House = Extra Ball
# 4 of a kind = 1 Special (don't know what that is yet)
# Straight Flush = 3 Specials (ditto)
# Royal Flush = Extra Ball, Special, Complete BROOKS N DUNN, 10M pts, and double score (?)

#todo make all lights around left hole flash to collect card. They can pretty much just flashing all the time after the
#todo spinner is hit the first time.

mode:
  start_events: start_play_poker_mode
  stop_events: play_poker_done
  priority: 500
  code: play_poker.PlayPoker

event_player:
  mode_play_poker_started:
      - fade_out_base_music
#      - disable_base_left_vuk_hold  # we'll use the hold from base mode
#      - release_left_vuk_ball|3s # todo change to after intro show
      - start_poker_music|1s
  mode_play_poker_stopping:
    fade_in_base_music
    enable_base_left_vuk_hold
  ball_will_end:
    play_poker_fail

sound_player:
  start_poker_music:
    poker_loop:
      action: play
      loops: -1
      mode_end_action: stop

timers:
    poker_countdown:
      start_value: 30
      direction: down
      end_value: 0
      max_value: 30
      control_events:
        - event: shot_lower_vuk_from_playfield_hit
          action: add
          value: 5
        - event: shot_lower_vuk_from_playfield_hit
          action: stop
        - event: balldevice_bd_lower_vuk_ball_eject_success
          action: start
        - event: start_poker_countdown
          action: start
        - event: poker_deck_complete
          action: stop

show_player:
    mode_play_poker_started:
        play_poker_intro:
            events_when_stopped: start_poker_countdown, release_left_vuk_ball, show_player_cards
            loops: 0
    flipper_cancel:
        play_poker_intro:
            action: stop

slide_player:
  timer_poker_countdown_tick:
    poker_countdown:
      target: stage
  show_player_cards: card_background
  poker_royal_flush:
    poker_royal_flush:
      expire: 2s
  poker_straight_flush:
    poker_straight_flush:
      expire: 2s
  poker_four_of_a_kind:
    poker_four_of_a_kind:
      expire: 2s
  poker_full_house:
    poker_full_house:
      expire: 2s
  poker_flush:
    poker_flush:
      expire: 2s
  poker_straight:
    poker_straight:
      expire: 2s
  poker_three_of_a_kind:
    poker_three_of_a_kind:
      expire: 2s
  poker_two_pairs:
    poker_two_pairs:
      expire: 2s
  poker_one_pair:
    poker_one_pair:
      expire: 2s
  poker_high_card:
    poker_high_card:
      expire: 2s

slides:
  pp_intro_dmd_1:
    widgets:
      - type: text
        text: Hit spinner to
        anchor_y: top
        style: dmd_small
        y: top-1
        anchor_x: right
        x: right-1
      - type: text
        text: get card
        style: dmd_small
        anchor_y: bottom
        y: center
        anchor_x: right
        x: right-1
    target: dmd
# This will transition in over the first slide, right to left.
  pp_intro_dmd_2:
    transition: # I think this is how to do this?
        type: push
        direction: left
    widgets:
      - type: text
        text: Shoot left hole
        anchor_y: top
        style: dmd_small
        y: top-1
        anchor_x: right
        x: right-1
      - type: text
        text: to collect
        style: dmd_small
        anchor_y: bottom
        y: center
        anchor_x: right
        x: right-1
    target: dmd
# This plays the music video on the stage
  pp_stage:
    widgets:
      - type: video
        video: pp_play_something_country
        end_behavior: loop
        animations:
          music_awards_fade_out:
            - property: volume
              value: 0
              duration: 2s

  full_cards:
        widgets:
          - type: image
            image: nine_clubs
            x: 14
          - type: image
            image: eight_clubs
            x: 39
          - type: image
            image: seven_clubs
            x: 64
          - type: image
            image: six_clubs
            x: 89
          - type: image
            image: five_clubs
            x: 114

  card_background:
    widgets:
      - type: rectangle
        x: 14
        width: 20
        height: 30
        color: black
        corner_radius: 3
      - type: rectangle
        x: 14
        width: 22
        height: 32
        color: white
        corner_radius: 3
      - type: rectangle
        x: 39
        width: 20
        height: 30
        color: black
        corner_radius: 3
      - type: rectangle
        x: 39
        width: 22
        height: 32
        color: white
        corner_radius: 3
      - type: rectangle
        x: 64
        width: 20
        height: 30
        color: black
        corner_radius: 3
      - type: rectangle
        x: 64
        width: 22
        height: 32
        color: white
        corner_radius: 3
      - type: rectangle
        x: 89
        width: 20
        height: 30
        color: black
        corner_radius: 3
      - type: rectangle
        x: 89
        width: 22
        height: 32
        color: white
        corner_radius: 3
      - type: rectangle
        x: 114
        width: 20
        height: 30
        color: black
        corner_radius: 3
      - type: rectangle
        x: 114
        width: 22
        height: 32
        color: white
        corner_radius: 3

  poker_countdown:
    widgets:
      - type: text
        text: (ticks)
        style: dmd_huge
        font_size: 400
        y: 300
      - type: text
        text: LEFT HOLE = LOCK SELECTED CARD
        style: dmd_huge
        y: 30
        font_size: 70
      - type: text
        text: SPINNER = PICK NEW CARD
        style: dmd_huge
        y: 90
        font_size: 70

  poker_royal_flush:
    widgets:
      - type: text
        text: ROYAL FLUSH!
        style: dmd_huge
  poker_straight_flush:
    widgets:
      - type: text
        text: STRAIGHT FLUSH!
        style: dmd_huge
  poker_four_of_a_kind:
    widgets:
      - type: text
        text: FOUR OF A KIND!
        style: dmd_huge
  poker_full_house:
    widgets:
      - type: text
        text: FULL HOUSE!
        style: dmd_huge
  poker_flush:
    widgets:
      - type: text
        text: FLUSH!
        style: dmd_huge
  poker_straight:
    widgets:
      - type: text
        text: STRAIGHT!
        style: dmd_huge
  poker_three_of_a_kind:
    widgets:
      - type: text
        text: 3 OF A KIND!
        style: dmd_huge
  poker_two_pairs:
    widgets:
      - type: text
        text: TWO PAIRS!
        style: dmd_huge
  poker_one_pair:
    widgets:
      - type: text
        text: ONE PAIR!
        style: dmd_huge
  poker_high_card:
    widgets:
      - type: text
        text: (value_name) HIGH
        style: dmd_huge

widgets:
  card_1_solid:
    - type: image
      image:
      x: 14
      z: 1
  card_1_flash:
    - type: image
      image:
      x: 14
      z: 1
      animations:
        add_to_slide:
        - property: opacity
          value: 0
          duration: 300ms
          easing: in_quint
        - property: opacity
          value: 1
          duration: 300ms
          repeat: true
          easing: in_quint

  card_2_solid:
    - type: image
      image:
      x: 39
      z: 1
  card_2_flash:
    - type: image
      image:
      x: 39
      z: 1
      animations:
        add_to_slide:
        - property: opacity
          value: 0
          duration: 300ms
          easing: in_quint
        - property: opacity
          value: 1
          duration: 300ms
          repeat: true
          easing: in_quint

  card_3_solid:
    - type: image
      image:
      x: 64
      z: 1
  card_3_flash:
    - type: image
      image:
      x: 64
      z: 1
      animations:
        add_to_slide:
        - property: opacity
          value: 0
          duration: 300ms
          easing: in_quint
        - property: opacity
          value: 1
          duration: 300ms
          repeat: true
          easing: in_quint

  card_4_solid:
    - type: image
      image:
      x: 89
      z: 1
  card_4_flash:
    - type: image
      image:
      x: 89
      z: 1
      animations:
        add_to_slide:
        - property: opacity
          value: 0
          duration: 300ms
          easing: in_quint
        - property: opacity
          value: 1
          duration: 300ms
          repeat: true
          easing: in_quint

  card_5_solid:
    - type: image
      image:
      x: 114
      z: 1
  card_5_flash:
    - type: image
      image:
      x: 114
      z: 1
      animations:
        add_to_slide:
        - property: opacity
          value: 0
          duration: 300ms
          easing: in_quint
        - property: opacity
          value: 1
          duration: 300ms
          repeat: true
          easing: in_quint

widget_player:
  poker_card_1_solid:
    card_1_solid:
      slide: card_background
  poker_card_2_solid:
    card_2_solid:
      slide: card_background
  poker_card_3_solid:
    card_3_solid:
      slide: card_background
  poker_card_4_solid:
    card_4_solid:
      slide: card_background
  poker_card_5_solid:
    card_5_solid:
      slide: card_background

  poker_card_1_flash:
    card_1_flash:
      slide: card_background
  poker_card_2_flash:
    card_2_flash:
      slide: card_background
  poker_card_3_flash:
    card_3_flash:
      slide: card_background
  poker_card_4_flash:
    card_4_flash:
      slide: card_background
  poker_card_5_flash:
    card_5_flash:
      slide: card_background

  poker_remove_card_1:
    card_1_flash:
      action: remove
  poker_remove_card_2:
    card_2_flash:
      action: remove
  poker_remove_card_3:
    card_3_flash:
      action: remove
  poker_remove_card_4:
    card_4_flash:
      action: remove
  poker_remove_card_5:
    card_5_flash:
      action: remove
