#config_version=4
Mode:
  start_events: start_play_poker_mode
  stop_events: play_poker_done
  priority: 500

# TODO
# Also need a counter to count how many cards and something to remember the cards.
# Stage show
# There is something not quite right about this show.
# WHEN YOU PLAY THIS, YOU HAVE TO HIT SPINNER, THEN TOP RIGHT VUK QUICKLY AFTER
# Scoring:
#1 Pair- Mystery 1,000,000
#2 Pair- Mystery 3,000,000
#3 Kind- Managers Choice 5,000,000
#Full House- Extra Ball
#Straight- Extra Ball
#4 Kind- 1 Special
#5 Kind- 3 Specials
#5 Aces- Award Extra Ball, Special, Complete BROOKS N DUNN, 10M, and Double Score.

event_player:
  mode_play_poker_started:
    play_poker_done|15s
    play_poker_success|14s

ball_locks:
  poker_lock:
    balls_to_lock: 1
    lock_devices: bd_top_right_vuk
    enable_events: shot_spinner_to_vuk_hit
    request_new_balls_to_pf: False
    release_one_events: timer_display_timer_complete #probably switch this to an event fired by a show
    disable_events: timer_display_timer_complete|1

# Also need intro dots and instructions

timers:
    shuffle_timer:
        start_value: 1
        direction: down
        restart_on_complete: true
        control_events:
          - event: shot_spinner_to_vuk_hit
            action: start
          - event: timer_shuffle_timer_complete
            action: stop
    display_timer:
        start_value: 5
        direction: down
        restart_on_complete: true
        control_events:
           - event: timer_shuffle_timer_complete
             action: start
           - event: timer_display_timer_complete
             action: stop

show_player:
    s_spinner_active:
        cycle_cards:
            loops: 3
    timer_shuffle_timer_complete:
        cycle_cards:
            action: stop

# Need to get music from base to fade away. Maybe use ducking? Need to configure
# the release to happen when the ball ejects, though, which isn't a thing.
      # This might be ok now - moved poker_loop to music track and set to preload

    poker_ten_received:
        award_card:
            show_tokens:
                card_image: 10_dmd
            loops: -1
    poker_jack_received:
        award_card:
            show_tokens:
                card_image: jack_dmd
            loops: -1
    poker_queen_received:
        award_card:
            show_tokens:
                card_image: queen_dmd
            loops: -1
    poker_king_received:
        award_card:
            show_tokens:
                card_image: king_dmd
            loops: -1
    poker_ace_received:
        award_card:
            show_tokens:
                card_image: ace_dmd
            loops: -1

random_event_player:
    timer_shuffle_timer_started:
        - poker_ten_received
        - poker_jack_received
        - poker_queen_received
        - poker_king_received
        - poker_ace_received

sound_player:
  timer_shuffle_timer_started:
    poker_loop:
        action: play
        loops: -1