#config_version=5
#config_version=4 # Left for reference. Did NOT double check

# Settings here overwrite the defaults in mpf/modes/tilt

tilt:
  warnings_to_tilt: 3
  multiple_hit_window: 300ms
  settle_time: 5s

slide_player:
  tilt_warning_1: tilt_warning_1_slide
  tilt_warning_2: tilt_warning_2_slide
  tilt: tilt_slide
  tilt_clear:
    tilt:
      action: remove

slides:
  tilt_warning_1_slide:
    widgets:
    - type: text
      text: WARNING!
      style: dmd_big
      color: red
    - type: line
      points: 1, 0, 1, 32, 128, 32, 128, 1, 1, 1
      color: orange
    - type: line
      points: 2, 1, 2, 31, 127, 31, 127, 2, 2, 2
      color: yellow
    expire: 1s

  tilt_warning_2_slide:
    widgets:
    - type: text
      text: WARNING!
      style: dmd_big
      color: red
      y: 22
    - type: text
      text: WARNING!
      style: dmd_big
      color: red
      y: 10
    - type: line
      points: 1, 0, 1, 32, 128, 32, 128, 1, 1, 1
      color: orange
    - type: line
      points: 2, 1, 2, 31, 127, 31, 127, 2, 2, 2
      color: yellow
    expire: 2s

  tilt_slide:
    widgets:
    - type: text
      text: TIL
      style: dmd_med
      color: red
      x: 60
    - type: text
      text: T
      style: dmd_med
      color: red
      x: 69
    - type: line
      points: 1, 0, 1, 32, 128, 32, 128, 1, 1, 1
      color: orange
    - type: line
      points: 2, 1, 2, 31, 127, 31, 127, 2, 2, 2
      color: yellow