#config_version=5


# todo we should add a light show that disables any other lights that might
# be flashing since really all we want the player to do is shoot the JB

mode:
  start_events: start_jukebox_hurryup
  stop_events: stop_jukebox_hurryup_mode
  priority: 1000

#                                                      ,d            
#                                                      88            
#   ,adPPYba,  8b       d8   ,adPPYba,  8b,dPPYba,   MM88MMM         
#  a8P_____88  `8b     d8'  a8P_____88  88P'   `"8a    88            
#  8PP"""""""   `8b   d8'   8PP"""""""  88       88    88            
#  "8b,   ,aa    `8b,d8'    "8b,   ,aa  88       88    88,           
#   `"Ybbd8"'   88 "8"       `"Ybbd8"'  88       88    "Y888         
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

event_player:
  mode_jukebox_hurryup_started: 
    - fade_out_base_music
    - stop_mission_select
  timer_jb_display_timer_complete: jukebox_hurryup_done
  jukebox_hurryup_done:
    - fade_in_base_music|3s
    - stop_jukebox_hurryup_mode|4s


#                                       88              88           88              
#                                       ""              88           88              
#                                                       88           88              
#  8b       d8  ,adPPYYba,  8b,dPPYba,  88  ,adPPYYba,  88,dPPYba,   88   ,adPPYba,  
#  `8b     d8'  ""     `Y8  88P'   "Y8  88  ""     `Y8  88P'    "8a  88  a8P_____88  
#   `8b   d8'   ,adPPPPP88  88          88  ,adPPPPP88  88       d8  88  8PP"""""""  
#    `8b,d8'    88,    ,88  88          88  88,    ,88  88b,   ,a8"  88  "8b,   ,aa  
#      "8"      `"8bbdP"Y8  88          88  `"8bbdP"Y8  8Y"Ybbd8"'   88   `"Ybbd8"'
#               88                                                                   
#               88                                                                   
#               88                                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,                  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8                  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88                          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88                          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88                          
#  88                               d8'                                              
#  88                              d8' 


#scoring: #leaving for reference
variable_player:
  jukebox_hurryup_hit:  # fires when the JB is hit
    score: current_player.jukebox_hurryup_value  # adds the score
    jukebox_hurryup_total: current_player.jukebox_hurryup_value  # tracks how many points the player got in this mode
  player_jukebox_hurryup_jb_score_timer_tick:
    jukebox_hurryup_value:  # does the math for the score, with "set" action to reset this var each time instead of adding to it
      int: current_player.jukebox_hurryup_jb_score_timer_tick * device.counters.jukebox_hurryup_score_multiplier.value * 6660
      action: set
    # jukebox_hurryup_test_ticks_remaining:
    #   int: current_player.jukebox_hurryup_jb_score_timer_tick
    #   action: set
    # jukebox_hurryup_test_multiplier_value:
    #   int: device.counters.jukebox_hurryup_score_multiplier.value
    #   action: set
  mode_jukebox_hurryup_started:
    jukebox_hurryup_total:  # resets the mode total each time the mode starts since this is in a player var
      int: 0
      action: set


#           88                                                         
#    ,d     ""                                                         
#    88                                                                
#  MM88MMM  88  88,dPYba,,adPYba,    ,adPPYba,  8b,dPPYba,  ,adPPYba,  
#    88     88  88P'   "88"    "8a  a8P_____88  88P'   "Y8  I8[    ""  
#    88     88  88      88      88  8PP"""""""  88           `"Y8ba,   
#    88,    88  88      88      88  "8b,   ,aa  88          aa    ]8I  
#    "Y888  88  88      88      88   `"Ybbd8"'  88          `"YbbdP"' 

timers:
  start_timer: #This just plays while we show some dots
    start_value: 3
    end_value: 0
    direction: down
    tick_interval: 1s
    bcp: no
    control_events:
      - event: mode_jukebox_hurryup_started
        action: start

  jb_display_timer:  # the "Friendly" countdown from 15 to 0
    start_value: 15
    max_value: 15
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
        - event: sw_subway
          action: pause
        - event: balldevice_playfield_ball_enter
          action: start
        - event: timer_start_timer_complete
          action: start
        - event: jukebox_hurryup_hit
          # logic block hit event, not switch hit, so this won't count if the
          # mode is complete but still running it's final summary slide
          action: add
          value: 7

  jb_score_timer:  # a more precise 1/10th second time for the score countdown
    start_value: 150
    max_value: 150
    end_value: 0
    direction: down
    tick_interval: 100ms
    bcp: no
    control_events:
        - event: timer_jb_display_timer_started
          action: start
        - event: timer_jb_display_timer_paused
          action: pause
        - event: timer_jb_display_timer_stopped
          action: stop
        - event: jukebox_hurryup_hit
          # logic block hit event, not switch hit, so this won't count if the
          # mode is complete but still running it's final summary slide
          action: add
          value: 70

#                                                       ,d                                        
#                                                       88                                        
#   ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,   MM88MMM   ,adPPYba,  8b,dPPYba,  ,adPPYba,  
#  a8"     ""  a8"     "8a  88       88  88P'   `"8a    88     a8P_____88  88P'   "Y8  I8[    ""  
#  8b          8b       d8  88       88  88       88    88     8PP"""""""  88           `"Y8ba,   
#  "8a,   ,aa  "8a,   ,a8"  "8a,   ,a88  88       88    88,    "8b,   ,aa  88          aa    ]8I  
#   `"Ybbd8"'   `"YbbdP"'    `"YbbdP'Y8  88       88    "Y888   `"Ybbd8"'  88          `"YbbdP"' 

#logic_blocks:
counters:
  jukebox_hurryup_score_multiplier:
    count_events: sw_jukebox_hit
    events_when_hit: jukebox_hurryup_hit
    direction: up
    # The next three lines ensure that the value of this counter is 1, 3, and
    # 5, which gives us the multipliers we need for the scoring math
    starting_count: 1
    count_complete_value: 6  # updated with each hit, but has to be higher than 5 because we want to count the final hit, not end on it
    count_interval: 2
    disable_on_complete: true
    disable_events: jukebox_hurryup_done
    events_when_complete: jukebox_hurryup_done
    # player_variable: jukebox_hurryup_score_multiplier # removed. Why? Probably have to fix.
    console_log: full

#             88  88           88                                    
#             88  ""           88                                    
#             88               88                                    
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,                        
#  I8[    ""  88  88  a8"    `Y88  a8P_____88                        
#   `"Y8ba,   88  88  8b       88  8PP"""""""                        
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa                        
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

slide_player:
  mode_jukebox_hurryup_started:
    jukebox_hurryup_stage:
      target: stage
    jukerbox_hurryup_intro:
      target: dmd
  timer_jb_score_timer_tick: jukebox_hurryup_dmd
  jukebox_hurryup_done:
    jukebox_hurryup_done:
      # priority shift +1 so this slide shows on top of the counter slide
      priority: 1

#             88  88           88                         
#             88  ""           88                         
#             88               88                         
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,  ,adPPYba,  
#  I8[    ""  88  88  a8"    `Y88  a8P_____88  I8[    ""  
#   `"Y8ba,   88  88  8b       88  8PP"""""""   `"Y8ba,   
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa  aa    ]8I  
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'  `"YbbdP"'

slides:
  jukerbox_hurryup_intro:
    widgets:
      - type: text
        text: SHOOT THE JUKEBOX
        style: huge 
        color: yellow
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 100ms
            easing: in_quint
          - property: opacity
            value: 1
            duration: 100ms
            repeat: true
            easing: in_quint
      - type: text
        text: JAMBOREE!
        style: huge 
        color: red
        font_size: 41
        y: 15
  jukebox_hurryup_stage:
    widgets:
      - type: image
        image: jb_hurryup_arrow
        anchor_x: middle
        anchor_y: top
        x: middle
        y: top
        animations:
          show_slide:
            - property: y
              value: -10
              duration: 800ms
            - property: y
              value: 300
              duration: 800ms
              repeat: true
      - type: video
        volume: 0.4
        video: jb_hurry_up_foggy_mountain
        end_behavior: loop
        animations:
          jukebox_hurryup_done:
            - property: volume
              value: 0
              duration: 2s
  jukebox_hurryup_dmd:
    widgets:
      - type: text
        text: NEXT HIT = (player|jukebox_hurryup_value)
        color: red
        style: small 
        y: 29
        number_grouping: true
        anchor_x: left
        x: 25
      - type: text
        text: "TIME REMAINING: (player|jukebox_hurryup_jb_display_timer_tick)"
        style: huge 
        anchor_x: left
        x: 8
      - type: text
        text: "YOUR SCORE (player|score)"
        style: small 
        y: 3
        number_grouping: true
  jukebox_hurryup_done:
    widgets:
      - type: text
        text: PHEW!
        style: huge 
        y: 20
      - type: text
        text: "JAMBOREE TOTAL: (player|jukebox_hurryup_total)"
        style: small 
        y: 8
        number_grouping: true

#                                                             88     
#                                                             88     
#                                                             88     
#  ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,    ,adPPYb,88     
#  I8[    ""  a8"     "8a  88       88  88P'   `"8a  a8"    `Y88     
#   `"Y8ba,   8b       d8  88       88  88       88  8b       88     
#  aa    ]8I  "8a,   ,a8"  "8a,   ,a88  88       88  "8a,   ,d88     
#  `"YbbdP"'   `"YbbdP"'    `"YbbdP'Y8  88       88   `"8bbdP"Y8     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

sound_player:
  jukebox_hurryup_hit:
    yeehaw:
      loops: 0

#             88                                                       
#             88                                                       
#             88                                                       
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   8b      db      d8   
#  I8[    ""  88P'    "8a  a8"     "8a  `8b    d88b    d8'   
#   `"Y8ba,   88       88  8b       d8   `8b  d8'`8b  d8'     
#  aa    ]8I  88       88  "8a,   ,a8"    `8bd8'  `8bd8'     
#  `"YbbdP"'  88       88   `"YbbdP"'       YP      YP     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8' 

show_player:
  mode_jukebox_hurryup_started: flash_jukebox
