#config_version=4
Mode:
  start_events: ball_starting
  priority: 100

timers:
  start_timer: #This just plays while we show some dots
    start_value: 2
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: mode_jukebox_hurry_started
        action: start

  jukebox_timer:
    start_value: 15
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
        - event: sw_subway
          action: pause
        - event: balldevice_playfield_ball_enter
          action: start
        - event: timer_start_timer_complete
          action: start

logic_blocks:
  counters:
    jukebox_reset_counter:
      count_events: sw_jukebox
      event_when_hit: reset_jukebox_hurryup
      direction: up
      starting_count: 0
      count_complete_value: 5
      disable_on_complete: true




# Need a light show in here that turns off other things and just lights the hurry up shot

# Also need scoring for whatever that shot is
