#config_version=4
mode:
  priority: 500
  start_events: start_world_tour_mode
  stop_events: stop_world_tour, start_jukebox_two_ball

# todo
#when over, has to start something else. Doc says another mode. This mode is complete, though.
# ok, not quite. Need to find a way to fade down the video when the mode ends instead of just
# killing it.

event_player:
  mode_world_tour_started:
    wt_mode_running|5s
    enable_north_america|1s
    fade_out_base_music

  player_world_tour_world_tour_timer_tick{value == 5}:
    slow_down_timer
  wt_australia_complete:
    world_tour_success|2.5s
    world_tour_fade_out|3.7s
    start_jukebox_two_ball|3.7s
    release_wt_ball|3.7s
    stop_world_tour|3.7s
  timer_world_tour_timer_complete:  # fail message QIO todo and adjust timings below
    stop_world_tour|5s
    world_tour_fade_out|3s
    stop_world_tour_timer
    world_tour_fail|3s
    fade_in_base_music|3s
  mode_world_tour_stopping:
    enable_base_left_vuk_hold
  ball_will_end:
    world_tour_fail
  timer_wt_intro_timer_complete:
    release_left_vuk_ball
    disable_base_left_vuk_hold
    release_top_kicker_ball
    disable_base_top_kicker_hold


# We need to set up shots so that we start on the North America shot, then move on to
# Europe, then South America, and finally Australia

#  jackpot:
#    show_when_started: flash
#    show_when_completed: off
#    show_tokens:
#      led: jackpot
#    reset_events: double_jackpot_complete
##    enable_events: mode_jukebox_two_ball_started
#    start_events: mode_jukebox_two_ball_started, double_jackpot_complete
#    complete_events: shot_right_ramp_full_loop_hit
#    events_when_completed: jackpot_complete
#    restart_after_stop_possible: true

achievements:
  wt_north_america:
    show_tokens:
      led: l_north_america
    show_when_started: flash
    show_when_completed: on
#    enable_events: enable_north_america
    start_events: enable_north_america
    complete_events: s_leftorbit_active
    events_when_completed: wt_north_america_complete, add_time
    restart_after_stop_possible: true

  wt_europe:
#    enable_events: wt_north_america_complete
    start_events: wt_north_america_complete
    complete_events: shot_spinner_to_vuk_hit
    events_when_completed: wt_europe_complete, add_time
    show_tokens:
      led: l_europe
    show_when_started: flash
    show_when_completed: on
    restart_after_stop_possible: true

  wt_south_america:
#    enable_events: wt_europe_complete
    start_events: wt_europe_complete
    complete_events: s_rightrampopto_active
    events_when_completed: wt_south_america_complete, add_time
    show_tokens:
      led: l_south_america
    show_when_started: flash
    show_when_completed: on
    restart_after_stop_possible: true

  wt_australia:
#    enable_events: wt_south_america_complete
    start_events: wt_south_america_complete
    complete_events: shot_pops_to_vuk_hit
    events_when_completed: wt_australia_complete
    show_tokens:
      led: l_australia
    show_when_started: flash
    show_when_completed: on
    restart_after_stop_possible: true

shot_profiles:
    wt_advertise:
      states:
        - name: flashing
          show: flash
        - name: complete
          show: on
      loop: no
      advance_on_hit: yes
      block: yes

ball_locks:
  wt_complete:
    balls_to_lock: 1
    lock_devices: bd_top_right_vuk
    enable_events: wt_south_america_complete
    request_new_balls_to_pf: false
    release_one_events: release_wt_ball

timers:
    world_tour_timer:
        start_value: 20
        max_value: 20
        tick_interval: 1.25s
        direction: down
        control_events:
          - event: timer_wt_intro_timer_complete
            action: start
          - event: slow_down_timer #player_world_tour_world_tour_timer_tick{value == 5}
            action: change_tick_interval
            value: 1.5
          - event: add_time
            action: add
            value: 3
          - event: s_subwayopto_active
            action: stop
          - event: stop_world_tour_timer
            action: stop
          - event: balldevice_bd_lower_vuk_ball_eject_success
            action: start
    wt_intro_timer:
        start_value: 3
        direction: down
        control_events:
          - event: mode_world_tour_started
            action: start

# We need a show for each shot. There are four shots, so four shows. Each show will do a light
# sweep (one up-down, one down-up, one left-right, one right-left) and play a video of a plane
# flying across the earth.
#
# Each shot has a specific video. When the player hits the Australia shot, it plays the
# wt_australia video, etc...

show_player:
  wt_south_america_complete:
    south_america:
      loops: 0
    south_america_lights:
      loops: 0
  wt_australia_complete:
    australia:
      loops: 0
    australia_lights:
      loops: 0
  wt_europe_complete:
    europe:
      loops: 0
    europe_lights:
      loops: 0
  wt_north_america_complete:
    north_america:
      loops: 0
    north_america_lights:
      loops: 0

# We also have a video bed for this mode, so we have to figure out a way to play that video bed
# first, then play the plane animations over that, returning to the video when they're done. Let's
# try putting that on a slide, then playing shows over it.

slides:
  wt_complete:
    widgets:
      - type: text
        text: WORLD TOUR
        style: dmd_huge
        font_size: 90
        color: yellow
        animations:
          show_slide:
            - property: font_size
              value: 33
              duration: .2s
            - property: font_size
              value: 33
              duration: .8s
            - property: font_size
              value: 0
              duration: .2s
            - property: opacity
              value: 0
      - type: text
        text: COMPLETE
        style: dmd_huge
        font_size: 90
        opacity: 0
        color: yellow
        animations:
          show_slide:
            - property: font_size
              value: 90
              duration: 1s
            - property: opacity
              value: 1
              duration: 1ms
            - property: font_size
              value: 33
              duration: .2s
            - property: font_size
              value: 33
              duration: 1s

  wt_intro_dmd:
    widgets:
      - type: text
        text: Hit flashing shots
        anchor_y: top
        style: dmd_small
        y: top-1
        anchor_x: right
        x: right-1
      - type: text
        text: to complete the
        style: dmd_small
        anchor_y: bottom
        y: center
        anchor_x: right
        x: right-1
      - type: text
        text: WORLD TOUR!
        style: dmd_big
        anchor_y: bottom
        y: bottom+1
        anchor_x: right
        x: right-1
      - type: video
        video: wt_spinny_globe_dmd
        end_behavior: loop
        anchor_x: left
        x: left
    target: dmd
  world_tour_stage:
    widgets:
      - type: video
        video: wt_boot_scoot
        end_behavior: loop
        animations:
          world_tour_fade_out:
            - property: volume
              value: 0
              duration: 2s
  world_tour_dmd:
    widgets:
      - type: video
        video: wt_spinny_globe_dmd
        end_behavior: loop
        anchor_x: left
        x: left
      - type: text
        text: Time left (world_tour_world_tour_timer_tick)
        anchor_y: bottom
        style: dmd_small
        y: bottom+1
        anchor_x: right
        x: right-1
      - type: text
        text: (player1|score)
        number_grouping: true
        min_digits: 2
        anchor_x: right
        x: right-1
        y: middle
        style: tall title
      - type: text
        text: Each hit = 1 million
        anchor_y: top
        style: dmd_small
        y: top-1
        anchor_x: right
        x: right-1
  world_tour_complete:
    widgets:
      - type: video
        video: wt_spinny_globe_dmd
        end_behavior: loop
        anchor_x: left
        x: left
      - type: text
        text: World Tour
        anchor_y: top
        style: dmd_med
        y: top-4
        anchor_x: right
        x: right-9
      - type: text
        text: Complete!
        number_grouping: true
        min_digits: 2
        anchor_x: right
        x: right-6
        anchor_y: bottom
        y: bottom+1
        style: tall title

slide_player:
  mode_world_tour_starting:
    wt_intro_dmd:
      target: dmd
    world_tour_stage:
      target: stage
  wt_mode_running:
    world_tour_dmd:
      target: dmd
  wt_australia_complete:
    world_tour_complete:
      target: dmd
  world_tour_success:
    wt_complete:
      target: dmd

sound_player:
  world_tour_success:
    slam:
      action: play
      loops: 1


# Now we need a logic block to keep track of shots. When all four are hit, we're done!
# It's not in the rules, but I also added something to extend the time when you hit a shot
# just so that the song plays longer.

# Might not need the sequence
logic_blocks:
    counters:
        stop_adding_time:
            count_events: shot_north_america_hit, shot_europe_hit, shot_south_america_hit, shot_australia_hit
            events_when_hit: add_time
            count_complete_value: 3
            events_when_complete: world_tour_stop_adding_time
            enable_events: mode_world_tour_started
            disable_events: logicblock_stop_adding_time_complete
            multiple_hit_window: 500ms
            persist_state: true

scoring:
    wt_south_america_complete:
      score: 1000000
    wt_north_america_complete:
      score: 1000000
    wt_europe_complete:
      score: 1000000
    wt_australia_complete:
      score: 1000000

