#config_version=5


# What might be fun is to have to make a shot to end Weak Flipper mode. Maybe a shot to the left orbit? 
# It should be getable, but hard.
# Or maybe the flippers randomly get strong again for a second (or just random flipper switch hits)
# But while weak flippers is on, scores double

mode:
  priority: 300
  start_events: start_weak_flippers, s_right_inlane_active
  stop_events: stop_weak_flippers

#                                                      ,d            
#                                                      88            
#   ,adPPYba,  8b       d8   ,adPPYba,  8b,dPPYba,   MM88MMM         
#  a8P_____88  `8b     d8'  a8P_____88  88P'   `"8a    88            
#  8PP"""""""   `8b   d8'   8PP"""""""  88       88    88            
#  "8b,   ,aa    `8b,d8'    "8b,   ,aa  88       88    88,           
#   `"Ybbd8"'   88 "8"       `"Ybbd8"'  88       88    "Y888         
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

event_player:
  mode_weak_flippers_started: # THESE ARE PLACEHOLDERS. SHOW WILL PLAY THESE EVENTS
    - weak_flippers_enabled
  timer_weak_flippers_complete:
    - weak_flippers_disabled
    - stop_weak_flippers|100ms
  mode_weak_flippers_stopping:
    - weak_flippers_disabled

#           88                                                         
#    ,d     ""                                                         
#    88                                                                
#  MM88MMM  88  88,dPYba,,adPYba,    ,adPPYba,  8b,dPPYba,  ,adPPYba,  
#    88     88  88P'   "88"    "8a  a8P_____88  88P'   "Y8  I8[    ""  
#    88     88  88      88      88  8PP"""""""  88           `"Y8ba,   
#    88,    88  88      88      88  "8b,   ,aa  88          aa    ]8I  
#    "Y888  88  88      88      88   `"Ybbd8"'  88          `"YbbdP"' 

timers:
  weak_flippers:
    start_value: 30
    tick_interval: 1s
    direction: down
    control_events:
      - event: mode_weak_flippers_started
        action: start

#             88  88           88                         
#             88  ""           88                         
#             88               88                         
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,  ,adPPYba,  
#  I8[    ""  88  88  a8"    `Y88  a8P_____88  I8[    ""  
#   `"Y8ba,   88  88  8b       88  8PP"""""""   `"Y8ba,   
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa  aa    ]8I  
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'  `"YbbdP"'

slides:
  weak_flippers:
    widgets:
      - type: text
        text: weak

#             88  88           88                                    
#             88  ""           88                                    
#             88               88                                    
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,                        
#  I8[    ""  88  88  a8"    `Y88  a8P_____88                        
#   `"Y8ba,   88  88  8b       88  8PP"""""""                        
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa                        
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

slide_player:
  mode_weak_flippers_started:
    weak_flippers:
      target: stage