#config_version=5
#config_version=4 # Left for reference. Did NOT double check

mode:
  priority: 300
  start_events: start_weak_flippers, s_right_inlane_active
  stop_events: stop_weak_flippers

event_player:
  mode_weak_flippers_started: # THESE ARE PLACEHOLDERS. SHOW WILL PLAY THESE EVENTS
    - weak_flippers_enabled
  timer_weak_flippers_complete:
    - weak_flippers_disabled
    - stop_weak_flippers|100ms
  mode_weak_flippers_stopping:
    - weak_flippers_disabled

timers:
  weak_flippers:
    start_value: 30
    tick_interval: 1s
    direction: down
    control_events:
      - event: mode_weak_flippers_started
        action: start

slides:
  weak_flippers:
    widgets:
      - type: text
        text: weak

slide_player:
  mode_weak_flippers_started:
    weak_flippers:
      target: stage