#config_version=5

mode:
  priority: 500
  start_events: start_music_awards_mode
  stop_events: music_awards_fail, mode_ma_two_ball_stopping, ball_ending

#                                                      ,d            
#                                                      88            
#   ,adPPYba,  8b       d8   ,adPPYba,  8b,dPPYba,   MM88MMM         
#  a8P_____88  `8b     d8'  a8P_____88  88P'   `"8a    88            
#  8PP"""""""   `8b   d8'   8PP"""""""  88       88    88            
#  "8b,   ,aa    `8b,d8'    "8b,   ,aa  88       88    88,           
#   `"Ybbd8"'   88 "8"       `"Ybbd8"'  88       88    "Y888         
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

event_player:
  mode_music_awards_started:
    - mode_running|5s
    - play_intro_slide
    - play_intro_slide2|2.5s
    - fade_out_base_music
  mode_music_awards_stopping:
    - fade_in_base_music
    - enable_base_left_vuk_hold
  ball_will_end:
    - music_awards_fail
  timer_ma_intro_timer_complete:
    - release_left_vuk_ball
    - disable_base_left_vuk_hold
    - release_top_kicker_ball
    - disable_base_top_kicker_hold
  player_song_layer{value==1}: add_bass
  player_song_layer{value==2}: add_other
  player_song_layer{value==3}: add_vocals

#                                                             88     
#                                                             88     
#                                                             88     
#  ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,    ,adPPYb,88     
#  I8[    ""  a8"     "8a  88       88  88P'   `"8a  a8"    `Y88     
#   `"Y8ba,   8b       d8  88       88  88       88  8b       88     
#  aa    ]8I  "8a,   ,a8"  "8a,   ,a88  88       88  "8a,   ,d88     
#  `"YbbdP"'   `"YbbdP"'    `"YbbdP'Y8  88       88   `"8bbdP"Y8     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8' 

# apparently I can't stop sounds when they're played by show with show_player: show_name: action: stop
# so I have to do it here
sound_player:
  mode_music_awards_stopping: 
    ma_bass_layer:
      action: stop
    ma_other_layer:
      action: stop
    ma_drums_layer:
      action: stop
    ma_vocal_layer:
      action: stop

#                                               88                   
#    ,d                                         88                   
#    88                                         88                   
#  MM88MMM  8b,dPPYba,  ,adPPYYba,   ,adPPYba,  88   ,d8             
#    88     88P'   "Y8  ""     `Y8  a8"     ""  88 ,a8"              
#    88     88         ,adPPPPP88  8b          8888[                
#    88,    88  88      88,    ,88  "8a,   ,aa  88`"Yba,             
#    "Y888  88  88      `"8bbdP"Y8   `"Ybbd8"'  88   `Y8a 
#               88
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8' 

track_player:
  add_bass:
    ma_bass_track:
      action: set_volume
      volume: 0.8
  add_other:
    ma_other_track: 
      action: set_volume
      volume: 0.8
  add_vocals:
    ma_vocal_track:
      action: set_volume
      volume: 0.8

#           88                                                         
#    ,d     ""                                                         
#    88                                                                
#  MM88MMM  88  88,dPYba,,adPYba,    ,adPPYba,  8b,dPPYba,  ,adPPYba,  
#    88     88  88P'   "88"    "8a  a8P_____88  88P'   "Y8  I8[    ""  
#    88     88  88      88      88  8PP"""""""  88           `"Y8ba,   
#    88,    88  88      88      88  "8b,   ,aa  88          aa    ]8I  
#    "Y888  88  88      88      88   `"Ybbd8"'  88          `"YbbdP"' 

timers:
  music_awards_timer:
    start_value: 20
    max_value: 20
    tick_interval: 1.25s
    direction: down
    control_events:
      - event: timer_ma_intro_timer_complete
        action: start
      - event: ma_shot_made
        action: add
        value: 8
      - event: s_subwayopto_active
        action: stop
      - event: balldevice_bd_lower_vuk_ball_eject_success
        action: start
  ma_intro_timer:
    start_value: 5
    direction: down
    control_events:
      - event: mode_music_awards_started
        action: start

#             88                                                       
#             88                                                       
#             88                                                       
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   8b      db      d8  ,adPPYba,  
#  I8[    ""  88P'    "8a  a8"     "8a  `8b    d88b    d8'  I8[    ""  
#   `"Y8ba,   88       88  8b       d8   `8b  d8'`8b  d8'    `"Y8ba,   
#  aa    ]8I  88       88  "8a,   ,a8"    `8bd8'  `8bd8'    aa    ]8I  
#  `"YbbdP"'  88       88   `"YbbdP"'       YP      YP      `"YbbdP"' 

shows:
  ma_advertise_show_left:
    - duration: 150ms
      lights:
        (led3): off
        (led1): on
    - duration: 150ms
      lights:
        (led1): on
        (led2): on
    - duration: 150ms
      lights:
        (led1): off
        (led2): on
        (led3): on
    - duration: 150ms
      lights:
        (led2): off
    - duration: 150ms
      lights:
        (led3): off
    - duration: 250ms
      lights:
        (led1): off
        (led2): off
        (led3): off
  ma_advertise_show_right:
    - duration: 150ms
      lights:
        (led3): off
        (led1): on
    - duration: 150ms
      lights:
        (led1): on
        (led2): on
    - duration: 150ms
      lights:
        (led1): off
        (led2): on
        (led3): on
    - duration: 150ms
      lights:
        (led2): off
    - duration: 150ms
      lights:
        (led3): off
    - duration: 250ms
      lights:
        (led1): off
        (led2): off
        (led3): off
  ma_stage_show:
    - duration: 179s
      slides:
        ma_stage_video:
          widgets:
            - type: video
              video: ma_12many_full_no_audio
              end_behavior: stop
          target: stage
      sounds:
        ma_bass_layer:
          action: play
        ma_other_layer:
          action: play
        ma_drums_layer:
          action: play
        ma_vocal_layer:
          action: play
    - duration: 1
      events:
        - play_real_video

#             88                                                     
#             88                                                     
#             88                                                     
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   8b      db      d8           
#  I8[    ""  88P'    "8a  a8"     "8a  `8b    d88b    d8'           
#   `"Y8ba,   88       88  8b       d8   `8b  d8'`8b  d8'            
#  aa    ]8I  88       88  "8a,   ,a8"    `8bd8'  `8bd8'             
#  `"YbbdP"'  88       88   `"YbbdP"'       YP      YP                                                                                
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8' 

show_player:
  mode_music_awards_started:
    ma_advertise_show_right:
      loops: -1
      show_tokens:
        led1: l_right_music_award
        led2: l_ramp_jackpot
        led3: l_south_america
    ma_advertise_show_left:
      loops: -1
      show_tokens:
        led1: l_advance_wizard
        led2: l_north_america
        led3: l_left_music_award
    ma_stage_show:
      loops: 1
  ma_shot_made:
    australia_lights:
      loops: 0
      speed: 2
  mode_music_awards_stopping:
    ma_stage_show:
      action: stop

#                                                       ,d                                        
#                                                       88                                        
#   ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,   MM88MMM   ,adPPYba,  8b,dPPYba,  ,adPPYba,  
#  a8"     ""  a8"     "8a  88       88  88P'   `"8a    88     a8P_____88  88P'   "Y8  I8[    ""  
#  8b          8b       d8  88       88  88       88    88     8PP"""""""  88           `"Y8ba,   
#  "8a,   ,aa  "8a,   ,a8"  "8a,   ,a88  88       88    88,    "8b,   ,aa  88          aa    ]8I  
#   `"Ybbd8"'   `"YbbdP"'    `"YbbdP'Y8  88       88    "Y888   `"Ybbd8"'  88          `"YbbdP"'  

# Two shots: Music Awards are made through either the left orbit or right ramp. Both shots are lit all the time.
# We won't actually create shots for this since we don't need them. 

# Each time a shot is hit, the logic block fires an add_time event. We'll hook that with the timer above, as well
# as with the show player to play a wipe of lights.

# Need a counter to count shots made. Mode is complete at 6. Need to figure out what happens when the mode is over.

counters:
  ma_shot_counter:
    count_events: s_rightrampopto_active, s_leftorbit_active
    events_when_hit: ma_shot_made
    count_complete_value: 3
    events_when_complete: music_awards_stop_adding_time, start_ma_two_ball
    enable_events: mode_music_awards_started
    disable_events: counter_ma_shot_counter_complete
    multiple_hit_window: 500ms

#             88  88           88                                    
#             88  ""           88                                    
#             88               88                                    
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,                        
#  I8[    ""  88  88  a8"    `Y88  a8P_____88                        
#   `"Y8ba,   88  88  8b       88  8PP"""""""                        
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa                        
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'                                                                                     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

slide_player:
  play_real_video:
    music_awards_full_audio_stage:
      target: stage
  play_intro_slide:
    ma_intro_dmd:
      target: dmd
  play_intro_slide2:
    ma_intro_dmd2:
      target: dmd
  mode_running:
    music_awards_dmd:
      target: dmd
  logicblock_stop_adding_time_complete:
    music_awards_complete:
      target: dmd

#             88  88           88                         
#             88  ""           88                         
#             88               88                         
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,  ,adPPYba,  
#  I8[    ""  88  88  a8"    `Y88  a8P_____88  I8[    ""  
#   `"Y8ba,   88  88  8b       88  8PP"""""""   `"Y8ba,   
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa  aa    ]8I  
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'  `"YbbdP"'

slides:
  ma_intro_dmd:
    widgets:
      - type: text
        text: Ramp and Left Orbit
        anchor_y: top
        style: small 
        y: top-17
        anchor_x: right
        x: right-1
      - type: text
        text: add tracks to song
        style: small 
        anchor_y: bottom
        y: top-28
        anchor_x: right
        x: right-1
      - type: text
        text: Music Awards
        style: big 
        anchor_y: top
        y: top-3
        anchor_x: right
        x: right-1
      - type: video
        video: ma_grammy_loop_3
        end_behavior: loop
        anchor_x: left
        x: left
    target: dmd
  ma_intro_dmd2:
    widgets:
      - type: text
        text: Complete song for 5M
        anchor_y: top
        style: small 
        y: top-17
        anchor_x: right
        x: right-1
      - type: text
        text: and multiball!
        style: small 
        anchor_y: bottom
        y: top-28
        anchor_x: right
        x: right-1
      - type: text
        text: Music Awards
        style: big 
        anchor_y: top
        y: top-3
        anchor_x: right
        x: right-1
      - type: video
        video: ma_grammy_loop_3
        end_behavior: loop
        anchor_x: left
        x: left
    target: dmd
  music_awards_full_audio_stage:
    widgets:
      - type: video
        video: ma_12many_full
        end_behavior: loop
  music_awards_dmd:
    widgets:
      - type: video
        video: ma_grammy_loop_3
        end_behavior: loop
        anchor_x: left
        x: left
      - type: text
        text: Time left (music_awards_music_awards_timer_tick)
        anchor_y: bottom
        style: small 
        y: bottom+1
        anchor_x: right
        x: right-1
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        anchor_x: right
        x: right-1
        y: middle
        style: tall_title
      - type: text
        text: Each hit = 500k
        anchor_y: top
        style: small 
        y: top-1
        anchor_x: right
        x: right-1

  music_awards_complete:
    widgets:
      - type: video
        video: ma_grammy_loop
        end_behavior: loop
        anchor_x: left
        x: left
      - type: text
        text: Music Awards
        anchor_y: top
        style: medium 
        y: top-4
        anchor_x: right
        x: right-9
      - type: text
        text: Complete!
        number_grouping: true
        min_digits: 2
        anchor_x: right
        x: right-6
        anchor_y: bottom
        y: bottom+1
        style: tall_title

#                                       88              88           88              
#                                       ""              88           88              
#                                                       88           88              
#  8b       d8  ,adPPYYba,  8b,dPPYba,  88  ,adPPYYba,  88,dPPYba,   88   ,adPPYba,  
#  `8b     d8'  ""     `Y8  88P'   "Y8  88  ""     `Y8  88P'    "8a  88  a8P_____88  
#   `8b   d8'   ,adPPPPP88  88          88  ,adPPPPP88  88       d8  88  8PP"""""""  
#    `8b,d8'    88,    ,88  88          88  88,    ,88  88b,   ,a8"  88  "8b,   ,aa  
#      "8"      `"8bbdP"Y8  88          88  `"8bbdP"Y8  8Y"Ybbd8"'   88   `"Ybbd8"'                                                                                  
#               88                                                                   
#               88                                                                   
#               88                                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,                  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8                  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88                          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88                          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88                          
#  88                               d8'                                              
#  88                              d8' 

variable_player:
  mode_music_awards_started:
    song_layer:
      int: 0
      action: set
  ma_shot_made:
    score: 
      int: 500000
      action: add
    song_layer:
      int: 1
      action: add
  complete_song:
    score: 
      int: 5000000
      action: add
