#config_version=4
mode:
  priority: 500
  start_events: start_music_awards_mode
  stop_events: music_awards_done

# todo
# What to do when the mode is over. No ball captured. Thinking hurry up. 7 seconds to get extra ball?

# Scoring starts at 500k per shot. Both VUKs add 500k to the value. Value needs to reset when mode
# is resumed. This is probably the hardest part of this mode. Can do in mode code, though 100% not sure how.
# Possible to do in config??

# Also need to add in a music awards video pool type thing. It will hook the add_time event.

event_player:
  mode_music_awards_started:
    mode_running|5s
    fade_out_base_music
  music_awards_stop_adding_time:  # success
    music_awards_done|5s
    music_awards_fade_out|3s
    music_awards_success|1s
    fade_in_base_music|4s
  timer_music_awards_timer_complete:  # fail
    music_awards_done|5s
    music_awards_fade_out|3s
    music_awards_fail|1s
  mode_music_awards_stopping:
    fade_in_base_music
    enable_base_left_vuk_hold
  ball_will_end:
    music_awards_fail
  timer_ma_intro_timer_complete:
    release_left_vuk_ball
    disable_base_left_vuk_hold
    release_top_kicker_ball
    disable_base_top_kicker_hold

random_event_player:
    add_time:
      force_all: true
      events:
          play_ma_award1
          play_ma_award2
          play_ma_award3
          play_ma_award4
          play_ma_award5
          play_ma_award6

#Need a timer that starts at 10 secs. Need to add 5 secs per successful shot. Max 10 secs, though.

# /// This timer is a boilerplate mode timer for this game. Specifically, it pauses the timer
# /// the ball goes into the subway and re-starts it when the ball ejects.

timers:
    music_awards_timer:
        start_value: 10
        max_value: 10
        tick_interval: 1.25s
        direction: down
        control_events:
          - event: timer_ma_intro_timer_complete
            action: start
          - event: add_time
            action: add
            value: 5
          - event: s_subwayopto_active
            action: stop
          - event: balldevice_bd_lower_vuk_ball_eject_success
            action: start
    ma_intro_timer:
        start_value: 5
        direction: down
        control_events:
          - event: mode_music_awards_started
            action: start

# Two shots: Music Awards are made through either the left orbit or right ramp. Both shots are lit all the time.
# We won't actually create shots for this since we don't need them. We've got shows to play for each shot, then
# a show player to kick off those shows when the mode starts.

# Each time a shot is hit, the logic block fires an add_time event. We'll hook that with the timer above, as well
# as with the show player to play a wipe of lights.

shows:
  ma_advertise_show_left:
    - duration: 150ms
      leds:
        (led3): off
        (led1): on
    - duration: 150ms
      leds:
        (led1): on
        (led2): on
    - duration: 150ms
      leds:
        (led1): off
        (led2): on
        (led3): on
    - duration: 150ms
      leds:
        (led2): off
    - duration: 150ms
      leds:
        (led3): off
    - duration: 250ms
      leds:
        (led1): off
        (led2): off
        (led3): off
  ma_advertise_show_right:
    - duration: 150ms
      leds:
        (led3): off
        (led1): on
    - duration: 150ms
      leds:
        (led1): on
        (led2): on
    - duration: 150ms
      leds:
        (led1): off
        (led2): on
        (led3): on
    - duration: 150ms
      leds:
        (led2): off
    - duration: 150ms
      leds:
        (led3): off
    - duration: 250ms
      leds:
        (led1): off
        (led2): off
        (led3): off
  play_ma_award1:
    - duration: 200ms
      events:
        music_awards_quick_fade_out
    - duration: 2600ms
      slides:
        award_1:
          target: stage
          priority: 501
          transition_out: fade
    - duration: 200ms
      events:
        music_awards_quick_fade_in
  play_ma_award2:
    - duration: 200ms
      events:
        music_awards_quick_fade_out
    - duration: 6300ms
      slides:
        award_2:
          target: stage
          priority: 501
          transition_out: fade
    - duration: 200ms
      events:
        music_awards_quick_fade_in
  play_ma_award3:
    - duration: 200ms
      events:
        music_awards_quick_fade_out
    - duration: 4430ms
      slides:
        award_3:
          target: stage
          priority: 501
          transition_out: fade
    - duration: 200ms
      events:
        music_awards_quick_fade_in
  play_ma_award4:
    - duration: 200ms
      events:
        music_awards_quick_fade_out
    - duration: 3570ms
      slides:
        award_4:
          target: stage
          priority: 501
          transition_out: fade
    - duration: 200ms
      events:
        music_awards_quick_fade_in
  play_ma_award5:
    - duration: 200ms
      events:
        music_awards_quick_fade_out
    - duration: 6000ms
      slides:
        award_5:
          target: stage
          priority: 501
          transition_out: fade
    - duration: 200ms
      events:
        music_awards_quick_fade_in
  play_ma_award6:
    - duration: 200ms
      events:
        music_awards_quick_fade_out
    - duration: 4000ms
      slides:
        award_6:
          target: stage
          priority: 501
          transition_out: fade
    - duration: 200ms
      events:
        music_awards_quick_fade_in

show_player:
    mode_music_awards_started:
        ma_advertise_show_right:
            loops: -1
            show_tokens:
                led1: l_right_music_award
                led2: l_ramp_jackpot
                led3: l_south_america
        ma_advertise_show_left:
            loops: -1
            show_tokens:
                led1: l_advance_wizard
                led2: l_north_america
                led3: l_left_music_award
    add_time:
        australia_lights:
            loops: 0
            speed: 2
    play_ma_award1:
      play_ma_award1:
        loops: 0
    play_ma_award2:
      play_ma_award2:
        loops: 0
    play_ma_award3:
      play_ma_award3:
        loops: 0
    play_ma_award4:
      play_ma_award4:
        loops: 0
    play_ma_award5:
      play_ma_award5:
        loops: 0
    play_ma_award6:
      play_ma_award6:
        loops: 0

#Need a counter to count shots made. Mode is complete at 6. Need to figure out what happens when the mode is over.

logic_blocks:
    counters:
        stop_adding_time:
            count_events: s_rightrampopto_active, s_leftorbit_active
            events_when_hit: add_time
            count_complete_value: 6
            events_when_complete: music_awards_stop_adding_time
            enable_events: mode_music_awards_started
            disable_events: logicblock_stop_adding_time_complete
            multiple_hit_window: 500ms
            persist_state: true


# This is where we set up the slides that play the different dots and stage slides during the mode.

slide_player:
  mode_music_awards_starting:
    ma_intro_dmd:
      target: dmd
    music_awards_stage:
      target: stage
  mode_running:
    music_awards_dmd:
      target: dmd
  logicblock_stop_adding_time_complete:
    music_awards_complete:
      target: dmd
#  play_ma_award1:
#    award_1:
#      target: stage
#      priority: 501
#      transition_out: fade
#  play_ma_award2:
#    award_2:
#      target: stage
#      priority: 501
#      transition_out: fade
#  play_ma_award3:
#    award_3:
#      target: stage
#      priority: 501
#      transition_out: fade
#  play_ma_award4:
#    award_4:
#      target: stage
#      priority: 501
#      transition_out: fade
#  play_ma_award5:
#    award_5:
#      target: stage
#      priority: 501
#      transition_out: fade
#  play_ma_award6:
#    award_6:
#      target: stage
#      priority: 501
#      transition_out: fade



# And here are the slides referenced above

slides:
  ma_intro_dmd:
    widgets:
      - type: text
        text: Hit flashing shots
        anchor_y: top
        style: dmd_small
        y: top-1
        anchor_x: right
        x: right-1
      - type: text
        text: to collect
        style: dmd_small
        anchor_y: bottom
        y: center
        anchor_x: right
        x: right-1
      - type: text
        text: Music Awards!
        style: dmd_big
        anchor_y: bottom
        y: bottom+1
        anchor_x: right
        x: right-1
      - type: video
        video: ma_grammy_loop_3
        end_behavior: loop
        anchor_x: left
        x: left
    target: dmd
  music_awards_stage:
    widgets:
      - type: video
        video: ma_my_maria
        end_behavior: loop
        animations:
          music_awards_fade_out:
            - property: volume
              value: 0
              duration: 2s
          music_awards_quick_fade_in:
            - property: volume
              value: 1.0
              duration: .2s
          music_awards_quick_fade_out:
            - property: volume
              value: .5
              duration: .8s
  music_awards_dmd:
    widgets:
      - type: video
        video: ma_grammy_loop_3
        end_behavior: loop
        anchor_x: left
        x: left
      - type: text
        text: Time left (music_awards_music_awards_timer_tick)
        anchor_y: bottom
        style: dmd_small
        y: bottom+1
        anchor_x: right
        x: right-1
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        anchor_x: right
        x: right-1
        y: middle
        style: tall title
      - type: text
        text: Each hit = 500k #todo this needs to show whatever the actual score is that we calculate as the mode progresses
        anchor_y: top
        style: dmd_small
        y: top-1
        anchor_x: right
        x: right-1
  music_awards_complete:
    widgets:
      - type: video
        video: ma_grammy_loop
        end_behavior: loop
        anchor_x: left
        x: left
      - type: text
        text: Music Awards
        anchor_y: top
        style: dmd_med
        y: top-4
        anchor_x: right
        x: right-9
      - type: text
        text: Complete!
        number_grouping: true
        min_digits: 2
        anchor_x: right
        x: right-6
        anchor_y: bottom
        y: bottom+1
        style: tall title
  award_1:
    widgets:
      - type: video
        video: ma_award1
        end_behavior: stop
        anchor_x: left
        x: left
  award_2:
    widgets:
      - type: video
        video: ma_award2
        end_behavior: stop
        anchor_x: left
        x: left
  award_3:
    widgets:
      - type: video
        video: ma_award3
        end_behavior: stop
        anchor_x: left
        x: left
  award_4:
    widgets:
      - type: video
        video: ma_award4
        end_behavior: stop
        anchor_x: left
        x: left
  award_5:
    widgets:
      - type: video
        video: ma_award5
        end_behavior: stop
        anchor_x: left
        x: left
  award_6:
    widgets:
      - type: video
        video: ma_award6
        end_behavior: stop
        anchor_x: left
        x: left

scoring:
    add_time:
      score: 500000



