#config_version=5

mode:
  priority: 600
  start_events: start_honky_tonk_multiball
  stop_events: multiball_honky_tonk_ended

#                                                      ,d            
#                                                      88            
#   ,adPPYba,  8b       d8   ,adPPYba,  8b,dPPYba,   MM88MMM         
#  a8P_____88  `8b     d8'  a8P_____88  88P'   `"8a    88            
#  8PP"""""""   `8b   d8'   8PP"""""""  88       88    88            
#  "8b,   ,aa    `8b,d8'    "8b,   ,aa  88       88    88,           
#   `"Ybbd8"'   88 "8"       `"Ybbd8"'  88       88    "Y888         
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

event_player:
  mode_honky_tonk_multiball_started:
    - fade_out_base_music
    - stop_quarters_mode
    - block_jukebox_hits
    - start_hkmb_achievements|2s
    - stop_mission_select
  mode_honky_tonk_multiball_stopping:
    - fade_in_base_music
    - start_quarters_mode
    - unblock_jukebox_hits
    - disable_htmb_intro_lock
  htmb_double_jackpot_complete:
    - duck
    - unduck|1.5s
  htmb_jackpot_complete:
    - duck
    - unduck|1.5s


#  88                       88  88                       
#  88                       88  88                       
#  88                       88  88                       
#  88,dPPYba,   ,adPPYYba,  88  88                       
#  88P'    "8a  ""     `Y8  88  88                       
#  88       d8  ,adPPPPP88  88  88                       
#  88b,   ,a8"  88,    ,88  88  88                       
#  8Y"Ybbd8"'   `"8bbdP"Y8  88  88                       
#  88                        88           88             
#  88                        88           88             
#  88                        88           88             
#  88,dPPYba,    ,adPPYba,   88   ,adPPYb,88  ,adPPYba,  
#  88P'    "8a  a8"     "8a  88  a8"    `Y88  I8[    ""  
#  88       88  8b       d8  88  8b       88   `"Y8ba,   
#  88       88  "8a,   ,a8"  88  "8a,   ,d88  aa    ]8I  
#  88       88   `"YbbdP"'   88   `"8bbdP"Y8  `"YbbdP"' 


ball_holds:
  htmb_intro_lock:
    balls_to_hold: 1
    hold_devices: bd_top_right_vuk
    enable_events: mode_honky_tonk_multiball_started
    release_one_events: slide_honky_tonk_instructions_removed
    disable_events: disable_htmb_intro_lock

#                                                             88     
#                                                             88     
#                                                             88     
#  ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,    ,adPPYb,88     
#  I8[    ""  a8"     "8a  88       88  88P'   `"8a  a8"    `Y88     
#   `"Y8ba,   8b       d8  88       88  88       88  8b       88     
#  aa    ]8I  "8a,   ,a8"  "8a,   ,a88  88       88  "8a,   ,d88     
#  `"YbbdP"'   `"YbbdP"'    `"YbbdP'Y8  88       88   `"8bbdP"Y8     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

sound_player:
  htmb_jackpot_complete:
    jackpot:
      action: play
      loops: 0
  htmb_double_jackpot_complete:
    double_jackpot:
      action: play
      loops: 0

#                                   88           88  88                       88  88             
#                                   88    ,d     ""  88                       88  88             
#                                   88    88         88                       88  88             
#  88,dPYba,,adPYba,   88       88  88  MM88MMM  88  88,dPPYba,   ,adPPYYba,  88  88  ,adPPYba,  
#  88P'   "88"    "8a  88       88  88    88     88  88P'    "8a  ""     `Y8  88  88  I8[    ""  
#  88      88      88  88       88  88    88     88  88       d8  ,adPPPPP88  88  88   `"Y8ba,   
#  88      88      88  "8a,   ,a88  88    88,    88  88b,   ,a8"  88,    ,88  88  88  aa    ]8I  
#  88      88      88   `"YbbdP'Y8  88    "Y888  88  8Y"Ybbd8"'   `"8bbdP"Y8  88  88  `"YbbdP"' 

multiballs:
  honky_tonk:
    ball_count: 3
    shoot_again: 10s
    start_events: slide_honky_tonk_instructions_removed


#             88  88           88                                    
#             88  ""           88                                    
#             88               88                                    
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,                        
#  I8[    ""  88  88  a8"    `Y88  a8P_____88                        
#   `"Y8ba,   88  88  8b       88  8PP"""""""                        
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa                        
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'


slide_player:
  mode_honky_tonk_multiball_started:
    honky_tonk_dmd_intro:
      expire: 5.4s
      target: dmd
  slide_honky_tonk_dmd_intro_removed:
    honky_tonk_stage:
      target: stage
    honky_tonk_instructions:
      target: dmd
      expire: 5s
  slide_honky_tonk_instructions_removed:
    honky_tonk_dmd:
      target: dmd
  sw_jukebox_hit:
    honky_tonk_dmd:
      target: dmd
  htmb_jackpot_complete:
    jackpot_slide:
      target: dmd
      expire: 1.5s
  htmb_double_jackpot_complete:
    double_jackpot_slide:
      target: dmd
      expire: 1.5s

#             88  88           88                         
#             88  ""           88                         
#             88               88                         
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,  ,adPPYba,  
#  I8[    ""  88  88  a8"    `Y88  a8P_____88  I8[    ""  
#   `"Y8ba,   88  88  8b       88  8PP"""""""   `"Y8ba,   
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa  aa    ]8I  
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'  `"YbbdP"'

slides:
  honky_tonk_dmd:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        style: huge 
        font_size: 24
        anchor_y: top
        y: top+3
      - type: text
        text: JACKPOT = (player|htmb_jackpot_value)
        number_grouping: true
        style: medium 
        color: gold
        anchor_y: bottom
        y: bottom+1
        animations:
          show_slide:
            - property: opacity
              value: 1
              duration: .3s
            - property: opacity
              value: .6
              duration: .3s
              repeat: true
      - type: rectangle
        width: 128
        height: 32
        color: black
        opacity: .5
      - type: image
        image: honky_tonk

  honky_tonk_instructions:
    widgets:
      - type: text
        text: HONKY TONK
        style: big #dmd_big
        anchor_y: top
        y: top
        color: yellow
      - type: text
        text: MULTIBALL
        style: huge 
        anchor_y: top
        y: top-8
        color: red
      - type: text
        style: small 
        text: JACKPOT STARTS AT 250k
        anchor_y: bottom
        y: bottom+1
        animations:
          show_slide:
            - property: opacity
              value: 1
              duration: 2s
            - property: opacity
              value: 0
      - type: text
        style: small 
        opacity: 0
        anchor_y: bottom
        y: bottom+1
        text: JUKEBOX ADDS TO JACKPOT
        animations:
          show_slide:
            - property: opacity
              value: 0
              duration: 2s
            - property: opacity
              value: 1
  honky_tonk_dmd_intro:
    widgets:
      - type: video
        video: htmb_dmd_intro
        anchor_x: left
        x: left
  ball_saved:
    widgets:
      - type: text
        text: BALL SAVED!
        expire: 2s
        style: huge 
  honky_tonk_stage: 
    widgets:
      - type: video
        volume: 0.4
        video: htmb_miss_honky_tonk
        end_behavior: loop
        control_events:
          - event: duck
            action: volume
            value: .4
          - event: unduck
            action: volume
            value: 1.0  
  double_jackpot_slide:
    widgets:
      - type: image
        image: double_jackpot_top
        anchor_x: left
        x: right
        anchor_y: top
        y: top
        animations:
          show_slide:
            - property: x
              value: 0
              duration: .3s
      - type: image
        image: double_jackpot_bottom
        anchor_x: left
        x: right
        animations:
          show_slide:
            - property: x
              value: 128
              duration: .5s
            - property: x
              value: 0
              duration: .3s
  jackpot_slide:
    widgets:
      - type: image
        image: jackpot
        anchor_x: left
        x: right
        anchor_y: top
        y: top
        animations:
          show_slide:
            - property: x
              value: 0
              duration: .2s

#                          88           88                                                                                                        
#                          88           ""                                                                                      ,d                
#                          88                                                                                                   88                
#  ,adPPYYba,   ,adPPYba,  88,dPPYba,   88   ,adPPYba,  8b       d8   ,adPPYba,  88,dPYba,,adPYba,    ,adPPYba,  8b,dPPYba,   MM88MMM  ,adPPYba,  
#  ""     `Y8  a8"     ""  88P'    "8a  88  a8P_____88  `8b     d8'  a8P_____88  88P'   "88"    "8a  a8P_____88  88P'   `"8a    88     I8[    ""  
#  ,adPPPPP88  8b          88       88  88  8PP"""""""   `8b   d8'   8PP"""""""  88      88      88  8PP"""""""  88       88    88      `"Y8ba,   
#  88,    ,88  "8a,   ,aa  88       88  88  "8b,   ,aa    `8b,d8'    "8b,   ,aa  88      88      88  "8b,   ,aa  88       88    88,    aa    ]8I  
#  `"8bbdP"Y8   `"Ybbd8"'  88       88  88   `"Ybbd8"'      "8"       `"Ybbd8"'  88      88      88   `"Ybbd8"'  88       88    "Y888  `"YbbdP"'

achievements:
  htmb_jackpot:
    show_when_started: flash_fast
    show_when_completed: off
    show_tokens:
      led: jackpot
    reset_events: htmb_jackpot_complete
    start_events: start_hkmb_achievements, htmb_double_jackpot_complete
    complete_events: seq_shot_right_ramp_full_loop_hit
    events_when_completed: htmb_jackpot_complete
    restart_after_stop_possible: true

  htmb_double_jackpot:
    show_when_started: flash_fast
    show_when_completed: off
    show_tokens:
      led: double_jackpot
    reset_events: htmb_double_jackpot_complete
    start_events: htmb_jackpot_complete
    complete_events: s_topkicker_active
    events_when_completed: htmb_double_jackpot_complete
    restart_after_stop_possible: true


#                                       88              88           88              
#                                       ""              88           88              
#                                                       88           88              
#  8b       d8  ,adPPYYba,  8b,dPPYba,  88  ,adPPYYba,  88,dPPYba,   88   ,adPPYba,  
#  `8b     d8'  ""     `Y8  88P'   "Y8  88  ""     `Y8  88P'    "8a  88  a8P_____88  
#   `8b   d8'   ,adPPPPP88  88          88  ,adPPPPP88  88       d8  88  8PP"""""""  
#    `8b,d8'    88,    ,88  88          88  88,    ,88  88b,   ,a8"  88  "8b,   ,aa  
#      "8"      `"8bbdP"Y8  88          88  `"8bbdP"Y8  8Y"Ybbd8"'   88   `"Ybbd8"'
#               88                                                                   
#               88                                                                   
#               88                                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,                  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8                  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88                          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88                          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88                          
#  88                               d8'                                              
#  88                              d8' 


variable_player:
  mode_honky_tonk_multiball_started:
    htmb_jackpot_value:
      int: 250000
      action: set
    htmb_balls_locked:
      int: 0
      action: set
  sw_jukebox_hit:
    htmb_jackpot_value:
      int: 50000
  htmb_jackpot_complete:
    score: current_player.htmb_jackpot_value
  htmb_double_jackpot_complete:
    score: current_player.htmb_jackpot_value * 2


