#config_version=4
mode:
  priority: 600
  start_events: start_honky_tonk_multiball
  stop_events: multiball_honky_tonk_ended

event_player:
  mode_honky_tonk_multiball_started:
    fade_out_base_music
    stop_quarters_mode
    block_jukebox_hits
    start_hkmb_achievements|2s
    stop_mission_select
  mode_honky_tonk_multiball_stopping:
    fade_in_base_music
    start_quarters_mode
    unblock_jukebox_hits
  htmb_double_jackpot_complete:
    duck
    unduck|1.5s
  htmb_jackpot_complete:
    duck
    unduck|1.5s

sound_player:
  htmb_jackpot_complete:
    jackpot:
      action: play
      loops: 0
  htmb_double_jackpot_complete:
    double_jackpot:
      action: play
      loops: 0

multiballs:
  honky_tonk:
    ball_count: 3
    shoot_again: 10s
    start_events: mode_honky_tonk_multiball_started

slide_player:
  mode_honky_tonk_multiball_started:
    honky_tonk_dmd_intro:
      expire: 5.4s
      target: dmd
  slide_honky_tonk_dmd_intro_removed:
    honky_tonk_stage:
      target: stage
    honky_tonk_instructions:
      target: dmd
      expire: 5s
  slide_honky_tonk_instructions_removed:
    honky_tonk_dmd:
      target: dmd
  htmb_jackpot_complete:
    jackpot_slide:
      target: dmd
      expire: 1.5s
  htmb_double_jackpot_complete:
    double_jackpot_slide:
      target: dmd
      expire: 1.5s

slides:
  honky_tonk_dmd:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        style: dmd_huge
        font_size: 24
        anchor_y: top
        y: top+3
      - type: text
        text: JACKPOT = (player|htmb_jackpot_value)
        number_grouping: true
        style: dmd_med
        color: gold
        anchor_y: bottom
        y: bottom+1
        animations:
          show_slide:
            - property: opacity
              value: 1
              duration: .3s
            - property: opacity
              value: .6
              duration: .3s
              repeat: true
      - type: rectangle
        width: 128
        height: 32
        color: black
        opacity: .5
      - type: image
        image: honky_tonk

  honky_tonk_instructions:
    widgets:
      - type: text
        text: HONKY TONK
        style: dmd_big
        anchor_y: top
        y: top
        color: yellow
      - type: text
        text: MULTIBALL
        style: dmd_huge
        anchor_y: top
        y: top-8
        color: red
      - type: text
        style: dmd_small
        text: JACKPOT STARTS AT 250k
        anchor_y: bottom
        y: bottom
        animations:
          show_slide:
            - property: opacity
              value: 1
              duration: 2s
            - property: opacity
              value: 0
      - type: text
        style: dmd_small
        opacity: 0
        anchor_y: bottom
        y: bottom
        text: JUKEBOX ADDS TO JACKPOT
        animations:
          show_slide:
            - property: opacity
              value: 0
              duration: 2s
            - property: opacity
              value: 1
  honky_tonk_dmd_intro:
    widgets:
      - type: video
        video: htmb_dmd_intro
        anchor_x: left
        x: left
  ball_saved:
    widgets:
      - type: text
        text: BALL SAVED!
        expire: 2s
        style: dmd_huge
  honky_tonk_stage:
    widgets:
      - type: video
        video: htmb_miss_honky_tonk
        end_behavior: loop
        animations:
          duck:
            - property: volume
              value: .4
              duration: .01s
          unduck:
            - property: volume
              value: 1
              duration: .5s
  double_jackpot_slide:
    widgets:
      - type: image
        image: double_jackpot_top
        anchor_x: left
        x: right
        anchor_y: top
        y: top
        animations:
          show_slide:
            - property: x
              value: 0
              duration: .3s
      - type: image
        image: double_jackpot_bottom
        anchor_x: left
        x: right
        animations:
          show_slide:
            - property: x
              value: 128
              duration: .5s
            - property: x
              value: 0
              duration: .3s
  jackpot_slide:
    widgets:
      - type: image
        image: jackpot
        anchor_x: left
        x: right
        anchor_y: top
        y: top
        animations:
          show_slide:
            - property: x
              value: 0
              duration: .2s

achievements:
  htmb_jackpot:
    show_when_started: flash
    show_when_completed: off
    show_tokens:
      led: jackpot
    reset_events: s_topkicker_active
    start_events: start_hkmb_achievements, htmb_double_jackpot_complete
    complete_events: shot_right_ramp_full_loop_hit
    events_when_completed: htmb_jackpot_complete
    restart_after_stop_possible: true

  htmb_double_jackpot:
    show_when_started: flash
    show_when_completed: off
    show_tokens:
      led: double_jackpot
    reset_events: shot_right_ramp_full_loop_hit
    start_events: htmb_jackpot_complete
    complete_events: s_topkicker_active
    events_when_completed: htmb_double_jackpot_complete
    restart_after_stop_possible: true

scoring:
  mode_honky_tonk_multiball_started:
    htmb_jackpot_value:
      score: 250000
      action: set
    htmb_balls_locked:
      score: 0
      action: set
  sw_jukebox:
    htmb_jackpot_value:
      score: 150000
  htmb_jackpot_complete:
    score: current_player.htmb_jackpot_value
  htmb_double_jackpot_complete:
    score: current_player.htmb_jackpot_value * 2


