#config_version=6


# todo spot quarter feature
# QIO for quarter_25m



#                                            88              
#                                            88              
#                                            88              
#  88,dPYba,,adPYba,    ,adPPYba,    ,adPPYb,88   ,adPPYba,  
#  88P'   "88"    "8a  a8"     "8a  a8"    `Y88  a8P_____88  
#  88      88      88  8b       d8  8b       88  8PP"""""""  
#  88      88      88  "8a,   ,a8"  "8a,   ,d88  "8b,   ,aa  
#  88      88      88   `"YbbdP"'    `"8bbdP"Y8   `"Ybbd8"'

mode:
  start_events: mode_base_started, start_quarters_mode
  stop_events: stop_quarters_mode
  priority: 110

#                                                             88     
#                                                             88     
#                                                             88     
#  ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,    ,adPPYb,88     
#  I8[    ""  a8"     "8a  88       88  88P'   `"8a  a8"    `Y88     
#   `"Y8ba,   8b       d8  88       88  88       88  8b       88     
#  aa    ]8I  "8a,   ,a8"  "8a,   ,a88  88       88  "8a,   ,d88     
#  `"YbbdP"'   `"YbbdP"'    `"YbbdP'Y8  88       88   `"8bbdP"Y8     
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

sound_player:
  quarters_lit_hit:
      quarter:
          action: play
          loops: 0
  quarters_collected_hit:
      beats:
        action: play
        loops: 0

#                                       88              88           88              
#                                       ""              88           88              
#                                                       88           88              
#  8b       d8  ,adPPYYba,  8b,dPPYba,  88  ,adPPYYba,  88,dPPYba,   88   ,adPPYba,  
#  `8b     d8'  ""     `Y8  88P'   "Y8  88  ""     `Y8  88P'    "8a  88  a8P_____88  
#   `8b   d8'   ,adPPPPP88  88          88  ,adPPPPP88  88       d8  88  8PP"""""""  
#    `8b,d8'    88,    ,88  88          88  88,    ,88  88b,   ,a8"  88  "8b,   ,aa  
#      "8"      `"8bbdP"Y8  88          88  `"8bbdP"Y8  8Y"Ybbd8"'   88   `"Ybbd8"'
#               88                                                                   
#               88                                                                   
#               88                                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,                  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8                  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88                          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88                          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88                          
#  88                               d8'                                              
#  88                              d8' 

#scoring: #leaving for reference
variable_player:
  mode_quarters_started:
    quarters_this_ball:
      int: 0
      action: set
  quarters_lit_hit:
    score: 2510
    quarters: 1 
  quarters_lit_complete:
    score: 15170
    #quarters: 3
  quarters_collected_hit:
    score: 30 
  quarter_25m:
    score: 25000000
  super_quarters:
    score: 250000
  counter_bonus_multiplier_hit:
    bonus_multiplier:
      int: 1

#                                                      ,d            
#                                                      88            
#   ,adPPYba,  8b       d8   ,adPPYba,  8b,dPPYba,   MM88MMM         
#  a8P_____88  `8b     d8'  a8P_____88  88P'   `"8a    88            
#  8PP"""""""   `8b   d8'   8PP"""""""  88       88    88            
#  "8b,   ,aa    `8b,d8'    "8b,   ,aa  88       88    88,           
#   `"Ybbd8"'   88 "8"       `"Ybbd8"'  88       88    "Y888         
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

event_player:

  light_quarters_extra_ball: light_extra_ball

  player_quarters{value <= 3}:
    collect_quarters:
      next_award_name: MYSTERY
      next_award_quarters: 3

  player_quarters{current_player.quarters == 3}: light_mystery|2s

  player_quarters{value >= 4 and value <= 6}:
    collect_quarters:
      next_award_name: QUARTER MULTIBALL
      next_award_quarters: 6

  player_quarters{current_player.quarters == 6}: start_quarters_multiball|2s

  player_quarters{value >= 7 and value <= 9}:
    collect_quarters:
      next_award_name: LIGHT EXTRA BALL
      next_award_quarters: 9

  player_quarters{current_player.quarters == 9}: light_quarters_extra_ball|2s

  player_quarters{value >= 10 and value <= 15}:
    collect_quarters:
      next_award_name: MYSTERY
      next_award_quarters: 15

  player_quarters{current_player.quarters == 15}: light_mystery|2s

  player_quarters{value >= 10 and value <= 20}:
    collect_quarters:
      next_award_name: LIGHT SPECIAL
      next_award_quarters: 20

  player_quarters{current_player.quarters == 20}: light_special|2s

  player_quarters{value >= 21 and value <= 25}:
    collect_quarters:
      next_award_name: MYSTERY
      next_award_quarters: 6

  player_quarters{current_player.quarters == 25}: light_mystery|2s

  player_quarters{value >= 21 and value <= 32}:
    collect_quarters:
      next_award_name: 25M POINTS
      next_award_quarters: 32

  player_quarters{current_player.quarters == 32}: quarter_25m|2s

  player_quarters{current_player.quarters >= 33}: quarters_maxed

#                                                       ,d                                        
#                                                       88                                        
#   ,adPPYba,   ,adPPYba,   88       88  8b,dPPYba,   MM88MMM   ,adPPYba,  8b,dPPYba,  ,adPPYba,  
#  a8"     ""  a8"     "8a  88       88  88P'   `"8a    88     a8P_____88  88P'   "Y8  I8[    ""  
#  8b          8b       d8  88       88  88       88    88     8PP"""""""  88           `"Y8ba,   
#  "8a,   ,aa  "8a,   ,a8"  "8a,   ,a88  88       88    88,    "8b,   ,aa  88          aa    ]8I  
#   `"Ybbd8"'   `"YbbdP"'    `"YbbdP'Y8  88       88    "Y888   `"Ybbd8"'  88          `"YbbdP"'  


#logic_blocks:
counters:
  bonus_multiplier:
    count_events: quarters_collected_complete  # posted by the shot group
    #player_variable: bonus_multiplier
    starting_count: 1
    count_complete_value: 4
    reset_on_complete: false

#             88                                            
#             88                          ,d                
#             88                          88                
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   MM88MMM  ,adPPYba,  
#  I8[    ""  88P'    "8a  a8"     "8a    88     I8[    ""  
#   `"Y8ba,   88       88  8b       d8    88      `"Y8ba,   
#  aa    ]8I  88       88  "8a,   ,a8"    88,    aa    ]8I  
#  `"YbbdP"'  88       88   `"YbbdP"'     "Y888  `"YbbdP"' 

shots:
  quarter_1:
    switch: s_toprightstandup
    profile: quarters
    show_tokens:
      lights: l_top_quarter
  quarter_2:
    switch: s_rightbanktop
    profile: quarters
    show_tokens:
      lights: l_middle_quarter
  quarter_3:
    switch: s_rightbankbottom
    profile: quarters
    show_tokens:
      lights: l_bottom_quarter

#             88                                                              
#             88                          ,d                                  
#             88                          88                                  
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   MM88MMM                               
#  I8[    ""  88P'    "8a  a8"     "8a    88                                  
#   `"Y8ba,   88       88  8b       d8    88                                  
#  aa    ]8I  88       88  "8a,   ,a8"    88,                                 
#  `"YbbdP"'  88       88   `"YbbdP"'     "Y888                                                                                                      
#                                                                             
#   ,adPPYb,d8  8b,dPPYba,   ,adPPYba,   88       88  8b,dPPYba,   ,adPPYba,  
#  a8"    `Y88  88P'   "Y8  a8"     "8a  88       88  88P'    "8a  I8[    ""  
#  8b       88  88          8b       d8  88       88  88       d8   `"Y8ba,   
#  "8a,   ,d88  88          "8a,   ,a8"  "8a,   ,a88  88b,   ,a8"  aa    ]8I  
#   `"YbbdP"Y8  88           `"YbbdP"'    `"YbbdP'Y8  88`YbbdP"'   `"YbbdP"'  
#   aa,    ,88                                        88                      
#    "Y8bbdP"                                         88 

shot_groups:
  quarters:
    shots: quarter_1, quarter_2, quarter_3
    enable_events: mode_quarters_started
    restart_events: quarters_collected_complete

#             88                                                                 
#             88                          ,d                                     
#             88                          88                                     
#  ,adPPYba,  88,dPPYba,    ,adPPYba,   MM88MMM                                  
#  I8[    ""  88P'    "8a  a8"     "8a    88                                     
#   `"Y8ba,   88       88  8b       d8    88                                     
#  aa    ]8I  88       88  "8a,   ,a8"    88,                                    
#  `"YbbdP"'  88       88   `"YbbdP"'     "Y888                                  
#                                           ad88  88  88                         
#                                          d8"    ""  88                         
#                                          88         88                         
#  8b,dPPYba,   8b,dPPYba,   ,adPPYba,   MM88MMM  88  88   ,adPPYba,  ,adPPYba,  
#  88P'    "8a  88P'   "Y8  a8"     "8a    88     88  88  a8P_____88  I8[    ""  
#  88       d8  88          8b       d8    88     88  88  8PP"""""""   `"Y8ba,   
#  88b,   ,a8"  88          "8a,   ,a8"    88     88  88  "8b,   ,aa  aa    ]8I  
#  88`YbbdP"'   88           `"YbbdP"'     88     88  88   `"Ybbd8"'  `"YbbdP"'  
#  88                                                                            
#  88 

shot_profiles:
    quarters:
        states:
          - name: lit
            show: flash
          - name: collected
            show: "on"

#             88  88           88                                    
#             88  ""           88                                    
#             88               88                                    
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,                        
#  I8[    ""  88  88  a8"    `Y88  a8P_____88                        
#   `"Y8ba,   88  88  8b       88  8PP"""""""                        
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa                        
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'
#               88                                                   
#               88                                                   
#               88                                                   
#  8b,dPPYba,   88  ,adPPYYba,  8b       d8   ,adPPYba,  8b,dPPYba,  
#  88P'    "8a  88  ""     `Y8  `8b     d8'  a8P_____88  88P'   "Y8  
#  88       d8  88  ,adPPPPP88   `8b   d8'   8PP"""""""  88          
#  88b,   ,a8"  88  88,    ,88    `8b,d8'    "8b,   ,aa  88          
#  88`YbbdP"'   88  `"8bbdP"Y8      Y88'      `"Ybbd8"'  88          
#  88                               d8'                              
#  88                              d8'

slide_player:
  collect_quarters:
    collect_quarters:
      expire: 2s
  quarters_maxed:
    quarters_maxed:
      expire: 2s

#             88  88           88                         
#             88  ""           88                         
#             88               88                         
#  ,adPPYba,  88  88   ,adPPYb,88   ,adPPYba,  ,adPPYba,  
#  I8[    ""  88  88  a8"    `Y88  a8P_____88  I8[    ""  
#   `"Y8ba,   88  88  8b       88  8PP"""""""   `"Y8ba,   
#  aa    ]8I  88  88  "8a,   ,d88  "8b,   ,aa  aa    ]8I  
#  `"YbbdP"'  88  88   `"8bbdP"Y8   `"Ybbd8"'  `"YbbdP"'

slides:
  collect_quarters:
    widgets:
      - type: text
        text: QUARTER COLLECTED!
        style: big #dmd_big
        color: lime
        y: 25
      - type: text
        text: (player|bonus_multiplier)X
        style: huge 
        anchor_x: left
        x: 0
        y: 8
        color: yellow
      - type: text
        text: BONUS
        style: small 
        x: 29
        y: 3
        color: yellow
      - type: text
        text: "TOTAL QUARTERS: (player|quarters)"
        style: small 
        anchor_x: right
        x: right-1
      - type: text
        text: (next_award_name) AT (next_award_quarters)
        style: small 
        anchor_x: right
        x: right-1
        y: 10
  quarters_maxed:
    widgets:
      - type: text
        text: QUARTER COLLECTED!
        style: big #dmd_big
        color: lime
        y: 25
      - type: text
        text: (player|bonus_multiplier)X
        style: huge 
        anchor_x: left
        x: 0
        y: 8
        color: yellow
      - type: text
        text: BONUS
        style: small 
        x: 29
        y: 3
        color: yellow
      - type: text
        text: "TOTAL QUARTERS: (player|quarters)"
        style: small 
        anchor_x: right
        x: right-1
      - type: text
        text: NEXT QUARTER 250K
        style: small 
        anchor_x: right
        x: right-1
        y: 10

#                             ,d                             
#                             88                             
#   ,adPPYba,  8b,     ,d8  MM88MMM  8b,dPPYba,  ,adPPYYba,  
#  a8P_____88   `Y8, ,8P'     88     88P'   "Y8  ""     `Y8  
#  8PP"""""""     )888(       88     88          ,adPPPPP88  
#  "8b,   ,aa   ,d8" "8b,     88,    88          88,    ,88  
#   `"Ybbd8"'  8P'     `Y8    "Y888  88          `"8bbdP"Y8  
#                                                            
#  88                       88  88                           
#  88                       88  88                           
#  88                       88  88                           
#  88,dPPYba,   ,adPPYYba,  88  88  ,adPPYba,                
#  88P'    "8a  ""     `Y8  88  88  I8[    ""                
#  88       d8  ,adPPPPP88  88  88   `"Y8ba,                 
#  88b,   ,a8"  88,    ,88  88  88  aa    ]8I                
#  8Y"Ybbd8"'   `"8bbdP"Y8  88  88  `"YbbdP"'

extra_balls:
  quarters:
    light_events: light_quarters_extra_ball
